### ISSUE TITLE
Add plugin view

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#1015]
## Purpose
It would be nice to have a basic view of installed plugins. @JustArchi can you add API for that?

**Comment by JustArchi** [comment]
Sure, I can display some basic info such as `Name` and `Version` of each plugin.

**Comment by MrBurrBurr** [comment]
Cool, thanks.

Can a plugin be installed (as in its inside `plugins` folder) but not loaded? This would also be a neat thing to display.

**Comment by JustArchi** [comment]
We do not keep a track of those. Either plugin is loaded or it's discarded as invalid.

**Comment by JustArchi** [comment]
`GET /Api/Plugins` example:

```
{
  "Result": [
    {
      "Name": "SteamTokenDumperPlugin",
      "Version": "4.2.3.4"
    }
  ],
  "Message": "OK",
  "Success": true
}
```

`Name` and `Version` is guaranteed, but the plugins can extend the data with additional details:

```
{
  "Result": [
    {
      "IsEnabled": false,
      "Name": "SteamTokenDumperPlugin",
      "Version": "4.2.3.4"
    }
  ],
  "Message": "OK",
  "Success": true
}
```

Looks good to me.

**Comment by JustArchi** [comment]
Additional details can be displayed in some way if available, plugins developers can use it for including some data about current state of their plugins. `SteamTokenDumperPlugin` will expose `IsEnabled`.

**Comment by JustArchi** [comment]
Added into mainline ASF.

**Comment by MrBurrBurr** [comment]
Thanks! 👍
