### ISSUE TITLE
Make use of mice's wheel on Commands page to select previously executed command

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1018]
## Purpose
Scrolling wheel up will lead to the most recent executed command in the commands history and further to the oldest one and vice versa

## Alternatives
Pressing up and down arrows on keyboard

## Additional information
ASF-ui users can execute commands by pressing little arrow on Commands page, implemeting this feature will ease executing most used and repetitive commands, as there will be no need to reach for up and down arrows on keyboard.
Another case: only mice is at hands with no keyboard.

**Comment by Ryzhehvost** [comment]
Scrolling wheel is used for scrolling already, and it would be inconvenient if it will do something else instead.

**Comment by Botan626** [comment]
Can you possibly define the area in whatever units around that flashing cursor in which mouse scrolling will travel between executed commands?

**Comment by Botan626** [comment]
## Add Execute button in Commands window
https://github.com/JustArchiNET/ASF-ui/issues/337

**Comment by Ryzhehvost** [comment]
Is there other applications that support this kind of behavior? I see no reason to implement some ui concept that nobody expecting, because it means nobody will use it, and when accidentally triggered - it may actually annoy people.

**Comment by Botan626** [comment]
>Is there other applications that support this kind of behavior?
Idk, I just thought of such solution couple of moments later when I was told mouse scrolling is already used to scroll the whole page.

>because it means nobody will use it
Why? Just mention about it in the ASF-ui description on the project's main github page.

>it may actually annoy people
People get annoyed from different reasons, I hate to reach for up and down arrows with my left hand just to find a command I executed millions times before for example (not loot asf).

**Comment by Ryzhehvost** [comment]
It's counter-productive to make changes just for one user. Standard ui controls is good, because people expect them to be there. Non-standard ui controls make no sense.

**Comment by Botan626** [comment]
>It's counter-productive to make changes just for one user

Why one user? How many people you already asked?

>Standard 

What is standard and what is not? How do you define?

**Comment by Botan626** [comment]
I will say most of population on the Earth is right handed and has mice in their right prevailing part of the time spending at PC.
So am I.

**Comment by Ryzhehvost** [comment]
> Why one user? How many people you already asked?

Why would I? It's your task to prove this change is useful and needs to be implemented.  If you can't show that many people want it - we will consider it just your whim.

> What is standard and what is not? How do you define?

Again, it's your task to prove if it's standard. Give me RFC number or other document describing this feature, and I will instantly agree that it's standard. If you did not - we will consider it's non-standard.

>I will say most of population on the Earth is right handed and has mice in their right prevailing part of the time spending at PC.
So am I.

Sorry, but this proves nothing. You still have left hand free.

**Comment by Botan626** [comment]
> It's your task

No, it's you said it will benefit just one user, so it's your task now to back up your words.

> it's your task to prove if it's standard

You mentioned 'standard' again. So what is it? The features already implemented? So the first car with auto pilot is not standard because all previous cars were produced without auto pilot?

> You still have left hand free.

I know I have, knew it before opened this feature request.

**Comment by JustArchi** [comment]
My 5 cents, I saw mouse-scrolling commands actually implemented in **some** terminals, but it's **far** from considered standard, and personally I'd heavily vouch against it.

If we want to implement this, whether for botan or other reasons, it should be explicitly around the line of the command input and NOT any other part of the screen, including previous commands executed in the same window. So if user wants to scroll commands, he has to position his cursor exactly on the command input line.

This approach is good enough in my opinion to not annoy people with non-standard behaviour, while still allowing the planned use case. Any other behaviour, such as changing scrolling for entire window, is entirely counter-productive if not outright harmful.

**Comment by Botan626** [comment]
> My 5 cents, I saw mouse-scrolling commands actually implemented in **some** terminals, but it's **far** from considered standard, and personally I'd heavily vouch against it.
> 
> If we want to implement this, whether for botan or other reasons, it should be explicitly around the line of the command input and NOT any other part of the screen, including previous commands executed in the same window. So if user wants to scroll commands, he has to position his cursor exactly on the command input line.
> 
> This approach is good enough in my opinion to not annoy people with non-standard behaviour, while still allowing the planned use case. Any other behaviour, such as changing scrolling for entire window, is entirely counter-productive if not outright harmful.
> 
> And since the use case is so irrelevant and arrow keys already work, it's up to ASF-ui devs to decide if they want to bother with it.

Thank you, I have zero objection/argument.

**Comment by Botan626** [comment]
@Abrynos You are welcome to discussion.

**Comment by MrBurrBurr** [comment]
I share the same views as Archi and Ryzhe. I will not bother implementing this for the reasons already stated, but if anyone else wants to do it and it will be implemented as Archi stated above I would be ok with a PR.

**Comment by Botan626** [comment]
Another solution, standard in Chrome and Firefox:
![image](https://user-images.githubusercontent.com/28785698/85824566-c498b980-b788-11ea-8cab-90afed7e18b4.png)

https://i.imgur.com/e95AeAb.gif

**Comment by Abrynos** [comment]
Thanks @Botan626 

I am also opposed to the idea. Even to the solution @JustArchi . This is because I can see people trigger it on accident by scrolling and their mouse being on the input line due to scrolling and suddenly changing behaviour mid what they intended to do.

In my opinion this is some behaviour shaving half a second off every time you use it (mind: you can also just type the command instead of search for it with 50 scrolls ;) ). I myself use a vim-plugin in my browser and even navigate and click on buttons using my keyboard. I assure you that if you are used to typing fast, which in recent history most people who regularly use a PC are, you are as fast if not faster just typing `loot^ r!1\d{3} 12345 123` instead of searching for the last time you used it. 

If either is too much work I suggest a custom plugin that allows you to configure command aliases. Which, now that I think of it, I might code.

**Comment by Ryzhehvost** [comment]
> Another solution, standard in Chrome and Firefox: left mouse click on the line with flashing cursor opens list of recently used stuff.

This one sounds better for me. At least it's some behavior that people may have seen elsewhere, so it's not so confusing. Of course this popup should be easily closed with click outside of it and with Esc key.

**Comment by MrBurrBurr** [comment]
Feel free to send a PR, otherwise I think the current solution where you just use the arrow keys on your keyboard is good enough.

**Comment by Botan626** [comment]
> send a PR

I will.
