### ISSUE TITLE
Add info about shortcuts in Readme on GitHub

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1019]
Can be hard to remember them, harder to find info about them, newcomers might not know about them at all.

I managed to find info about shortcuts here:
https://github.com/JustArchiNET/ASF-ui/issues/517
https://github.com/JustArchiNET/ASF-ui/pull/466

**Comment by MrBurrBurr** [comment]
If we start documenting "hidden" features we should do them all at once.

- Filtering bots via sidebar tiles
- Send command "button" in Terminal
- Terminal shortcuts

Maybe we should add a little wiki describing those features and also add FAQ. I feel like writing all this info in README would bloat it a bit and make it confusing.
