### ISSUE TITLE
Change Restart and Exit icons

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1027]
Current restart and exit icons are misleading and uncommon.

Current version:
![](https://i.imgur.com/OqiMZrS.png)

Example of icons with clear purpose:
![](https://i.imgur.com/c4Ox9ru.png)

Restart icon: https://fontawesome.com/icons/redo-alt?style=solid
Exit icon: https://fontawesome.com/icons/power-off?style=solid

**Comment by MrBurrBurr** [comment]
Thank you, closed in https://github.com/JustArchiNET/ASF-ui/commit/75f9e8b7097eb6cb3bd87e9849c50e2bce23b18f

**Comment by Botan626** [comment]
You could also change icon for Wiki to this one: https://fontawesome.com/icons/book-open?style=solid

Looks like Wiki icon on GitHub.
![image](https://user-images.githubusercontent.com/28785698/86486981-8f323400-bd65-11ea-956d-df8c5eab346f.png)

**Comment by MrBurrBurr** [comment]
> You could also change icon for Wiki to this one: https://fontawesome.com/icons/book-open?style=solid

Please open new issue for that, or I will do it when I have time.
