### ISSUE TITLE
Refresh Log after restart or update

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1029]
Currently user needs to reload Log page in order to refresh log.
![image](https://user-images.githubusercontent.com/28785698/86489504-336ba900-bd6d-11ea-83bd-11c99800548d.png)

**Comment by Botan626** [comment]
[92c7fb2](https://github.com/JustArchiNET/ASF-ui/commit/92c7fb2b9b1ef6bb6f83bd757b653af9c1b1cc7f) doesn/t work

![image](https://user-images.githubusercontent.com/28785698/89420843-f3b52a00-d73b-11ea-9449-68545542eb3b.png)

plus ui can't be reached after I pressed update and restart buttons several times on ui page without page reloading
![image](https://user-images.githubusercontent.com/28785698/89421760-1bf15880-d73d-11ea-9886-d1933fe15f8b.png)

**Comment by Botan626** [comment]
and interactive console didn't work at this time as well

**Comment by Botan626** [comment]
![image](https://user-images.githubusercontent.com/28785698/89422354-e305b380-d73d-11ea-9a6c-60c6e67d1f38.png)

**Comment by Botan626** [comment]
1 check update on a not-reloaded ui page after restart, and interactive console won't work
![image](https://user-images.githubusercontent.com/28785698/89422638-45f74a80-d73e-11ea-8282-a2cdfea3917e.png)

**Comment by Botan626** [comment]
but interactive console is working if I restart ASF with UI and then check for updates with interactive console
![image](https://user-images.githubusercontent.com/28785698/89423706-85726680-d73f-11ea-919d-06c3f6b4d85b.png)

**Comment by MrBurrBurr** [comment]
I can't understand what you are trying to do, neither do I understand what you are trying to report.
Too little text, too many screenshots.

As for now I still believe that the issue you are encountering has nothing to do with ASF-ui.

**Comment by Botan626** [comment]
1. Open ui log page,

2. Press restart button in ui,

3. ASF restarts (ui confirms it with message)
![image](https://user-images.githubusercontent.com/28785698/89430084-08e38600-d747-11ea-9bb8-3700a8f2d143.png),

4. Log doesn't refresh on ui log page after successful restart, compare last messages in ui log page and ASF terminal.
![image](https://user-images.githubusercontent.com/28785698/89430430-6aa3f000-d747-11ea-80e7-ac3a1615352f.png).

**Comment by Botan626** [comment]
I just noticed, after I installed publicly released v4.2.3.7 yesterday, that ui browser page will reload itself after restart performed with restart button in ui. So your solution actually works. Sorry for misleading.

But if I restart ASF with restart command in interactive console, ui page won't reload.

**Comment by Abrynos** [comment]
@Botan626  can you test if you get the same result when you restart via steam chat?

**Comment by Botan626** [comment]
When I restart via Steam chart, ui page won't reload.

**Comment by MrBurrBurr** [comment]
ASF-ui does not handle 504 status codes currently. It doesn't know that ASF was restarted outside of ASF-ui. It just receives 504 status code and does nothing currently. So maybe we should add some kind of "Waiting for connection" status loader. I actually suggested it myself in #1039 but then trashed the idea again.

**Comment by Abrynos** [comment]
@MrBurrBurr keep in mind that 504 will only be returned if ASF is behind a reverse proxy 😉

**Comment by Botan626** [comment]
> So maybe we should add some kind of "Waiting for connection" status loader.

and what will be further actions? manual ui page reload?

**Comment by Botan626** [comment]
Also ui page does not reload after update via ui.
![image](https://user-images.githubusercontent.com/28785698/89792020-b16d5d80-db2c-11ea-94e4-de547a59fb17.png)
