### ISSUE TITLE
ASF-ui shows outdated changelog

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1033]
ASF-ui Releases page:
![image](https://user-images.githubusercontent.com/28785698/86533310-fc1a0b00-bed8-11ea-9cc6-4d434cf9bccd.png)

GitHub Releases page at the same time:
![image](https://user-images.githubusercontent.com/28785698/86533327-16ec7f80-bed9-11ea-9224-5551c0997f81.png)

CTRL+F5 doesn't help.

**Comment by MrBurrBurr** [comment]
This was not a bug btw since the original changelog was cached. So this issue is more of a feature request.

**Comment by Botan626** [comment]
I pressed ctrl+f5 several times, but asf-ui doesn't show updated changelog.
![image](https://user-images.githubusercontent.com/28785698/92034791-697dd700-ed76-11ea-9e20-796c1ccf1f92.png)
![image](https://user-images.githubusercontent.com/28785698/92034814-71d61200-ed76-11ea-8aa0-a3aa797b8521.png)

**Comment by MrBurrBurr** [comment]
I think I know why. I will take a look and fix it later today. Thanks for reporting.

**Comment by MrBurrBurr** [comment]
Could you please show me the content of your localStorage? Like this please:
![image](https://user-images.githubusercontent.com/31552675/92136363-39811300-ee0c-11ea-82aa-aa7f4bdd090b.png)

**Comment by Botan626** [comment]
ASF-ui already updated changelog, but still:
![image](https://user-images.githubusercontent.com/28785698/92148156-d18af680-ee24-11ea-8d81-afc5084c9146.png)

By content you mean info in the box? https://pastebin.com/raw/dVvspZGZ

**Comment by MrBurrBurr** [comment]
Did you clear your localStorage or why does it now show the correct changelog?

If it happens again please copy the [`Value` part](https://user-images.githubusercontent.com/31552675/92150818-5293bf00-ee20-11ea-849e-4e425bf0e457.png) from the localStorage. You can click into the field and the whole content will be auto-selected, so you just need to copy it.

**Comment by Botan626** [comment]
I never cleared localStorage, only cache.

> If it happens again please copy the [`Value` part](https://user-images.githubusercontent.com/31552675/92150818-5293bf00-ee20-11ea-849e-4e425bf0e457.png) from the localStorage.

Will do it next time.

**Comment by Botan626** [comment]
![image](https://user-images.githubusercontent.com/28785698/99301885-adee1e80-285f-11eb-9192-5427aa5ef473.png)

![image](https://user-images.githubusercontent.com/28785698/99301832-96169a80-285f-11eb-8276-95aa3229924e.png)

asf-ui:cache:releases: https://pastebin.com/raw/vDKcAGPU

**Comment by Botan626** [comment]
Even after update ASF-ui doesn't update changelog:
![image](https://user-images.githubusercontent.com/28785698/99302914-21446000-2861-11eb-81bc-3202675def04.png)
asf-ui:cache:releases: https://pastebin.com/raw/e8zH0Kxu

**Comment by Botan626** [comment]
I also saw this message:
![image](https://user-images.githubusercontent.com/28785698/99307135-26a4a900-2867-11eb-8e22-c571f9ab129a.png)
But after I pressed CTRL+F5 several times it was gone, yet ASF-ui still didn't update changelog:
![image](https://user-images.githubusercontent.com/28785698/99307258-489e2b80-2867-11eb-9895-a9cf333894ad.png)

**Comment by MrBurrBurr** [comment]
This time it's not ASF-ui's fault.

![image](https://user-images.githubusercontent.com/31552675/99408221-446a2080-28f0-11eb-8eb9-be99823f770c.png)
