### ISSUE TITLE
Change Restart icon

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1045]
Will be same as here:
![image](https://user-images.githubusercontent.com/28785698/87699245-42a31b80-c79d-11ea-895e-2fa6e7e4cf04.png)

https://fontawesome.com/icons/undo-alt?style=solid

Sorry I didn't find it in the beginning!

**Comment by MrBurrBurr** [comment]
I don't think the direction is important or that it makes a difference. On other systems you got the restart icon going clockwise.

**Comment by Botan626** [comment]
Maybe, but counterclockwise arrow represents return to inception action more strictly.
