### ISSUE TITLE
Show wallet info on bot modal

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#1046]
Would be nice to have some information about the wallet balance and currency for each bot.

**Comment by MrBurrBurr** [comment]
@JustArchi Can we get `s_WalletBalance` in /Api/Bot/{botNames}?

**Comment by JustArchi** [comment]
@MrBurrBurr what for? Max safe integer in js is `9007199254740991`, and considering the value is given in cents, do you expect from people to have over `90 071 992 547 409,91` of their local currency?

**Comment by MrBurrBurr** [comment]
Ok, I guess nobody will have more than that :D

**Comment by JustArchi** [comment]
I don't know what is the least worth currency, but `90 071 992 547 409,91` of RUB is worth approx `1 252 901 416 334,47` USD, I'd say find the user having that much first before considering precision loss in js.
