### ISSUE TITLE
UI crashes/stops to respond

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1048]
I don't know how to reproduce it, but this happened several times before with previous ASF builds.
There are no warnings/errors in ASF log, but ui crashes/stops to respond. Previously restarting ASF solved the problem.
I will not restart ASF for now.

![image](https://user-images.githubusercontent.com/28785698/88037904-2c56e000-cb4e-11ea-965c-734efe571ad4.png)

https://i.imgur.com/kJLVFWK.gif

ASF log: https://pastebin.com/raw/cxubW7Uk

**Comment by Botan626** [comment]
Reloading ui page leads to this:
![image](https://user-images.githubusercontent.com/28785698/88038727-4c3ad380-cb4f-11ea-8253-9219532ae1ca.png)

**Comment by MrBurrBurr** [comment]
This looks more like an error on your end. Try reinstalling latest stable ASF and clear your cache. Then report back please.

**Comment by Botan626** [comment]
I did what you said, it returned ui back to normal, I will report here if this will happen again.

**Comment by MrBurrBurr** [comment]
Ok, then I will close this issue for now.

**Comment by Botan626** [comment]
There it is again:
![image](https://user-images.githubusercontent.com/28785698/89151659-1db6f280-d56a-11ea-8c88-54f85674b895.png)

ASF did re-connect when I came back home yesterday evening, ui did work (I checked for new version), when I woke up this morning it doesn't respond.

ASF log; https://pastebin.com/raw/AFMTyH81
