### ISSUE TITLE
Enter Access code directly in ASF-UI

### ISSUE THREAD

**Issue by Kotoki1337** [JustArchiNET/ASF-ui#1057]
# Feature request

first of all, my english is poor, so i briefly looked at the current issue/pr, i may have missed the issue/pr/wiki related to this feature. but i still post an issue. if there is any way or is already in WIP, please let me know...

Then let us start

## Purpose

i use ASF-UI because i dont want to touch the command line. ASF-UI is all good and solved all my requirements. but when i create a new BOT, ASF needs to log in to that account and enter the account access code. i found that there is no place in the UI for me to enter this code. of course, if there is, i may have overlooked it, just like the beginning of the issue, please let me know, and then sorry for this issue.

## Solution

i dont understand C# so i dont know how to implement it :(. just let the UI react something when ASF requests the access code.

## Alternatives

if we cant, maybe can let the UI command line input code when ASF needs code.

## Additional information

i know that ASF can handle login requests when ASF has 2FA files. but many times people only bind emails or use their mobile phones as 2FA.

**Comment by MrBurrBurr** [comment]
This feature request is already being tracked in issue #888 

As for now I would recommend following the [wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker#pro-tips) and use the `input` command until this feature is implemented.

**Comment by Kotoki1337** [comment]
i got it. thx for notice

**Comment by Kotoki1337** [comment]
> This feature request is already being tracked in issue #888
> 
> As for now I would recommend following the [wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Docker#pro-tips) and use the `input` command until this feature is implemented.

i got it. thx for notice
