### ISSUE TITLE
Improve notifications for Update

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#106]
If ASF is up to date, it should say so, instead of displaying Error message, I guess.

https://i.imgur.com/s7bvYq7.png

**Comment by Aareksio** [comment]
That's ASF response. We do not know what exactly failed.

**Comment by Abrynos** [comment]
Maybe you want to display the message you receive from ASF instead of "Failed!"... Would be my idea on how to go about this

**Comment by Aareksio** [comment]
@Abrynos 
![This *IS* the response](https://yko.im/i03v.png)

It's exactly what it does. :doubt:

**Comment by Abrynos** [comment]
i'm talking about the MESSAGE in the generic response

**Comment by Aareksio** [comment]
That's precisely what we do ([source](https://github.com/JustArchiNET/ASF-ui/blob/master/src/components/NavigationBrand.vue#L57)). In English translation the message is `Failed!`, exactly as on included screen.

**Comment by Botan626** [comment]
Failed is no good.

Why Failed, if ASF is up to date?

**Comment by Abrynos** [comment]
set your update channel, botan!

**Comment by Botan626** [comment]
UpdateChannel is set to 2.

Still, why Error message and Failed, if ASF is up to date: https://i.imgur.com/s7bvYq7.png   ?

Maybe this issue should be reported in ASF itself, if ASF UI just transmits ASF responses?

**Comment by Botan626** [comment]
https://i.imgur.com/3jq6IO4.png

Local version = remote version, so no update process did run, and that's the reason for the Error message, I guess?

**Comment by Botan626** [comment]
@Aareksio 

I noticed you added **ASF Issue** label, but ASF itself shows no errors when updating, look:
https://i.imgur.com/TZmRzjf.png

It's ASF UI which gets Error response from somewhere else.

**Comment by Botan626** [comment]
@Aareksio 

Archi's response: https://github.com/JustArchiNET/ArchiSteamFarm/issues/940#issuecomment-436602296

ASF API errors are out of my filed of knowledge.

**Comment by Aareksio** [comment]
@Botan626 Archi simply said you didn't provide enough details :wink:

**Comment by Botan626** [comment]
@Aareksio 

Tbh, I don't want to get my head around ASF API. As an ordinary user, I pressed **Update** button in **ASF-ui** and the popped out **Error** message with the **Failed** description was surprising, since ASF still successfully checked for new version.

https://i.imgur.com/R1ERu2F.png

I think (I may be wrong) enough info was provided by me describing this case, so now it's up to you, Archi, or somebody else to decide what to do about this.

**Comment by Botan626** [comment]
@MrBurrBurr 

https://i.imgur.com/JMEmRBK.png

**Comment by Aareksio** [comment]
That's ASF update, returned message is now a bit more descriptive.

**Comment by Botan626** [comment]
@Aareksio 

Same Error.

https://i.imgur.com/Q6vFtVH.png

**Comment by Aareksio** [comment]
@Botan626 This is the error message we get from ASF

**Comment by Botan626** [comment]
@Aareksio Ok. Will somebody fix it? It's like everybody knows about it, but don't wanna do anything about it.

**Comment by Aareksio** [comment]
Go complain to Archi, not here :wink:

**Comment by Botan626** [comment]
But he already knows.

**Comment by Botan626** [comment]
@Aareksio 

Still the same.

https://i.imgur.com/9QexNW5.png

**Comment by Aareksio** [comment]
> Go complain to Archi, not here 😉

**Comment by Botan626** [comment]
@JustArchi Need for fix.

**Comment by Botan626** [comment]
@MrBurrBurr 

Why nobody improves this?

http://oi67.tinypic.com/175xqc.jpg

**Comment by Abrynos** [comment]
Either you stop complaining or you send a PR and also stop complaining. My guess is if you continue like this either will this issue be locked or you will be blocked to do anything on this repo (or both).
