### ISSUE TITLE
Move from POST (...)/Confirmations/(Accept|Cancel) to POST (...)/Confirmations IPC API endpoint

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#1075]
Accept/Cancel endpoints are deprecated and will be removed starting from next ASF development cycle, which will realistically hit stable in approx 1-2 months from now. ASF will keep backwards compatibility until then, giving everybody (including ASF-ui) at least full month to adapt.

If ASF-ui gives user option to accept/decline confirmations with this API endpoint, this needs to be addressed. Otherwise, the issue can be safely closed.

The change is trivial. Refer to ASF changelog starting from V4.2.3.8+ and swagger docs for more details. The most basic usage is `POST (...)/Confirmations` with `{"accept": true}` or `{"accept": false}`. No UI changes are required, only logic related to calling the appropriate endpoint.

Wishlist: new API endpoint gives more options, such as accepting confirmations of a specific type or even specific trade/market ID, refer to the docs for more info. This however is a low-priority wishlist after the required changes mentioned above, extra properties mentioned here are optional to use, only `Accept` is required.

![image](https://user-images.githubusercontent.com/1069029/89785018-ff2c9a80-db19-11ea-81c5-63685b1f0ad0.png)

**Comment by JustArchi** [comment]
The original issue was addressed in #1076, the remaining part is lower-priority wishlist.

(Feel free to edit the original issue or create a new one if you wish @MrBurrBurr)

**Comment by JustArchi** [comment]
Of course you can also decide that the potential wishlist idea is bad and not decide to do anything with it, I'm just reporting about new possibilities 🙂

**Comment by MrBurrBurr** [comment]
Thank you for reporting it. The API provides some cool new things that we should handle in the UI so I will open a new issue for your wishlist.
