### ISSUE TITLE
ASF-ui can't be reached

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1079]
I opened ui several times before it got lost, then all of a sudden ui page can't be found.

![image](https://user-images.githubusercontent.com/28785698/90338361-d876d400-dff1-11ea-8c6b-fa14c6b862a2.png)

**Comment by Botan626** [comment]
ASF log: https://pastebin.com/raw/6mjpb98H

**Comment by Botan626** [comment]
Should I restart ASF now?

**Comment by Botan626** [comment]
![image](https://user-images.githubusercontent.com/28785698/91230573-724a2980-e734-11ea-9b13-59a0bde56a60.png)

**Comment by MrBurrBurr** [comment]
This is not an ASF-ui issue.

**Comment by Abrynos** [comment]
I just saw, that his browser tries to access path `/:1` on the server (as you can see in his browser console). Is it possible that this is due to a bug in frontend router code redirecting improperly?

**Comment by Botan626** [comment]
This happened again, and as @Abrynos suggested me, I'm willing to give more information on the matter.

## Description
I tried to open ASF-ui with my bookmarked link http://127.0.0.1:1242/ in Chrome.
It gave me HTTP ERROR 404 with 'Failed to load resource: the server responded with a status of 404 (Not Found)' message while trying to load 127.0.0.1/:1 address for whatever reason.
![image](https://user-images.githubusercontent.com/28785698/91750013-0a2f9380-ebcb-11ea-8e96-8bb500ac7d38.png)

## Steps to reproduce
I don't know how to reproduce this issue. The only major event which happened before ui got lost was changing network connection type form Wi-Fi to 4G USB modem, which led to ASF disconnection from Steam at 2020-08-31 00:05:25 (see attached ASF log).

## Screenshots
I installed new browser Opera to check if this isuue is browser dependent, but the result is the same.
![image](https://user-images.githubusercontent.com/28785698/91750999-b625ae80-ebcc-11ea-9cdb-c8e114646d81.png)

UI confuguration:
![image](https://user-images.githubusercontent.com/28785698/91751088-dce3e500-ebcc-11ea-995c-a84feaf65290.png)

## Additional information

ASF log: https://pastebin.com/raw/u1DXnWjy
ASF json: https://pastebin.com/raw/QWnJCmqb

**Comment by MrBurrBurr** [comment]
To be honest I have no idea what could be wrong. I don't know where to start looking or how to reproduce. I am lost with this issue.

The only thing I could think of would be that the kestrel webserver has some issue with you switching networks.

@Abrynos suggested that you could try to disable/remove all plugins and see if it still happens. He will also try to find some time tomorrow so that he can test some stuff with kestrel and see if it fixes it.

Otherwise I would like to hear @Aareksio or @JustArchi about their opinion. Maybe they can give some hints on where to look at.

**Comment by Botan626** [comment]
## Steps to reproduce

This happens after I run custom clean in CCleaner.

**Comment by Abrynos** [comment]
Then it's neither ASF nor ASF-ui issue but CCleaner issue

**Comment by Botan626** [comment]
> Then it's neither ASF nor ASF-ui issue but CCleaner issue

CCleaner removes too much stuff? How come ASF itself keeps on working, but ASF-ui gets lost?

**Comment by Botan626** [comment]
What CCleaner could remove that ASF-ui becomes unreachable?

**Comment by JustArchi** [comment]
`%TEMP%` folder, as stated in **[ASF's FAQ](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/FAQ#systemiofilenotfoundexception-could-not-load-file-or-assembly)**.

Not ASF-ui issue, neither ASF issue. As a side note, it'll be fixed "by the way" when ASF upgrades to .NET 5.0.

**Comment by Botan626** [comment]
I added `%TEMP%\.net` folder to excluded folders in CCleaner, ASF-ui gets lost no more.

Thanks everybody who took part in resolving this issue :smiley:

**Comment by MrBurrBurr** [comment]
As you can see @Botan626, as soon as you provided a way to reproduce your problem it got solved.

I just wanted to use this issue as an example as to why it is so important to provide good and complete information.
