### ISSUE TITLE
Add 'redeem' to bot action buttons

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#112]
Related info: #111 

`/Api/Bot/{botName}/Redeem` should be used.

**Comment by MrBurrBurr** [comment]
@Aareksio Should there be a separate button for redeem or should we incorporate it into BGR? Like add detection for single key pattern?

**Comment by Aareksio** [comment]
We could probably combine both, good catch.

**Comment by Aareksio** [comment]
BGR window now supports keys without labels:
```
AAAAA-BBBBB-CCCCC
```

We can consider using `redeem` for single keys, but I'm not exactly sure why would we want to do so.

**Comment by MrBurrBurr** [comment]
We should use `redeem` since we get `Result` and `PurchaseResultDetail` in response and can use it to display outcome nicely for user.

**Comment by MrBurrBurr** [comment]
Related: #184
