### ISSUE TITLE
Remove 3rd-party network request to fonts.googleapis.com

### ISSUE THREAD

**Issue by PaulEwe** [JustArchiNET/ASF-ui#1121]
## Purpose
When visiting the UI, there are two 3rd-party resources/requests.
First, there is a request to `https://steamcdn-a.akamaihd.net/steamcommunity/public/images/avatars/*_full.jpg` because of profile pictures.
But there is also a request to `https://fonts.googleapis.com/css?family=Source Sans Pro:300,400,600` to get the Source Sans Pro font.
I don't see why this font shouldn't be provided by ASF as 1st-party. It's an unnecessary network request to Google and it's even worse that the UI is most likely only accessible within the home network which means the browser shouldn't need to have an internet connection to visit the UI with a font.

## Solution
I saw other projects on GitHub are using [google-webfonts-helper.herokuapp.com](https://google-webfonts-helper.herokuapp.com/fonts/source-sans-pro) with Modern Browsers option. It only takes three lines of CSS and downloading the fonts.

## Alternatives
None.

## Additional information
I know there are addons like uBlock Origin to block these requests. However, it would still be a privacy benefit for everyone without these addons when visiting the UI.
https://github.com/JustArchiNET/ASF-ui/blob/0cf8f0e44a0d54e5484ef91acb64adb5dc93ab1d/src/static/index.html#L10

**Comment by JustArchi** [comment]
I don't believe the call to steamcdn is wrong, at worst it could be simply non-mandatory with default profile picture with question mark being loaded from within ASF-ui in case online resolve fails for any reason. I'm not sure if it doesn't work like that today, maybe it does, otherwise it's probably a good idea @MrBurrBurr.

Second thing is up to devs, I don't know better to tell whether it makes sense to be bundled or not.

**Comment by MrBurrBurr** [comment]
> I don't see why this font shouldn't be provided by ASF as 1st-party.

The reason behind using googles api for the font was bundeling size. Also it was assumed that most users already got this font saved in cache from visiting other sites that use this font. I personally don't mind using googles api but I can see that some users may be concerned and bundeling size isn't that big of a deal anyways.

>... the UI is most likely only accessible within the home network which means the browser shouldn't need to have an internet connection to visit the UI with a font.

You can use the UI without an internet connection, it will just use Helvetica or Arial as a backup font.

That being said I think its a good idea to provide a default picture ourself and not rely on steamcdn.
