### ISSUE TITLE
ASF-ui ignores environment when checking for updates

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#1135]
## Description

ASF-ui should not point out availability of the newer version if running in non-supported (for updates) environment.

There are currently two situations which disable the auto-updates functionality:
- Running with `UpdateChannel` of `0` (`None`), which explicitly tells ASF that there is no channel to update to (and therefore you can't make any assumptions about versioning and whether something is newer or older). The whole logic should be disabled.
- Running ASF compiled with `!CanUpdate` setting, which is the case for generic docker builds and custom source builds. I've just added a way to fetch that in **[fe0df93](https://github.com/JustArchiNET/ArchiSteamFarm/commit/fe0df93176c58c958424035f0a15a5534fb8e103)**. If there is `UpdateChannel` set (different than `0`), it makes sense to check for version and notify user, but the auto-update functionality is unavailable, therefore perhaps it shouldn't be an exclamation mark, but rather something more neutral, as user might or might not be able to update on his own (e.g. because he's running a custom ASF version). It's also fine to ignore the whole logic and act the same as above.

## Steps to reproduce

Run outdated ASF version in non-supported (for updates) environment.

## Expected behavior

ASF-ui should not check for newer version available, and if it's done as part of some other functionality, should refrain from notifying user about new version - with `UpdateChannel` of `0`. With channel set but running ASF which doesn't have auto-update functionality, perhaps changing the symbol would work, I don't know which one makes sense, maybe a question mark? We don't know after all if update makes sense (docker) or doesn't at all (custom build).

In second case, ASF completely disables the functionality just like in the first case. If you deem it as appropriate, ASF-ui can also just remove the logic in both cases, but perhaps it makes sense to still do it as a measure to let users know - up to you. If some user doesn't want to have anything to do with the updates, he should be using `UpdateChannel` of `0`, regardless of whether his ASF can or can't auto-update, this is also why in this case ASF-ui may or may not notify user about the update, because there is a channel based on which we can make this assumption. ASF doesn't, because it's auto-updates routine and we can't do anything with newer version anyway.

## Current behavior

ASF-ui notifies user about newer version regardless of his environment.

## Screenshots

![image](https://user-images.githubusercontent.com/1069029/96376576-22aa3c00-1180-11eb-9074-94db603e4105.png)

`source` is one of the variants that has `CanUpdate = false`.

**Comment by Botan626** [comment]
> There are currently two situations which disable the auto-updates functionality

`UpdatePeriod` of 0 also disables auto updates.

> ASF-ui should not check for newer version available, and if it's done as part of some other functionality, should refrain from notifying user about new version - with `UpdateChannel` of `0`.

Do I understand you right, that you saying that **now** ASF-ui checks for newer ASF version and notifies user about new release, and that this behaviour is ought to be changed?

> With channel set but running ASF which doesn't have auto-update functionality, perhaps changing the symbol would work, I don't know which one makes sense, maybe a question mark?

I have `UpdatePeriod` of 0 and `UpdateChannel` of 2, if there is newer ASF version, ASF-ui gives me new release notification and puts exclamation mark in the footer.

Why changing the symbol? It just notifies about newer release available.

**Comment by JustArchi** [comment]
> UpdatePeriod of 0 also disables auto updates.

Which is irrelevant because we're talking about **channel** to update to, not the auto-updates functionality. ASF-ui doesn't need to bother with UpdatePeriod and actually shouldn't.

> Do I understand you right, that you saying that now ASF-ui checks for newer ASF version and notifies user about new release, and that this behaviour is ought to be changed?

With `UpdateChannel` of `0` - yes.

> I have UpdatePeriod of 0 and UpdateChannel of 2, if there is newer ASF version, ASF-ui gives me new release notification and puts exclamation mark in the footer.

> Why changing the symbol? It just notifies about newer release available.

If you're posting feedback then read carefully first. UpdatePeriod has **NOTHING** to do with this issue, and your setup is capable of update notifications and is not modified by this issue **at all**.

**Comment by Botan626** [comment]
> Which is irrelevant because we're talking about **channel** to update to, not the auto-updates functionality. ASF-ui doesn't need to bother with UpdatePeriod and actually shouldn't.

Ok, then, just to be clear on this matter, exclamation mark is ok if `UpdatePeriod ` is set to 0?

**Comment by JustArchi** [comment]
Yes, because as I said already, `UpdatePeriod` has **NOTHING** to do with this issue.

**Comment by Botan626** [comment]
> With `UpdateChannel` of `0` - yes.

I installed clean ASF v5.0.0.5, `UpdateChannel` is set to 0, new release notification is on in ASF-ui.

ASF-ui does not check for newer ASF version and doesn't show new release notification, there is no even an Update button.

![image](https://user-images.githubusercontent.com/28785698/103345165-af874500-4aa1-11eb-9079-8793a6962ae1.png)

**Comment by JustArchi** [comment]
Good, because this is how it's supposed to work.

@MrBurrBurr you should probably also clear/hide the existing notification if it's saved somewhere.

**Comment by MrBurrBurr** [comment]
It's not saved anywhere, so no worries - no changes needed in that regard.
