### ISSUE TITLE
Rename buttons in 2FA window

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1140]
![image](https://user-images.githubusercontent.com/28785698/96936696-37b00380-14cf-11eb-87d3-805ad672ae50.png)

Besides trade confirmations, there are also market confirmations [Trade and Market Confirmations](https://support.steampowered.com/kb_article.php?ref=1284-WTKB-4729).

Also 2faok and 2fano [commands](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#commands-1) accept or deny all pending **confirmations**.

## Solution
Rename 'Accept all trades' to 'Accept all confirmations' and 'Cancel all trades' to 'Reject all confirmations'.

**Comment by MrBurrBurr** [comment]
I used what Steam was using in their iOS app. I wonder if they are still using the same text.

**Comment by Botan626** [comment]
![image](https://user-images.githubusercontent.com/28785698/97048130-9aaea280-1582-11eb-8542-e01506e61d76.png)
