### ISSUE TITLE
Reload ASF-ui page after ASF update

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1142]
## Description
After successful ASF update ASF-ui page in browser does not auto reload. Probably hard reload is needed (CTRL+F5).

## Steps to reproduce
1. Open ASF-ui page in browser,
2. Make sure there is ASF update available,
3. Update ASF either way (interactive console, chat, ASF-ui),
4. ASF updated and restarted itself as well as started new IPC server (see on attached screenshot local version is 4.3.1.1), but ASF-ui page was not reloaded (see bottom right corner on attached screenshot).

## Purpose

Reload ASF-ui page in browser to update web interface after successful ASF update and subsequent ASF restart, which implies that IPC server was also restarted.

## Screenshots
![chrome_9hwWoPaNb8](https://user-images.githubusercontent.com/28785698/96938658-9c6d5d00-14d3-11eb-8bfa-a6996b9d3432.png)

**Comment by Botan626** [comment]
Requires more info label - what info?

**Comment by MrBurrBurr** [comment]
Please fill out the issue template, just like you did [here.](https://github.com/JustArchiNET/ASF-ui/issues/1079#issuecomment-683937138)

**Comment by Botan626** [comment]
> Please fill out the issue template, just like you did [here.](https://github.com/JustArchiNET/ASF-ui/issues/1079#issuecomment-683937138)

Done, anything else I need/can add?
