### ISSUE TITLE
Complete typing in commands and arguments with right arrow key press

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1146]
## Purpose

ASF-ui can show the remaining part of typing in commands and valid arguments in the background.
![image](https://user-images.githubusercontent.com/28785698/97084399-676e2100-161f-11eb-83d1-3c59c1f668ba.png)
![image](https://user-images.githubusercontent.com/28785698/97084407-72c14c80-161f-11eb-8a4f-57f9e134d3be.png)

This feature will help users to type in commands faster.

**Comment by JustArchi** [comment]
> right arrow key press

Sane people use tab for that, and it already works this way.

**Comment by Botan626** [comment]
Truly didn't know about that, @MrBurrBurr please describe it in the [Hidden features](https://github.com/JustArchiNET/ASF-ui/blob/master/.github/FEATURES.md).

**Comment by Botan626** [comment]
> Truly didn't know about that, @MrBurrBurr please describe it in the [Hidden features](https://github.com/JustArchiNET/ASF-ui/blob/master/.github/FEATURES.md).

#1147

**Comment by Botan626** [comment]
> @MrBurrBurr please describe it in the [Hidden features](https://github.com/JustArchiNET/ASF-ui/blob/master/.github/FEATURES.md).

#1147
