### ISSUE TITLE
CTRL + L shortcut does not clear the whole terminal

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1151]
## Description
CTRL+L shortcut does not clear everything on the Commands page when executed.

## Steps to reproduce
1. Open Commands page in ASF-ui,
2. Type something in the terminal,
3. Press CTRL+L,
4. The stuff that you typed in stays.

## Expected behavior
Clear the whole terminal, or bring it to this state:
![image](https://user-images.githubusercontent.com/28785698/97120542-ccfa0480-1728-11eb-91a1-d4d0ed79c737.png)

## Current behavior
Doesn't clear the input.

**Comment by Abrynos** [comment]
This behaviour is modeled after the behaviour of bash, which does also not clear the input line (to be specific: it does clear the input line, but it also rewrites it for you to continue typing). I will use the same link you sent me in a private chat earlier as a reference here:
http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#Readline-Movement-Commands

> Clear the screen, reprinting the current line at the top

**Comment by Abrynos** [comment]
I think the behaviour is fine, but the documentation of it should maybe be adapted.

**Comment by MrBurrBurr** [comment]
If most of our user-base expects the input to be cleared as well we should implement it.

Not the question is what does most of ASF-ui user-base expect?

**Comment by Abrynos** [comment]
I can only speak for myself. I like to use this and I'm used to bash.

Old feature request for reference: #517

**Comment by Botan626** [comment]
I guess if initial intentions were to make it work like in bash, and both of you want to keep it, then we should change description only.

**Comment by Abrynos** [comment]
As I said: I can only speak for myself. Maybe wait for a day or two, whether any other users want to give us their opinion?

**Comment by MrBurrBurr** [comment]
I will keep this open for a bit and wait and see if someone else wants to express their opinion. If nobody will join the discussion we will change the description and not change behavior.

**Comment by Botan626** [comment]
> If nobody will join the discussion we will change the description and not change behavior.

In this case you could add [kill-whole-line](http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#index-kill_002dwhole_002dline-_0028_0029) shortcut (need to think of keys combination for it), or [unix-line-discard](http://www.gnu.org/savannah-checkouts/gnu/bash/manual/bash.html#index-unix_002dline_002ddiscard-_0028C_002du_0029) shortcut `CTRL+U` (it's too far to reach for it imo).

**Comment by Botan626** [comment]
There is no a shortcut that actually clears or resets the whole terminal?
