### ISSUE TITLE
Rate Limited when Changing ASF IPC password

### ISSUE THREAD

**Issue by jondycz** [JustArchiNET/ASF-ui#1157]
## Description
When changing a password in ASF UI for the IPC login, you become rate limited

## Steps to reproduce

1. Go to 'Global Configuration'
2. Change password
3. Reload the page
4. You are rate limited

## Expected behavior
ASF UI should stop sending AJAX requests to the server and then reload the webpage showing a login screen.

## Current behavior
ASF UI keeps sending AJAX requests to the server in order to receive log data, status data, but since the password has changed, we are no longer logged in. On page reload, we get rate limited because the website kept on sending requests every second or so.

**Comment by MrBurrBurr** [comment]
This bug is related to #1142 

After sending restart command to ASF, ASF-ui will wait and >should< reload the page after ASF is done restarting. This would then cause 1x 401 response (which is fine) upon which we will ask user for ipc password.
