### ISSUE TITLE
Unknown buttton in the new ASF-ui screenshots

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1164]
## Question
What is this button on the left from languages panel?
![image](https://user-images.githubusercontent.com/28785698/97542014-1c655c80-19d7-11eb-9a0c-0fb66d361459.png)

I don't have it in my ASF-ui.
![image](https://user-images.githubusercontent.com/28785698/97542083-343ce080-19d7-11eb-9dd0-c6d1d30960d8.png)

**Comment by MrBurrBurr** [comment]
It's a "Logout" button. It will only be shown if you are "logged in" aka. you have a IPC Password set.

**Comment by Botan626** [comment]
Thanks for clarification.
