### ISSUE TITLE
How to log out the person who entered the password in the ASF UI?

### ISSUE THREAD

**Issue by lzrdblzzrd** [JustArchiNET/ASF-ui#1172]
## Question
Someone entered a password in my ASF UI and remains logged in. How do I force a person to reset cookies on the site so that the site will require to enter password again? Changing the password in the config, as I noticed, does not help. It doesn't ask you to re-enter password. I just need to log out the person.

**Comment by MrBurrBurr** [comment]
You can use the logout button in the top right corner.

![image](https://user-images.githubusercontent.com/31552675/98128398-2e07a200-1eb8-11eb-8b85-1fecf7fa3df1.png)

**Comment by lzrdblzzrd** [comment]
I don't want to log out myself out on the site. I want the person who entered the password on my site http://*myIP*:1242 to be asked for the password again.
I wrote that changing your password doesn't help. The user who entered the old password remains logged in even if the new password is set. I need to force reset cookies from the person who entered the password, so that the site will require the password again.

**Comment by Abrynos** [comment]
When you change ASFs IPC password in the correct config file ASF will automatically restart (see [here](https://github.com/JustArchiNET/ArchiSteamFarm/blob/ad90f799070ea5b26c95f61d33951d12653fbb07/ArchiSteamFarm/ASF.cs#L560)). After a restart the password is updated in memory and ASF will not give out any information whatsoever to people providing the wrong (old) password (which is saved in that other persons browser). Either you changed a file in the wrong location (e.g. if you have several copies of your config and ASF is loading the one you didn't change) or you switched back to the old password before that person opened the page again.

Apart from that: ASF password is not saved in cookies but in local storage AFAIK.
