### ISSUE TITLE
404 error While using IPC mode

### ISSUE THREAD

**Issue by the-25th-Nova** [JustArchiNET/ASF-ui#1186]
## Question
404 error occured when I use IPC mode
I have tried the same cfg another computer and it was the same yet it worked normally before on other computers.

I used 
```{
    "Kestrel": {
        "Endpoints": {
            "HTTP": {
                "Url": "http://*:1242"
            }
        }
    }
}
```
for IPC.config and proxypass to it and they seems work well
But I got 404 error (however title shown) and ```/swagger``` didnt show as well
and there is no err shown in log

## Screenshots
![Screenshot_20201116015429](https://user-images.githubusercontent.com/68760718/99192620-ae7aac80-27ae-11eb-987b-c43ed8bd4ef0.png)
![Screenshot_20201116015345](https://user-images.githubusercontent.com/68760718/99192623-b0447000-27ae-11eb-8d08-f0c747529598.png)
![Screenshot_20201116015551](https://user-images.githubusercontent.com/68760718/99192650-e41f9580-27ae-11eb-9a7d-17963ed0b570.png)
![Screenshot_20201116020738](https://user-images.githubusercontent.com/68760718/99192925-9a37af00-27b0-11eb-820b-a231a0b01665.png)

## Additional information
I tried to reinstall it and that didnt work
System:Ubuntu 18.04 64bit

**Comment by the-25th-Nova** [comment]
API works perfectly i guess
![Screenshot_20201116020738](https://user-images.githubusercontent.com/68760718/99192946-b2a7c980-27b0-11eb-88ba-5e81add686ea.png)

**Comment by the-25th-Nova** [comment]
So Generally I checked the src
it seems ASF went wrong or something I dont really got it

**Comment by MrBurrBurr** [comment]
So ASF-ui works on localhost on the same machine as ASF is running?

**Comment by the-25th-Nova** [comment]
yes.they both work on my server located in HK

**Comment by MrBurrBurr** [comment]
This looks like an issue on your end then. Probably misconfigured proxy. Feel free to check out [ASF's wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#can-i-use-asfs-ipc-behind-a-reverse-proxy-such-as-apache-or-nginx) on how to do that.

**Comment by the-25th-Nova** [comment]
I tried using ip to connect and it didnt work

**Comment by the-25th-Nova** [comment]
yes that's problem ty so much

before I re-install it I tried using ip to connect but that didnt work however it works now.
