### ISSUE TITLE
ASF restarts with Error if Log Page is opened in ASF-ui

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1187]
## Description
If log page is opened in browser, ASF will restart with error no matter how restart command was executed (steam chat, interactive console, restart button in ASF-ui).

There is no error if any other page is opened in ASF-ui.
There is no error if restart command is executed in ASF-ui's terminal.

## Steps to reproduce
1. Open ASF-ui log page in browser,
2. Restart ASF any way (steam chat, interactive console, restart button in ASF-ui).

## Additional information
ASF-ui's browser page reloads only if ASF was restarted via restart button in ASF-ui (on any page).

ASF log: https://pastebin.com/raw/HHMG6tic

**Comment by MrBurrBurr** [comment]
I guess this is a bug in ASF. Feel free to open an issue there.

**Comment by Botan626** [comment]
> Feel free to open an issue there.

This [sounds familiar](https://github.com/JustArchiNET/ASF-ui/issues/106#issuecomment-436260402), but I don't want to repeat history with issue like [this](https://github.com/JustArchiNET/ArchiSteamFarm/issues/940).

I don't know whether it's ASF-ui's bug or ASF's.

@JustArchi Please take a look at this issue.

**Comment by JustArchi** [comment]
This is not a "bug", ASF properly marks this as an error that it had to abort the connection due to restart command while you had open connection through a websocket.

Not every error is actual problem, you know.

**Comment by Botan626** [comment]
> ASF properly marks this as an error

Why ASF marks this disconnection process as an error then if this is what it meant or has to do?

Plus the log says 
> An unhandled exception was thrown by the application.

and

> The connection was aborted because the server is shutting down and request processing didn't complete within the time specified by HostOptions.ShutdownTimeout.

**Comment by JustArchi** [comment]
> Why ASF marks this disconnection process as an error then if this is what it meant or has to do?

Because abnormal abortion of the request due to the process shutting down **is** an error for kestrel, and kestrel is in charge of deciding how severe that situation is, not me or you.

**Comment by Botan626** [comment]
Could you make kestrel learn to treat the shutting down process as normal if ASF was restarted or exited?

As you mentioned 'shutting down', I tried to execute exit command in interactive console while having log page opened in browser, yes, same error, and again, only with log page.

**Comment by JustArchi** [comment]
> Could you make kestrel learn to treat the shutting down process as normal if ASF was restarted or exited?

Sure, send a PR, because I classify this "problem" of yours below anything I'm willing to spend my time on.

**Comment by Botan626** [comment]
> Sure

So it is possible?

**Comment by JustArchi** [comment]
C# is turing-complete language, by definition everything is possible to code in it 🙂
