### ISSUE TITLE
ASF-ui doesn't show new release notification

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1192]
## Description
It showed exclamation mark at the bottom of the page with pop-up window (clicking on it successfully redirected to Releases page) just once, see 1-st screenshot.

ASF-ui doesn't show new release notification, not even an exclamation mark, with a subsequent page reload (including CTRL+F5), or another ASF-ui page opening, or browser restart, see 2-nd screenshot.

## Screenshots
![image](https://user-images.githubusercontent.com/28785698/99882488-ddbb6e80-2c31-11eb-8eb7-d47833d3697f.png)
![image](https://user-images.githubusercontent.com/28785698/99882710-90400100-2c33-11eb-9a59-03d43e5e53c0.png)

**Comment by Botan626** [comment]
I did clear local storage --- same behaviour.

**Comment by Botan626** [comment]
I turned on in browser VPN, exclamation mark appeared for once with no pop-up window, after I reloaded page it disappeared.

**Comment by MrBurrBurr** [comment]
Thank you for reporting this.

**Comment by Botan626** [comment]
[8f12e62](https://github.com/JustArchiNET/ASF-ui/commit/8f12e62bd34e8d62b0d244b8665e181e7416625b) doesn't help, nothing has changed.
https://i.imgur.com/KR4L5G3.gif

**Comment by MrBurrBurr** [comment]
Keep in mind there is a 1 hour cooldown for checking latest available release. Also it will just check the notification upon page reload.

For me it works as expected following your "steps to reproduce". Please delete cache and check again.

**Comment by Botan626** [comment]
> Keep in mind there is a 1 hour cooldown for checking latest available release.

I thought this is what preventing ASF-ui from re-checking for update, but not even an exclamation mark?

> Also it will just check the notification upon page reload.

It doesn't. 

> For me it works as expected following your "steps to reproduce". Please delete cache and check again.

![image](https://user-images.githubusercontent.com/28785698/100148699-2717f200-2eae-11eb-96f8-22cecf9ed28f.png)
I pressed 3-d button from top, ui didn't give new release notification, then I cleared local storage, ui showed me new release notification, then I reloaded page and ui didn't give new release notification.

https://i.imgur.com/w0fG27U.gif

**Comment by MrBurrBurr** [comment]
Good that you test so much. Try again with latest commit.

**Comment by Botan626** [comment]
It won't give pop-up window on Releases page after page reload, is it how it's meant to be? I don't remember this aspect.

Otherwise, yes, fixed.

**Comment by MrBurrBurr** [comment]
Yes this is on purpose because you should be able to see that a new version is available now thanks to the new "install this verion" badge.
