### ISSUE TITLE
no bots are showing up

### ISSUE THREAD

**Issue by iamnotadummy** [JustArchiNET/ASF-ui#1199]
running asf, asf console shows that the bots were successfully started, but on ipc, there's not a single bot instance and ipc logs is the same with asf logs
my purpose for setting it up this way is to control my ASF instance using dropbox, this way I get to have my files in 1 folder and bring it wherever I go and easy way to setup new ASF instance

Steps to reproduce
1. run asf

Expected behavior
ipc should show a bot instance

Additional information
![started](https://user-images.githubusercontent.com/68459942/100621392-954f2f80-335a-11eb-8622-bedeb6e9fcab.jpg)

current folder tree
~/asf(soft link from ~/ASF/core/ArchiSteamFarm)
~/ASF
-core
--config(soft link from ~/Dropbox/ASF folder)
--other files

~/Dropbox/ASF folder
-IPC.config
-ASF.json
-bot files(.json, .db, .bin)

**Comment by MrBurrBurr** [comment]
Please visit [http://localhost:1242/api/bot/asf](http://localhost:1242/api/bot/asf) and show me the result.

**Comment by iamnotadummy** [comment]
ip.x.x.x/api/bot/asf returns 401 unauthorized

**Comment by MrBurrBurr** [comment]
Remove "IPCPassword" from ASF.json and restart ASF. Then test again.

**Comment by iamnotadummy** [comment]
which part should I paste here

**Comment by MrBurrBurr** [comment]
Can you please upload the config for the bot that is not showing up? I would like to reproduce.

**Comment by iamnotadummy** [comment]
so, it turns out that on my IPC, I'm running it on localhost:1242 and I'm accessing it behind nginx via ip.x.x.x/asf and on my nginx server block it's on localhost:1242 too and accessing it on ip.x.x.x/asf, but ip.x.x.x:1242/asf refuses to connect even if port 1242 is open.

I ran it on ip.x.x.x:1242 on IPC and changed server block to ip.x.x.x:1242 too.
accessing ip.x.x.x:1242/asf the bots show up but on ip.x.x.x/asf, same problem occurs. Making nginx useless since I have to open port 1242

**Comment by iamnotadummy** [comment]
and further checking,
I reverted back to using a config folder instead of a soft link,
IPC is at localhost:1242
nginx is at localhost:1242

accessing ip.x.x.x:/asf, no bots showing up
ip.x.x.x:1242/asf has bots

**Comment by MrBurrBurr** [comment]
This seems to be a problem with your proxy and not a problem with ASF-ui.

**Comment by iamnotadummy** [comment]
surprisingly, it worked again
