### ISSUE TITLE
Global Settings page stuck on "loading".

### ISSUE THREAD

**Issue by Zuko** [JustArchiNET/ASF-ui#1221]
## Description
Can't access to "Global Settings" page in latest ASF version.

## Steps to reproduce
1. Open UI 
2. Click on "Global Settings"
3. Check browser console

## Expected behavior
Working "Global Settings" page.

## Current behavior
Global Settings page stuck on "loading".

Chrome console error:
```
main.bundle.js:7 TypeError: Cannot read property 'replace' of undefined
    at 8.88c66c9.chunk.js:1
    at Array.map (<anonymous>)
    at a.created (8.88c66c9.chunk.js:1)
```

Firefox console error:
```
TypeError: n[t] is undefined
    fields https://example.com/asf-main/scripts/8.88c66c9.chunk.js:1
    created https://example.com/asf-main/scripts/8.88c66c9.chunk.js:1
```

## Screenshots
![image](https://user-images.githubusercontent.com/521035/103046618-2cd62580-4589-11eb-9cb0-340181dbb1b2.png)

## Additional information
ASF 5.0.1.2 - linux-x64 - dacb4d6, tested on Chrome, Firefox with and without Nginx RevProxy.

**Comment by MrBurrBurr** [comment]
Current workaround until someone fixes it is to change language to english.
