### ISSUE TITLE
Bot config panel with fixed width

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1226]
## Purpose
Will make switching between Config bot panels more convenient when using arrow keys.
More info, clause 1: https://github.com/JustArchiNET/ASF-ui/pull/1224#issuecomment-751847078

## Screenshots

[Screenshot 1](https://user-images.githubusercontent.com/28785698/103242838-ba8a8a00-4968-11eb-8659-8784dd67655b.png)
[Screenshot 2](https://user-images.githubusercontent.com/28785698/103242858-cf671d80-4968-11eb-9a19-170a75d93399.png)

**Comment by MrBurrBurr** [comment]
Check if #1231 fixed it.

**Comment by MrBurrBurr** [comment]
This issue will be closed for now because you were the only one requesting it and it's not really needed. It's definitely a nice2have and maybe something for the future. We can always reopen this issue if needed.
