### ISSUE TITLE
Enable immediate scrolling

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1228]
## Purpose
Enable immediate scrolling when opening bot config panel, on Global Config, Log, Releases pages.

## Steps to reproduce
1. Open Global Config page,
2. Press down arrow key,
3. Scrolling doesn't work.

## Current behavior
A single mouse click inside those elements is needed to activate scrolling.

**Comment by MrBurrBurr** [comment]
This issue will be closed for now because you were the only one requesting it and it's not really needed. It's definitely a nice2have and maybe something for the future. We can always reopen this issue if needed.
