### ISSUE TITLE
Install Badge doesn't handle current installed ASF version properly

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1233]
## Description
Install badge is shown if installed version of ASF is newer than the latest one in the configured update channel.

<details>
  <summary>Screenshot</summary>

 ![image](https://user-images.githubusercontent.com/28785698/103413737-d326ba00-4b8b-11eb-9b89-6b4c3380f906.png)

</details>

Also, for the same reason, ASF-ui fails to check for update:
<details>
  <summary>Screenshot</summary>

 ![image](https://user-images.githubusercontent.com/28785698/103413726-cace7f00-4b8b-11eb-8595-1b4d948f774d.png)

</details>

## Steps to reproduce
1. Install ASF newer than the last one released, which can be [found here](https://github.com/JustArchiNET/ArchiSteamFarm/actions).
2. Open Releases page in ASF-ui,
3. Open Log page in ASF-ui.

**Comment by MrBurrBurr** [comment]
Thank you for reporting this.
