### ISSUE TITLE
Click on 'Trying to update' notification should redirect to 'Log' page

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1238]
## Purpose
Besides quick closing, open Log page when clicking on this notification, in order to monitor update progress.

![image](https://user-images.githubusercontent.com/28785698/103665694-c7206b00-4f84-11eb-936d-69eceddcc481.png)

**Comment by MrBurrBurr** [comment]
Right now I do not see any reason not to implement this feature request.

I will think more about it. Maybe someone else will share their opinion.
