### ISSUE TITLE
Improve left side panel layout

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#124]
From this:
https://i.imgur.com/PII9Da4.png

To something like this:
https://i.imgur.com/FJHiD2J.png

We are farming cards foremost.

Thanks.

**Comment by Aareksio** [comment]
Complexity of such solution outweigh it's benefits.

**Comment by Botan626** [comment]
Unnecessary  --- really?

**Comment by Botan626** [comment]
@MrBurrBurr Please review.

**Comment by Botan626** [comment]
@Aareksio 

Complexity --- have no idea about this, since Im no coder.

responsiveness --- don't understand what you mean, when I add keys the number changes pretty fast. But even if not, why is that a problem?

outweigh its benefits --- I just don't understand how come that "MEMORY USAGE" is almost as important as "CARDS REMAINING". Don't know about others, but when I open ASF ui I want to see cards remaining asap.

v.3.4.0.6 has no such small box. But I wouldn't want to fold left panel.
https://i.imgur.com/El0l2vb.png

"While bot statuses can be accurately represented by colors, things like "cards remaining" can not." --- If there are cards to drop, the box is red, otherwise its the same color as "Offline or Disabled" box. Why not?

**Comment by MrBurrBurr** [comment]
I think the layout @Botan626 suggested looks better on maximized navigation. I think that cardsRemaining should be categorized together with bot status rather than system information.

**But** on minimized navigation (not only) we encounter the problems @Aareksio stated and I think those problems outweigh the looks. Tho I don't think the color would be a big problem.

**Comment by Botan626** [comment]
@MrBurrBurr 

The things you said mean that the left panel will be modified the way I suggested?

**Comment by Aareksio** [comment]
Figure out how to present "cards remaining" on small navigation, that's the problem.

**Comment by Botan626** [comment]
@Aareksio 
But you already showed us an example:
![image](https://user-images.githubusercontent.com/28785698/48160936-4ef98480-e2ea-11e8-8ef4-89084383a5ae.png)

I would only change the color to something darker, like 255,170,0, or maybe even 178,34,34, and you are good to go!  :-)
