### ISSUE TITLE
Stuck on bots page!

### ISSUE THREAD

**Issue by SENPAY98K** [JustArchiNET/ASF-ui#1240]
## Description

ASF-ui not working, it just stuck on bots page, you can't go to 'commands' page or any other pages

**Comment by MrBurrBurr** [comment]
> **Before submitting a bug report**
> - Clear the cache of your browser.

Have you tried that?

**Comment by Pabl00t** [comment]
> > https://github.com/JustArchiNET/ASF-ui/blob/master/.github/CONTRIBUTING.md#reporting-bugs
> > **Перед отправкой отчета об ошибке**
> > 
> > * Очистите кеш вашего браузера.
> 
> Вы пробовали это?

Yes it works 100%
