### ISSUE TITLE
Bot automatically added someone

### ISSUE THREAD

**Issue by Duchowa** [JustArchiNET/ASF-ui#1274]
![image](https://user-images.githubusercontent.com/78372560/106490564-04661300-64c7-11eb-9004-a671523eee54.png)

I deleted the ASF after using it once, i had 95 friends when I logged into my account but when I clicked it was 97. I deleted the config file, quit all accounts from steam guard, but I still see these accounts in my friends list. I can't click and check accounts. Sometimes they arise and sometimes they are not visible. They start to appear when you refresh the page. 

This is scary thing, is there no way to remove these accounts from my friends list? Please help me

**Comment by MrBurrBurr** [comment]
This has nothing to do with ASF-ui.

If you have problems deleting your steam friends you can write to steam support.

**Comment by Abrynos** [comment]
Let it be known, that this has nothing to do with ASF itself either.
