### ISSUE TITLE
Logout on Tab Close

### ISSUE THREAD

**Issue by PrincessAkira** [JustArchiNET/ASF-ui#1294]
## Purpose
It will lock the ASF-UI requiring a password on next enter

## Solution
Automatically log the Person out when the Tab is closed, or remember the Browser when going back in.

## Additional information
Im running ASF on my Server and access it via my Subdomain.
I want that, if someone ever finds it, they need to know my Subdomain Password AND my IPC ASF-UI Password and not just SubDomain Password, but if your logged in before it will keep the Password Stored for 12 Hours and then re-invalidate it.

**Comment by Aareksio** [comment]
The password is not stored on the _server_, but in **your** browser. It is possible to invalidate it with session end (`SessionStorage`) or after certain time (cookies). I do not think this provides much security enhancement and should be treated as "nice to have".

This should be somewhat easy change - create a service managing the password with 3 strategies (local storage - current, session and cookie) - PR welcomed :)

**Comment by MrBurrBurr** [comment]
I can't see the improvement in your request. If you want to log out instead of closing the tab.. then just do that?
