### ISSUE TITLE
strange formatting

### ISSUE THREAD

**Issue by Stiefel1234eu** [JustArchiNET/ASF-ui#1357]
Hello guys,
if I start ASF (tried it on win64, arm, linux64 all the same result) I get a wired formatting in the cli and web gui.
Idk if this is a gui issue, but I thought I would post it here first.

Here some example pictures:
![image](https://user-images.githubusercontent.com/63855548/113278543-56b68b00-92e2-11eb-9d70-e7f53db9bfb0.png)
![image](https://user-images.githubusercontent.com/63855548/113278592-659d3d80-92e2-11eb-8889-88eb22a9910d.png)

Are you aware of this issue?

Cheers
Stephan

**Comment by dgncnr** [comment]
I think it is April fools. That scared me a lot on midnight and I checked update notes. It says "Spoiler: Added April Fools easter egg."

**Comment by Stiefel1234eu** [comment]
> I think it is April fools. That scared me a lot on midnight and I checked update notes. It says "Spoiler: Added April Fools easter egg."

Okay... that got me.
