### ISSUE TITLE
About Arrow Keys In The ASF-UI

### ISSUE THREAD

**Issue by WiLuX-Source** [JustArchiNET/ASF-ui#1358]
## Purpose
Disabling Arrow Keys In Some Areas Of ASF-UI Or Completely.

## Solution
Bring an option to the disabling arrow keys completely or disabling in while activating a key.
(Sometimes we write our keys wrong or we need to decyrpt it. thats why I want this. Arrow keys annoys me while decyrpting a key.)

**Comment by MrBurrBurr** [comment]
Could you please try to re-phrase your problem? I can't understand what you are having troubles with.

Feel free to record a short gif or take some screenshots to further explain your issue.

**Comment by WiLuX-Source** [comment]
![hey](https://user-images.githubusercontent.com/61833703/113290901-ec5e1480-92fa-11eb-8e80-3dd1959893f4.gif)

**Comment by WiLuX-Source** [comment]
See how it changes while pressing arrow keys
I want a option to disable that.

**Comment by MrBurrBurr** [comment]
Oh, okay now I understand. This is a bug. Thank you for reporting it!
