### ISSUE TITLE
CurrentCulture Flag Bug

### ISSUE THREAD

**Issue by WiLuX-Source** [JustArchiNET/ASF-ui#1375]
## Description
Some Of The ASF elements Ignore CurrentCulture Flag

## Expected behavior
That ASF elements should also be translated to the CurrentCulture Option.

## Current behavior
ASF recognizes the CurrentCulture option but can't apply them to the some of the elements in the UI

## Additional Info
My System Uses English Windows Language.
My browser Uses Turkish Language & My CurrentCulture Flag is set to "tr-TR" for using Turkish language everywhere.
## Screenshots
![image](https://user-images.githubusercontent.com/61833703/115127217-81d8f400-9fdd-11eb-9e7e-895f2aa88a4f.png)
![image](https://user-images.githubusercontent.com/61833703/115127241-b8af0a00-9fdd-11eb-959d-41c986219707.png)

**Comment by MrBurrBurr** [comment]
This is not a bug in ASF-ui.

It's just that those strings haven't been translated by the community yet. Please feel free to read more about it on ASF's wiki: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Localization
