### ISSUE TITLE
Помогите с ASF не открывает UI сайт!

### ISSUE THREAD

**Issue by Byxel** [JustArchiNET/ASF-ui#1388]

**Comment by Byxel** [comment]
Запускаю консоль все работает находит IPC - готов, далее запускаю сайт UI и вдруг страница не найдена.

**Comment by MrBurrBurr** [comment]
Hello,

this seems like a configuration-problem on your end. Try to read ASF's wiki, more specific the IPC section: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC-ru-RU
