### ISSUE TITLE
Error Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by iamnotadummy** [JustArchiNET/ASF-ui#1400]
When clicking on bot's config, I get the error "Cannot read property 'replace' of undefined"

**Comment by MrBurrBurr** [comment]
What version of ASF-ui are you using (bottom right corner in ASF-ui, copy the whole text)?

And have you tried to clear your cache?

**Comment by iamnotadummy** [comment]
> What version of ASF-ui are you using? Look to the bottom right corner in ASF-ui and copy the whole text.
> 
> And have you tried to clear your cache?

ASF 5.0.2.4 - linux-x64 - be5c4c3
yes, tried it on incognito too

**Comment by MrBurrBurr** [comment]
You are using an outdated version of ASF-ui and ASF.

Please update ASF to v5.1.0.2 and see if this fixes your problem.

**Comment by iamnotadummy** [comment]
ASF 5.1.0.2 - linux-x64 - be5c4c3
New error, "ArchiSteamFarm.BotConfig is invalid!" after updating

**Comment by MrBurrBurr** [comment]
> be5c4c3

You still have an old version of ASF-ui installed.

> since update button on gui is missing and update command does not work

This is because you have disabled updates in your config or you are running inside docker.

**Comment by mostm** [comment]
@MrBurrBurr I'm experiencing same "ArchiSteamFarm.BotConfig is invalid!" (which calls "api/structure/ArchiSteamFarm.BotConfig") under 5.1.0.2. Can you look at this line?

https://github.com/JustArchiNET/ASF-ui/blob/511b0f9e9d29826f24001d3f62ba3c9f0955eb69/src/utils/fetchConfigSchema.js#L98

**Comment by MrBurrBurr** [comment]
> @MrBurrBurr I'm experiencing same "ArchiSteamFarm.BotConfig is invalid!"

Seems like you are using out of date ASF-ui or ASF then. Please post a screenshot of the error you are getting. Make sure I can see the bottom right cornor of ASF-ui.

**Comment by mostm** [comment]
> > @MrBurrBurr I'm experiencing same "ArchiSteamFarm.BotConfig is invalid!"
> 
> Seems like you are using out of date ASF-ui or ASF then. Please post a screenshot of the error you are getting. Make sure I can see the bottom right cornor of ASF-ui.

The reason behind this was the cache, sorry for misintepreting this :)
I can't reproduce this anymore
