### ISSUE TITLE
protocol missing while using reverse proxy

### ISSUE THREAD

**Issue by Stiefel1234eu** [JustArchiNET/ASF-ui#1401]
As soon as I try to access the web gui with nginx infront of it the menu point "protocol" is just empty

Do I have a misconfiguration?

server {
  listen *port* ssl;
  server_name default;
  ssl_certificate_key /etc/letsencrypt/live/stiefel1234.eu/privkey.pem;
  ssl_certificate     /etc/letsencrypt/live/stiefel1234.eu/cert.pem;
  auth_basic "Restricted access";
  auth_basic_user_file /etc/nginx/passwords;
  location / {
     proxy_pass http://127.0.0.1:1242/;
  }
}

Cheers
Stephan

**Comment by MrBurrBurr** [comment]
This has nothing to do with ASF-ui.

Please see the FAQ in the IPC section on ASF's wiki: https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#can-i-use-asfs-ipc-behind-a-reverse-proxy-such-as-apache-or-nginx
