### ISSUE TITLE
2fa input through web gui

### ISSUE THREAD

**Issue by Stiefel1234eu** [JustArchiNET/ASF-ui#1402]
Hello,
is it possible to implement a way to enter the 2fa code through the web gui?
(maybe somehow inside the protocol)
That you don't need to connect to the server each time you want to add a bot

Cheers
Stephan

**Comment by iamnotadummy** [comment]
you can by running it headless

**Comment by Stiefel1234eu** [comment]
@iamnotadummy
u are right

but if you **want** to add a new account then you need to enter the 2fa into the console, don't you?

**Comment by iamnotadummy** [comment]
no, you can do it via gui

**Comment by Stiefel1234eu** [comment]
omg... you need to click on "input required"...

well thanks
