### ISSUE TITLE
Cannot Display "ArchiSteamFarm"

### ISSUE THREAD

**Issue by haIfway** [JustArchiNET/ASF-ui#1403]
## Description

Can't launch ArchiSteamFarm as an executable, keep getting the following error message:
"Could Not Display "ArchiSteamFarm"
There is no application installed for "shared library" files.

I already have the file's permission set to allow executing the file as a program.
and installed the following:
```libc6 , libgcc1 , libicu , libgssapi-krb5-2 , libssl1.1 , libstdc++6 and zlib1g``` using ```apt``` , and .net sdk; used sudo apt upgrade && sudo apt update  
## Screenshots
![image](https://user-images.githubusercontent.com/83737346/118554677-21ea8000-b738-11eb-9c5d-c32dc65e65bb.png)
![image](https://user-images.githubusercontent.com/83737346/118554694-2adb5180-b738-11eb-84d6-a1cc0449e374.png)
![image](https://user-images.githubusercontent.com/83737346/118555179-c076e100-b738-11eb-9e23-b39492450a46.png)
![image](https://user-images.githubusercontent.com/83737346/118556553-6414c100-b73a-11eb-8a57-8a6731631f3e.png)

**Comment by MrBurrBurr** [comment]
This has nothing to do with ASF-ui. Please learn how to use your OS.

Start ASF via terminal "./ArchiSteamFarm".

**Comment by Ryzhehvost** [comment]
https://gitlab.gnome.org/GNOME/nautilus/-/issues/1601
Let me quote Archi:
![image](https://user-images.githubusercontent.com/15903022/118593676-c1e3f000-b7b0-11eb-9f6b-895d747eb2c9.png)
