### ISSUE TITLE
Add categories on Plugins page

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1405]
## Purpose
Plugins page could give more info for the user about his setup.

Example: SteamTokenDumperPlugin is disabled in global config, but ASF-ui just showes that it's installed, not giving the user info whether it's enabled or not.

<details>
  <summary>Screenshots</summary>
  
![image](https://user-images.githubusercontent.com/28785698/119277478-a3567c80-bc28-11eb-9c8a-998f29b26cd6.png)

![image](https://user-images.githubusercontent.com/28785698/119277576-31326780-bc29-11eb-976d-247fd30e245b.png)

</details>

## Solution
Add 'Installed' and 'Enabled' categories on Plugins page.

**Comment by Abrynos** [comment]
This would require the IPC API to provide such info, which is not possible at the moment. We COULD add a plugin interface such as `IConfigurable` that provides the configuration structures to ASF, which then could result in a new API endpoint, but I am not sure whether we really need/want that.

**Comment by MrBurrBurr** [comment]
Pretty much what @Abrynos already said. I will close this issue for now since we already got #1012 which would make this enhancement idea possible (and would also probably include it).

**Comment by Botan626** [comment]
> and would also probably include it

Add Wishlist label until it's done then? I don't see how exactly this feature request duplicates the one you mentioned above.

**Comment by MrBurrBurr** [comment]
No need to. This feature request duplicates a small part of the original issue I linked.
