### ISSUE TITLE
Add link to FEATURES in the footer

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1406]
## Purpose
I think most people who use ASF-ui don't open its github page, so this will give them more chances to learn ui's features.

## Solution
Add 'ASF-ui Features' button in the footer after 'Wiki' button. Probably also rename 'Wiki' button to 'ASF Wiki' to separate them more clearly.

## Additional information
Potential icons:
https://fontawesome.com/v5.15/icons/info?style=solid
https://fontawesome.com/v5.15/icons/info-circle?style=solid

**Comment by MrBurrBurr** [comment]
I agree that most people using ASF-ui will never learn about those hidden features.

But I do not think that this is the best way to solve this issue. The fact that those features are so hidden is a problem in itself. Nothing should be "hidden" from the user. Everything _should_ be easy to understand and use. I had some kind of [tour](https://introjs.com/) in mind but I am not sure about it just yet.

**Comment by Botan626** [comment]
They are hidden as much as Windows shortcuts. You have to make several clicks or google them to find and learn them.
You can just remove the word 'Hidden' from ASF-ui's main page and add a button to Features in the footer, those who will be interested to see what are these features will click on this button, others just won't.

**Comment by MrBurrBurr** [comment]
I will merge my PR #1413 for now. Let's see if it will survive or if I (or someone else) can come up with a better solution.

**Comment by Botan626** [comment]
> I will merge my PR #1413 for now. Let's see if it will survive or if I (or someone else) can come up with a better solution.

![image](https://user-images.githubusercontent.com/28785698/120894948-8c019100-c623-11eb-94a2-d2c76735f138.png)

1. Why there is a button for discussions, if there are also other support channels?
https://github.com/JustArchiNET/ArchiSteamFarm/blob/main/.github/SUPPORT.md

2. Why is it in the second place?

3. Why having there any button for support channel, if there is a button for Wiki?

4. Wiki and Features buttons relate to differents parts of ASF, and they don't indicate it now.

My suggestion is this:
![001](https://user-images.githubusercontent.com/28785698/120895286-ed762f80-c624-11eb-9e02-230bc52c4ac9.png)
