### ISSUE TITLE
Regardless the account's card !

### ISSUE THREAD

**Issue by SENPAY98K** [JustArchiNET/ASF-ui#1414]
1. It would be a great if we can add more shortcuts on the card like:
 `disable account` | `pause/resume` | `BGR `| `2FA `
![image](https://user-images.githubusercontent.com/77079047/120879714-401c0100-c5bd-11eb-842d-f42efdfc0334.png)

---

2. Well a setting to resize the account card would be very helpful as well.
Good luck.

**Comment by Botan626** [comment]
1. You already can do it. Open UI Config and find 'Quick action button' setting.

2. This feature was asked in Feb 2019 #402 , it's still on wishlist with no solution.

**Comment by SENPAY98K** [comment]
> 1. You already can do it. Open UI Config and find 'Quick action button' setting.
> 2. This feature was asked in Feb 2019 #402, it's still on wishlist with no solution.

Its very ugly tbh, I hope the devlopers consider this enhancement to ASF-UI. :)

**Comment by MrBurrBurr** [comment]
I reopened issue #402. Let's see if someone can suggest a good, maintainable and mobile-friendly solution for this.
