### ISSUE TITLE
Close BGR and User Input windows by pressing Esc key

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1418]
## Purpose
Currently these 2 windows can't be closed by pressing the Esc key.

<details>
  <summary>Screenshots</summary>
  
![image](https://user-images.githubusercontent.com/28785698/121086505-e8afa800-c7eb-11eb-93fd-81e5a2c7f5d3.png)
![image](https://user-images.githubusercontent.com/28785698/121086525-efd6b600-c7eb-11eb-8f96-bba7ebad862d.png)

</details>

**Comment by MrBurrBurr** [comment]
They can be closed by pressing the Esc key.
Just unfocus the input field / textarea and it will work.

We could change this behavior to always close the modal upon pressing the Esc key, no matter what element is in focus.

But I am not sure if we want to do this. I wonder what the UX best practice would be here...

**Comment by MrBurrBurr** [comment]
I wonder what @JustArchi, @Aareksio and @Abrynos think about this.

What behaviour would you expect in this case?

**Comment by Botan626** [comment]
Any reason why these windows shouldn't get closed, if Esc is pressed, like the rest of the windows?

**Comment by JustArchi** [comment]
> What behaviour would you expect in this case?

I wouldn't expect ESC to do anything. If it's supposed to do something, first ESC would unselect the input, second ESC would close the modal (as text input is no longer selected).

**Comment by Botan626** [comment]
Why the user would want to just unselect input? What for? What's next? But he might want to close the whole modal, if he wants.

**Comment by Abrynos** [comment]
> But he might want to close the whole modal, if he wants

He can do that by clicking anywhere on the site that is not the modal itself (or the X  in the top right corner).

**Comment by Botan626** [comment]
> He can do that by clicking anywhere on the site that is not the modal itself (or the X in the top right corner).

I know that, when will you stop telling me the obvious?

**Comment by Botan626** [comment]
Esc should not close any modals with possible unsaved changes, hence closing the issue.
