### ISSUE TITLE
ASF-ui does not open Setup page after ASF window was closed

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1423]
## Description
If ASF window was closed, ASF-ui does not open Setup page.
https://i.imgur.com/GLYIGgb.gif

## Steps to reproduce
In Chrome:
1. Clear local and session storages, remove cookies,
2. Empty cache and hard reload UI's page,
3. Open console,
4. Close ASF window.

## Screenshots
<details>
  <summary>Screenshot with errors</summary>
  
![image](https://user-images.githubusercontent.com/28785698/121363408-997a8c00-c93f-11eb-907e-f89d8312560d.png)

</details>

**Comment by MrBurrBurr** [comment]
This happens because ASF-ui can't fetch content from web-server (because you killed it).

Currently I do not have an idea on how to solve this. Feel free to suggest a solution.

**Comment by Aareksio** [comment]
ASF is the webserver of ASF-ui in your case. Once the webserver closes, all subsequent requests fail. Nothing _we_ can do. If you want your UI to be always active, consider using different webserver. Out of support.
