### ISSUE TITLE
Do not open Bots page if Esc key was pressed

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1424]
## Purpose
Currently ASF-ui opens Bots page, if Esc key was pressed on any UI's page, excluding Commands page.

If Esc key is pressed on Bots page, there is an error in console:

![image](https://user-images.githubusercontent.com/28785698/121365607-7650dc00-c941-11eb-9f50-fffbb7129d55.png)

**Comment by Abrynos** [comment]
you can also go from `/page/commands` to `/page/bots` by pressing ESC. You just have to press it twice, since the first press is for deselecting the input field and only the second one is used for navigation.

**Comment by Botan626** [comment]
> You just have to press it twice, since the first press is for deselecting the input field and only the second one is used for navigation.

Doesn't work for me.

**Comment by Aareksio** [comment]
Did you know pressing left and right arrows also throws an error? :)

**Comment by Botan626** [comment]
No.
