### ISSUE TITLE
Error when reloading Mass Editor page

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1425]
## Description
Console shows error when reloading Mass Editor page.

## Steps to reproduce

1. Open Mass Editor page,
2. Open console,
3. Reload the page twice,
4. See error.

## Screenshots
![image](https://user-images.githubusercontent.com/28785698/121389782-69d67e80-c955-11eb-8b61-1ca6163db023.png)

**Comment by Botan626** [comment]
Because of this error list with properties won't be loaded on 2nd stage and this message won't be shown:
![image](https://user-images.githubusercontent.com/28785698/121392382-01d56780-c958-11eb-9565-9dd099d28b00.png)

![image](https://user-images.githubusercontent.com/28785698/121392032-ac00bf80-c957-11eb-9c65-232b88cfe1d5.png)

**Comment by MrBurrBurr** [comment]
Thank you for reporting, should be fixed with latest commit. Feel free to verify.

**Comment by Botan626** [comment]
I don't see any console errors, but now Mass Editor can't find any bots when refreshing browser page.

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/121793726-d5954180-cc0a-11eb-8cff-a944f2b4697d.png)

</details>

**Comment by MrBurrBurr** [comment]
> I don't see any console errors, but now Mass Editor can't find any bots when refreshing browser page.

Thank you. I just tested with ASF running locally and I did not run into that error. When I switched over to test on my remote ASF instance I could reproduce it.

It _should_ be fixed now, feel free to verify it again.

**Comment by Botan626** [comment]
> Thank you.

I'm glad to have been of help.

> It _should_ be fixed now, feel free to verify it again.

Looks like it's fixed now, though I noticed it sometimes can take a longer time to load bots, comparing to other loadings when reloading UI page.

Please notice how long it takes to load bots in first and last loadings in this gif: https://i.imgur.com/0eLkxyC.gif

**Comment by MrBurrBurr** [comment]
> Looks like it's fixed now, though I noticed it sometimes can take a longer time to load bots, comparing to other loadings when reloading UI page.

Yes, I noticed this as well. But we will have to live with this for now until we find a better solution. I will refactor Mass Editor in the future. Maybe at some point I will find a solution.

**Comment by Botan626** [comment]
> > Looks like it's fixed now, though I noticed it sometimes can take a longer time to load bots, comparing to other loadings when reloading UI page.
> 
> Yes, I noticed this as well. But we will have to live with this for now until we find a better solution. I will refactor Mass Editor in the future. Maybe at some point I will find a solution.

Should we do something in order not to forget it? I can open another enhancement issue and include a link to this post https://github.com/JustArchiNET/ASF-ui/issues/1425#issuecomment-860256066.

**Comment by MrBurrBurr** [comment]
No need to at the moment. I have a comment in the code reminding me about it. After I finished some of my refactoring regarding Mass Editor we can check again.

**Comment by Botan626** [comment]
> No need to at the moment. I have a comment in the code reminding me about it. After I finished some of my refactoring regarding Mass Editor we can check again.

Was this fixed?
