### ISSUE TITLE
Remove improper articles in strings in Mass Editor

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1426]
## Purpose
No need for the article _the_, when we talk about things in general, or when they mean _all_.

http://www.englishteachermelanie.com/grammar-when-not-to-use-the-definite-article/
http://www.butte.edu/departments/cas/tipsheets/grammar/articles.html

These strings should be modified:
`Select the bots you want to edit config properties for` --> `Select bots you want to edit config properties for`
`Select the config properties you want to edit` --> `Select config properties you want to edit`
`Edit the config properties you selected` --> `Edit the selected config properties`

**Comment by Botan626** [comment]
Very nice you made these changes :relaxed:

**Comment by MrBurrBurr** [comment]
To be honest, my english skills are not very good and I just merged it to get rid of the open issue.

**Comment by Botan626** [comment]
> To be honest, my english skills are not very good and I just merged it to get rid of the open issue.

These incorrect suggestions were mine too :relieved:
https://github.com/JustArchiNET/ASF-ui/pull/1409#issuecomment-855478428 and https://github.com/JustArchiNET/ASF-ui/pull/1409#issuecomment-855906547
