### ISSUE TITLE
Don't fetch release info of installed version of ASF, if it's newer, than the latest released version

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1427]
Opening Releases page in ASF-ui causes failing requests to GItHub.

![image](https://user-images.githubusercontent.com/28785698/122051137-e9000280-cdec-11eb-900b-6feceec344f1.png)

Also, this will, probably, reduce time for this notification to appear, when user presses Update button, currently it takes more than 15 seconds.

![image](https://user-images.githubusercontent.com/28785698/122051611-76dbed80-cded-11eb-89e8-4f2fc644c69c.png)

**Comment by JustArchi** [comment]
There is endpoint that returns latest released version (ever), ASF-ui should make use of it.
