### ISSUE TITLE
Mass editor - Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#1436]
## Description
pressing next after selecting the value for a configuration field results in an empty page and the error `Cannot read property 'length' of undefined` in my browser console.

## Steps to reproduce
- Install ASF v5.1.1.1 (latest pre-release rocking current ASF-ui version)
- load ASF-ui and reload with CTRL+F5 to make sure the cache is not a problem 😉
- go to your ASF instances web-server and visit the mass editor page
- select bots (in my case 2) and click next
- select config properties to change (in my case only one: `Enabled`) and click next
- set the value (in my case i clicked on the checkmark and not the x) and click next

## Expected behavior
content being shown

## Current behavior
empty page and error in console (see screenshot)

## Screenshots
![image](https://user-images.githubusercontent.com/6608231/123003848-1718b000-d3b4-11eb-8004-a2b22753ee17.png)

**Comment by Botan626** [comment]
I followed your steps and I can't reproduce it.

**Comment by Aareksio** [comment]
Also can not reproduce

**Comment by MrBurrBurr** [comment]
Switch language to LOLCAT and you will be able to reproduce :D

**Comment by Aareksio** [comment]
Yup, found it a few seconds after typing the comment, fix is on the way

**Comment by Abrynos** [comment]
Thank you very much for the fast fix. 😄
