### ISSUE TITLE
ASF-ui checks for new release excessively long, if installed ASF version is newer, than latest released

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1441]
## Description

This would reduce time for this notification to appear, when user presses Update button, currently it takes more than 15 seconds.
![image](https://user-images.githubusercontent.com/28785698/123012868-b5fcd680-d3cb-11eb-9c42-8fa01373fab6.png)

ASF shows its warning message immediately after Update button is pressed, while ASF-ui is checking for new version for 15+ seconds.
![image](https://user-images.githubusercontent.com/28785698/123012928-da58b300-d3cb-11eb-8019-ffdaab69d458.png)

## Steps to reproduce
1. Install ASF of [newer version](https://github.com/JustArchiNET/ArchiSteamFarm/actions), than latest released,
2. Press Update button in UI or execute `update` command,
3. Count seconds until you see the notification or ASF-ui's respond.

**Comment by Aareksio** [comment]
@JustArchi `POST /api/asf/update` seems to take roughly 15 seconds when the current version is ahead of update channel.

![image](https://user-images.githubusercontent.com/11166786/123013608-d2e1db80-d3c4-11eb-85df-1d9073c2076e.png)
```
{"Result":"5.1.0.9","Message":"V5.1.1.1 ≥ V5.1.0.9","Success":false}
```

**Comment by Botan626** [comment]
This is fixed, I tested it.

**Comment by JustArchi** [comment]
Closing as this was on ASF's core side, no point in keeping it up for ASF-ui, not ASF-ui issue to begin with.

**Comment by Botan626** [comment]
> not ASF-ui issue to begin with

but it showed itself in ASF-ui
