### ISSUE TITLE
Change notification for Mass Editor, when it's not saving config

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1444]
Mass Editor could show different notification, when not saving config.

`Config property (properties) is (are) already of the same value (values) for selected bot (bots)!` suits perfectly in my opinion, this way the user will know he didn't choose new values for selected config properties to save.

**Comment by MrBurrBurr** [comment]
So if at least one config has been saved we will still show current message.

If no config has been saved at all we will show the new message.

If this is what you are suggesting I agree.

**Comment by Botan626** [comment]
> So if at least one config has been saved we will still show current message.

Yes.
