### ISSUE TITLE
ASF-ui does not copy added to BGR keys

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1454]
## Steps to reproduce

1. Open BGR for any bot,
2. Check this key `Y7VWN-22WI7-XET3F`,
3. Press Confirm,
4. Press 'Copy keys to clipboard',
5. See this error in console:

![image](https://user-images.githubusercontent.com/28785698/123860938-3b820880-d92f-11eb-91bb-bc0183e1134c.png)

**Comment by JustArchi** [comment]
This is something I've observed myself as well.

**Comment by Botan626** [comment]
This is how is copies keys, after you closed the issue, if game name is unknown.

![image](https://user-images.githubusercontent.com/28785698/123865936-2ad49100-d935-11eb-90e4-79720ac85bef.png)

**Comment by MrBurrBurr** [comment]
Yes, exactly as it was before.
