### ISSUE TITLE
Empty line disappeares on Releases page

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1457]
## Steps to reproduce

1. Open Mass Editor page,
2. Open Releases page,
3. See this:
![image](https://user-images.githubusercontent.com/28785698/123960909-83993d80-d9b8-11eb-9301-3842e9f773b4.png)
4. Press F5,
5. See this:
![image](https://user-images.githubusercontent.com/28785698/123961019-9a3f9480-d9b8-11eb-8912-5ad0f0dc8d25.png)

**Comment by MrBurrBurr** [comment]
Good catch, thank you.
