### ISSUE TITLE
CSS theme changer for ASF-ui

### ISSUE THREAD

**Issue by CHT5** [JustArchiNET/ASF-ui#1459]
## Purpose
This enhancement idea is for a CSS theme changer, to allow the user selection of a CSS theme to change up their UI style should they want to.

## Solution
In a corner of the top "navbar" in ASF-ui, there should be a dropdown menu with a "save changes" button to allow for the user to select a theme of choice. Should the user select this, they would be greeted with item choices of the current theme, maybe one or two others, and the ability to pick one from their system.

## Alternatives
The alternatives I've considered are either a source file adjustment, which isn't always the best idea; or something that injects the theme which can be a security nightmare.

## Additional information
Hopefully, all the information above is enough. If not, I could try to answer any questions regarding this idea.

**Comment by MrBurrBurr** [comment]
I think it would be better to use an addon such as [Stylus](https://chrome.google.com/webstore/detail/stylus/clngdbkpkpeebahjckkjfobafhncgmne) instead of implementing such feature into ASF-ui.
