### ISSUE TITLE
Unable to create new bot

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#1460]
## Description
In the version of ASF-ui that is part of the official release of ASF 5.1.1.1 it is impossible to create a new bot via ASF-ui.

## Steps to reproduce
- Open bots page
- click on the button to create a new bot
- type in any values for the bots name and password
- press the button to save

## Expected behavior
A new bot is added to ASF

## Current behavior
My browsers console currently displays an Exception every time the value of an input field is changed (see screenshot).

## Screenshots
![image](https://user-images.githubusercontent.com/6608231/124150993-62a51b00-da92-11eb-9242-315d5dca65db.png)

## Additional information
Found thanks to the post of @c111809 over in the discussions of ASFs main repository, which can be found [here ](https://github.com/JustArchiNET/ArchiSteamFarm/discussions/2358) (You may have to use a translation engine).

**Comment by Botan626** [comment]
Already fixed in https://github.com/JustArchiNET/ASF-ui/commit/89a781b5d7a69a3602de94e0934a1eb1edaa4fd0

**Comment by Abrynos** [comment]
oh great. I didn't notice that one. Sorry for opening an issue then
