### ISSUE TITLE
Don't fetch release info of installed ASF version, which was not released

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1464]
ASF v5.1.1.2 was installed, which was ahead of update channel, but was never released, then v5.1.2.0 was released and ASF-ui started to send failing requests to GItHub.

<details>
  <summary>Screenshot</summary>
  
![chrome_fh76eVjaz0](https://user-images.githubusercontent.com/28785698/124336103-72f9ea80-dba5-11eb-91ef-5a97456a2fbc.png)

</details>

**Comment by JustArchi** [comment]
We don't support users running custom builds, and CI build that wasn't released is *also* a custom build. While it makes sense to fetch latest release, compare and come to conclusion that whatever we're running is never than that, so it definitely doesn't exist, I don't see how ASF-ui should magically determine that user is running a version older than latest release that never had a release to begin with.

Up to @MrBurrBurr decision, but I'd classify it as "won't fix".

**Comment by Botan626** [comment]
> I don't see how ASF-ui should magically determine that user is running a version older than latest release that never had a release to begin with

Could ASF-ui somehow determine, that user is running a custom build and therefore not fetch release info for that version on GitHub?

**Comment by JustArchi** [comment]
It already does that for forks and custom source builds, but you're grabbing build directly from CI, this is **on purpose** not any different than official release. Official release only has additional info, like link to download, static number and documentation.

So, no, and not planned.

**Comment by Botan626** [comment]
Maybe ASF-ui could somehow recognize, that installed version doesn't have a [release tag](https://github.com/JustArchiNET/ArchiSteamFarm/tags), and not send requests to GitHub for release information.

**Comment by MrBurrBurr** [comment]
As Archi already wrote.

**Comment by Botan626** [comment]
> While it makes sense to fetch latest release, compare and come to conclusion that whatever we're running is newer than that, so it definitely doesn't exist, I don't see how ASF-ui should magically determine that user is running a version older than latest release that never had a release to begin with.

UI already has logic for cases, when the current version is ahead of update channel. Why it can't be expanded for cases this issue describes?

Archi said he doesn't know **how** it can be done. Why the whole idea should be disregarded?

**Comment by Ryzhehvost** [comment]
So, you suggest to put efforts and increase code base for an edge-case that will literally NEVER happen to any ASF user not involved in development? That's counter-productive to say the least.
