### ISSUE TITLE
Open input modal after first click on Start button

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1465]
## Purpose

If user clicks on the Start button to start a bot in a headless mode, which is going to require user input, input modal could be opened after this first click. Thereafter, if user submitted appropriate data, Submit button could also start bot again.

I suppose input modal should be opened on Bots page only in this case, if user was quick enough to leave Bots page before ASF-ui knew started bot requires user input.

**Comment by MrBurrBurr** [comment]
Yeah, I can see that your suggestion would improve the flow for the user. But sadly I haven't found a good way to implement it yet.
