### ISSUE TITLE
Introduce Shutdown page

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1466]
## Purpose

UI has a Shutdown button, so it should have a shutdown page of some kind.

## Current version

<details>
  <summary>Screenshot</summary>
  
![chrome_5HRsseN85K](https://user-images.githubusercontent.com/28785698/124337510-9d4ea680-dbab-11eb-9136-55f3d2065367.png)

</details>

**Comment by MrBurrBurr** [comment]
I can't see any enhancement for ASF-ui in your suggestion.

**Comment by Botan626** [comment]
> I can't see any enhancement for ASF-ui in your suggestion.

You mean I didn't provide any sketch of such page?

What about an idea in general though?

**Comment by Abrynos** [comment]
> What about an idea in general though?

I don't like it either. If ASF-ui is shutdown, there is nothing to display. Your browser should show your browsers "this webserver can't be reached" page. Or in case there is a reverse proxy in between (e.g. nginx): the configured behaviour for a "bad gateway" error should happen.

**Comment by Botan626** [comment]
UI could know that Shutdown button was pressed and could show in this case some goodbye page or whatever. If it can show what it shows now in the screenshot in the 1st post, it can show such page too.

I didn't mean cases, when ui losts connection to webserver.
