### ISSUE TITLE
Lack of tooltips on the header

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#1469]
Those buttons do not have a tooltip:

![image](https://user-images.githubusercontent.com/1069029/124385804-92913000-dcd7-11eb-9f2c-4c3842ee5162.png)

Since they lack text next to the icon, user will have no idea what they actually do until he clicks on them. I had no idea what the first thing did until I clicked it and realized it logged me out.

Either we should put text there, or add tooltips that could show text on hover. In fact, I think the text similar to the left navigation bar is justified there. The text could be "Logout", "Change language" and "Options".

![image](https://user-images.githubusercontent.com/1069029/124385850-d6843500-dcd7-11eb-8116-23682f780864.png)

**Comment by Aareksio** [comment]
Who puts a logout button on the left anyway? 🤔

**Comment by Botan626** [comment]
Logout button could be placed on the right from gears icon and tooltips could say 'Languages', 'Interface' and 'Logout' accordingly.

**Comment by MrBurrBurr** [comment]
I added some tooltips for now, not sure if we really want to add text next to the icon for those buttons.
