### ISSUE TITLE
Remove IPCPassword from ASF-ui, if it was nulled

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1480]
ASF-ui shouldn't keep `IPCpassword` saved, if it was nulled in global ASF config.

## Steps to reproduce

1. Use [ASF version](https://github.com/JustArchiNET/ArchiSteamFarm/releases)  5.1.2.2 and above with [latest ASF-ui version](https://github.com/JustArchiNET/ASF-ui/actions),
2. Enable `IPCPassword` by setting it to any non-empty value,
3. Log in into ASF-ui,
4. Set `IPCPassword` to `null` in ASF config,
5. Hard reload ASF-ui's page.
6. See, that ASF-ui still has `IPCPassword` saved.

![image](https://user-images.githubusercontent.com/28785698/126414894-284ed682-ebc1-4634-b7fe-10958806be81.png)

**Comment by MrBurrBurr** [comment]
I don't see a way how we could implement this.

How should ASF-ui know that IPCPassword is set to `null`?

**Comment by Botan626** [comment]
I opened this issue **_after_** you said on discord, that you don't know how to implement it.
https://discord.com/channels/267292556709068800/859553121856258058/867192775878115368
https://discord.com/channels/267292556709068800/859553121856258058/867197118028447794

Why did you close it with 'Not possible' label? Leave it to @Aareksio

**Comment by Botan626** [comment]
> How should ASF-ui know that IPCPassword is set to `null`?

When IPCPassword is set to `null`, like it is by default in global ASF config: `"IPCPassword": null`, it means there is no password saved in ASF.json.
There is no way for ASF-ui to determine this?

**Comment by MrBurrBurr** [comment]
> There is no way for ASF-ui to determine this?

No.
