### ISSUE TITLE
ASF-ui removes IPCPassword from ASF Config, when saving it

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1481]
## Steps to reproduce

1. Enable `IPCPassword` by setting it to any non-empty value,
2. Log in into ASF-ui,
3. Open `ASF.json` on your PC,
4. Edit any ASF Config setting in ASF-ui, e.g. set `WebLimiterDelay` to 350, press Save,
5. See, that `IPCPassword` is removed from `ASF.json`.

**Comment by Botan626** [comment]
This was tested with ASF v5.1.2.3, the issue is valid.

**Comment by JustArchi** [comment]
This is a severe security issue, I'd appreciate if you could look into it soon enough @MrBurrBurr

**Comment by MrBurrBurr** [comment]
As Abry already stated on [discord](https://discord.com/channels/267292556709068800/859553121856258058/868101717265367060) this is not a bug in ASF-ui.

**Comment by Abrynos** [comment]
Implemented [over here](https://github.com/JustArchiNET/ArchiSteamFarm/pull/2379). Let's get this resolved ASAP!
