### ISSUE TITLE
asf-ui in ASF v5.1.2.2 unable to connect to IPC Server

### ISSUE THREAD

**Issue by K4r0qtuYNE5G4qgZ** [JustArchiNET/ASF-ui#1482]
The asf-ui in ASF v5.1.2.2 shows "Unable to connect to ASF IPC server. Make sure ASF is running!".
Because ASF itself else is running just fine, it must be something with asf-ui in the v5.1.2.2 package.

**Comment by Aareksio** [comment]
Please read the changelog when using experimental update channel:

> ASF will no longer allow other machines than localhost to access ASF API in IPC interface without IPCPassword set by default, as an extra security measure. You can either set up IPCPassword or override that in IPC.config if absolutely required (#2371).

**Comment by K4r0qtuYNE5G4qgZ** [comment]
I'm sorry about but I run it on a raspi in local Network an it auto-updated and so i also couldn't read any changelogs before updating. But I now have another question, how to override that in IPC.config?

**Comment by Botan626** [comment]
Try installing latest ASF-ui version from here (download any artifact archive): https://github.com/JustArchiNET/ASF-ui/actions/runs/1055996406
Put internals in `www` folder (located in your ASF folder), replace all files. CTRL+F5 ui's page and it will work.

**Comment by Botan626** [comment]
> Please read the changelog when using experimental update channel:
> 
> > ASF will no longer allow other machines than localhost to access ASF API in IPC interface without IPCPassword set by default, as an extra security measure. You can either set up IPCPassword or override that in IPC.config if absolutely required (#2371).
> 
> Let us know if this fixes your case. We have changed the error processing recently so it may be related to that too.

https://discord.com/channels/267292556709068800/859553121856258058/867182855557480448

**Comment by K4r0qtuYNE5G4qgZ** [comment]
Alrighty, thank you very much.
With the new ASF-ui from https://github.com/JustArchiNET/ASF-ui/actions/runs/1055996406 it at least displays a useful message. And I now simply fixed it by adding 192.168.1.0/24 to KnownNetworks although it was already restricted with 192.168.1. * in Endpoints.
