### ISSUE TITLE
I'm not a coder, can someone help me configure an IPC.config file with an IPCPassword in the right syntax?

### ISSUE THREAD

**Issue by driftywinds** [JustArchiNET/ASF-ui#1490]
## Question
I do not know how these things work, I just use ASF on a remote machine and with the latest update I cannot access ASF-UI remotely from my own personal machine as it requires me to make a new IPC.config file with an IPCPassword from what I understand. I do not know the syntax of jsons to make a file, so can anyone help me?

## Screenshots
![Untitled](https://user-images.githubusercontent.com/63164617/126860595-c20b0293-f96e-4d03-9b13-3d6bc1722123.png)

## Additional information
If I have understood wrongly, help in the right direction would be appreciated.

**Comment by CHT5** [comment]
IPCPassword has always been with [Global Config](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#global-config) section of Configuration in ASF wiki, do read that first.

**Comment by driftywinds** [comment]
> IPCPassword has always been with [Global Config](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Configuration#global-config) section of Configuration in ASF wiki, do read that first.

my apologies, for some reason I could not find it when I was looking for it and now it seems very easy to find.

**Comment by driftywinds** [comment]
Thanks for your help, this has solved my issue.
