### ISSUE TITLE
Copy to clipboard copies the output in wrong format

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#1497]
## Description

Previously "copy to clipboard" button in BGR screen copied the output in the same format as ASF expects for its **[BGR](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Background-games-redeemer)** feature, that is, name first, then a tab character, then a key.

Right now the order is reversed, so the key goes first, then tab, then name.

I believe it'd be better if ASF-ui followed ASF in this regard, as one of the usage of that feature is copy-pasting the keys into a text file for future import.

## Steps to reproduce

Add keys to BGR queue, wait for them to get redeemed (or not), use "copy to clipboard" button

## Expected behavior

The format is `Name` `\t` `Key`

## Current behavior

The format is `Key` `\t` `Name`

/cc @MrBurrBurr

**Comment by MrBurrBurr** [comment]
Thank you for reporting this 🎉
