### ISSUE TITLE
Make bot cards higher, when farming

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1503]
To avoid truncating of a game's name.

Current state:
![image](https://user-images.githubusercontent.com/28785698/130236748-75a92283-d434-406d-a2d4-07425e907738.png)

**Comment by MrBurrBurr** [comment]
After thinking a bit more about this issue I no longer think it's actually a problem. This farming status is just for a quick view. If you want to know the exact game title you can always open up the bot modal and look at the games being farmed. If the title is still truncated you can always hover over the tile and the tooltip will be triggered.
