### ISSUE TITLE
ASF-ui shows full links in changelog for commits

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1504]
While it doesn't give any kind of links for PRs and issues.

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/130237762-8426f5b5-855b-4876-afe4-67c3960cd387.png)

</details>

**Comment by MrBurrBurr** [comment]
This is not possible for the same reason explained here: https://github.com/JustArchiNET/ASF-ui/issues/1325#issuecomment-797747120
