### ISSUE TITLE
Increase delay for tooltips

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1505]
Currently they are instant **everywhere**.
Probably 1s should be a minimum for a delay.

<details>
  <summary>Gifs</summary>
  
![6rbrPDdIcT](https://user-images.githubusercontent.com/28785698/130242547-9728452a-9e16-4c5d-b210-10db1c4fad39.gif)

![vnMEyiMxey](https://user-images.githubusercontent.com/28785698/130243943-c072b7ee-18b5-4c5a-a9b2-a06f72d83b70.gif)

</details>

**Comment by Abrynos** [comment]
I'd rather have it be configurable as part of `UI Config` (e.g. options `instant` or `delayed`). This very much comes down to personal preference and I for one like to not wait a second for it to pop up.

On the topic of tooltips: I'm not sure why there has to be a tooltip above the bot name (as the first `.gif` shows).

**Comment by Abrynos** [comment]
> This is because user could also choose to display steam nicknames instead of bot names

I never knew this option existed :P thanks for clarification.

**Comment by Botan626** [comment]
> I'd rather have it be configurable as part of `UI Config` (e.g. options `instant` or `delayed`).

Why would anybody want to see a tooltip after the first time he saw it lol? Especially every time. Short memory?

**Comment by Abrynos** [comment]
This has nothing to do with how often the user wants to see a tooltip. If they have bad memory (or any other reasoning), that's their thing. It is good, that we do not have to deal with absolutes, but are actually able to provide users with options.

**Comment by Botan626** [comment]
An option for tooltip, another lol.

**Comment by Botan626** [comment]
> It is good, that we do not have to deal with absolutes

Exactly, hence there is zero need for a new setting for tooltips, just give them the same delay, which they had  before https://github.com/JustArchiNET/ASF-ui/pull/1489.

**Comment by Abrynos** [comment]
Now exactly WHAT about "we do not have to deal with absolutes" didn't you get?

Forcing everyone to have the exact same delay IS an absolute. Giving people a choice is not.

**Comment by Botan626** [comment]
> Forcing everyone to have the exact same delay IS an absolute.

And this will satisfy everybody, like it was before https://github.com/JustArchiNET/ASF-ui/pull/1489.

Why you proposing your crap idea of having a setting for fucking tooltips **now**? Why you never said about it earlier?

Was it again one of your professors, who suggested you this shit, like here https://github.com/JustArchiNET/ASF-ui/issues/402#issuecomment-855250325?

**Comment by Abrynos** [comment]
> And this will satisfy everybody

This statement has already been proven wrong, before you made it by the fact that I said I'd prefer it the other way and I refuse to answer to the rest of your comment.

**Comment by Botan626** [comment]
And I prefer to cross roads anywhere I want, even if it's a 10 line, watch welding without special mask, cook egs in microwave, sit on freshly painted benches, stand under crane's boom, swim in the storm, sit in the bath with plugged in phone, etc.

Now tell everybody, that I prefer all this this way, there point of view is wrong and thereafter start doing things, which will help to avoid bad consequences in each case.

The world doesn't solve these problems, but it should, **because I prefer to do all this exactly this way!**

Btw, I'm also against wars and diseases. What for they are needed at all?

Just because you want something proves, that you are right? You talk with your professors on the same level?

> I refuse to answer to the rest of your comment

This is not new, expectedly. Here is another Q you iqnored https://github.com/JustArchiNET/ASF-ui/issues/1418#issuecomment-865743421, besides ['You really need a sketch in this case to visualize this?'](https://github.com/JustArchiNET/ASF-ui/issues/402#issuecomment-855252578).

**Comment by MrBurrBurr** [comment]
I wonder if we also should have an option to disable tooltips? Then we would have the following options:
- Instant
- Delayed (800ms)
- Hide tooltips

I would just set 5min as the value for "Hide tooltips".

What do you guys think about that?

**Comment by Abrynos** [comment]
> I wonder if we also should have an option to disable tooltips?

That sounds really nice to me. More power to the user 😆

> I would just set 5min as the value

That seems like a hack. Is there no way of "just" not having them?

**Comment by MrBurrBurr** [comment]
> That seems like a hack. Is there no way of "just" not having them?

Yeah it's somewhat of a hack. AFAIK there is no way to "unload" plugins from vue in runtime.

**Comment by Botan626** [comment]
This is the stupidest enhancement ASF-ui has even seen.
You didn't even make 'delayed' setting as default.

At the same time these ideas https://github.com/JustArchiNET/ASF-ui/issues/1464 and https://github.com/JustArchiNET/ASF-ui/issues/1466 are completely useless, in ASF-ui developer opinion.
