### ISSUE TITLE
ASF-ui does not recognize "null" as IPCPassword

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1507]
Though it saves it.

With "IPCPassword": "null" in global config:

1. UI can be accessed without entering IPCPassword,
2. Log page doesn't show log.

<details>
  <summary>Gif</summary>
  
![qjhQQsrb38](https://user-images.githubusercontent.com/28785698/130242420-1cd8aa2d-b890-4c76-8d31-4585d1e713f8.gif)

</details>

**Comment by Abrynos** [comment]
Nice find! 👍🏻 I just confirmed this on the latest pre-release version (5.1.3.4). This works for accessing ASF, but ASF-ui does not save "null" in local storage, which means, that after a page reload you will (once again) have to press the continue-button for the password.

**Comment by Abrynos** [comment]
@Botan626 Can you verify this commit fixes the issue for you as well?

**Comment by Botan626** [comment]
Works, but there will be no rate limited status, if you Press Continue button non stop, it was without this commit.

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/130258142-da4b9cfd-526e-42c4-b5f0-77b97f037c2c.png)

</details>

**Comment by Botan626** [comment]
Also, if UI changes password to "null", by saving it on ASF config page, after ASF restart UI doesn't show Contin ue button.

![image](https://user-images.githubusercontent.com/28785698/130258894-9fde98d7-8724-4e9a-988a-d500d103009a.png)

**Comment by Abrynos** [comment]
> Works, but there is no rate limited status, if you Press Continue button non stop.
> There was rate limited status without this commit.

works for me
![image](https://user-images.githubusercontent.com/6608231/130262833-06eddcb6-f520-4c4b-bc62-1844d2af0bbc.png)

**Comment by Abrynos** [comment]
> Also, if UI changes password to "null", by saving it on ASF Config page, after ASF restart UI doesn't show Continue button.
> UI does show it without this commit.

also works for me
![image](https://user-images.githubusercontent.com/6608231/130263188-e4ad763b-9126-4637-993f-96a6f41f7572.png)

**Comment by Botan626** [comment]
1. There is rate limit, if UI had password saved before. If you logout, and then open UI in the new tab, there wiil be no rate limit.
2. Now I can't steadily reproduce, but it happens from time to time. Probably these 2 things are not related.

**Comment by Botan626** [comment]
> Works, but there is no rate limited status, if you Press Continue button non stop.
> There was rate limited status without this commit.

1. Save "null" password in ASF-ui,
2. Log out of ASF-ui,
3. Reload UI page,
4. Press Continue non stop.

**Comment by Botan626** [comment]
This is the message, when sending password with russian letters. Of course 'Refresh status' button does nothing.

![image](https://user-images.githubusercontent.com/28785698/130315180-a021215e-f81b-440a-ae52-c8a75cf519e0.png)

**Comment by Botan626** [comment]
And more.

Log in into UI with any password, hard reload UI's page, press log out, you won't see, what's on screenshot.

![image](https://user-images.githubusercontent.com/28785698/130336570-fa6b9e73-5891-4087-972a-930825cbc49e.png)

**Comment by Botan626** [comment]
ASF-ui developer, are you still not in loony bin curing your schizophrenia?

Maybe seeing how you are breaking your own statement will finally convince you to ask for help? I guess not.

![image](https://user-images.githubusercontent.com/28785698/135696318-6acc6d87-d2d3-4c93-8d9f-4cd7256037e5.png)

The fact, that exactly 3 bugs were reported before you merged that PR from other schizoid makes it epic.


And you, most likely, disappointed somebody else. You don't care about your mates?

![image](https://user-images.githubusercontent.com/28785698/135696706-699b3863-af89-403d-98f4-79a749d12f9e.png)


Madness.

One day a saviour will come and will **MAKE ASF-UI GREAT AGAIN**.

**Comment by Botan626** [comment]
Is there anybody, who thinks, that this is how I cry, because my bugs were not fixed before merging?

If yes, you should join skurr in his journey to loony bin, and don't forget to take Abry with you.
