### ISSUE TITLE
ASF-ui shows console warning, when creating new bot

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1508]
## Steps to reproduce

1. Click 'Create new bot' on Bots page,
2. Enter ant name,
3. Press 'Create' button,
4. See this in console:

![image](https://user-images.githubusercontent.com/28785698/130240262-5d22269b-1148-41d3-98b8-dc938c93016f.png)

**Comment by MrBurrBurr** [comment]
In this case the warning can be ignored.

**Comment by Botan626** [comment]
In what case this warning can not be ignored? I can give you another case. Does it worth it?
