### ISSUE TITLE
ASF-ui simulates ASF restart, when saving current IPCPassword

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1510]
This is valid for ASF-ui, bundled in ASF v5.1.3.4.

## Steps to reproduce

1. Open ASF Config UI page,
2. Type in your current IPC password in the IPCPassword field,
3. Press Save,
4. See Gif.

<details>
  <summary>Gif</summary>
  
![30LTtLHZYe](https://user-images.githubusercontent.com/28785698/130260457-cae3e1c5-539e-4751-801f-cfefcb8c92c8.gif)

</details>

**Comment by MrBurrBurr** [comment]
This is probably due to the fact that we check if config has changed before saving. And since ASF does not send IPCPassword we do not have anything to check against. So any change to IPCPassword will trigger this behavior.

**Comment by Botan626** [comment]
> probably

Are you never sure too, like somebody else?
![image](https://user-images.githubusercontent.com/28785698/134215113-33172435-3422-4941-92a2-144ff6fd00d9.png)


> will trigger this behavior

And you, ASF-ui developer, justify this confusing behaviour, you don't think there is a need to change it, when this issue reveals, that ui shows below message without even knowing, that restart is actually happening. Is everything correct?
![image](https://user-images.githubusercontent.com/28785698/134215834-28fb5bf8-acb5-4014-8d8e-acd17ce265f0.png)

**Comment by Abrynos** [comment]
It's remarkable how you take a completely unrelated message and put it in a totally new context, just to be able to be passive aggressive to two people at the same time.

**Comment by Botan626** [comment]
Yet another schizoid came up!

Did you ever said this:
![i_view64_mCBqh2hSWX](https://user-images.githubusercontent.com/28785698/134240751-7e9f513f-0e9f-4beb-8192-bca250227865.png)

Then what about your PR https://github.com/JustArchiNET/ASF-ui/pull/1509 name?
![image](https://user-images.githubusercontent.com/28785698/134241126-7b070768-b829-4dd7-a938-83a9197eeda6.png)

Or did you give your discord account to one of your professors, so he could spread some useful knowledge for you?

**Comment by MrBurrBurr** [comment]
@Botan626 
You are violating our [code of conduct](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CODE_OF_CONDUCT.md). This behaviour is unacceptable. Consider this your final warning.
