### ISSUE TITLE
ASF-ui gives rate limited status for valid IPCPassword

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1511]
This is valid for ASF-ui, bundled in ASF v5.1.3.4.

1. Log in into UI with IPCPassword,
2. Hard reload UI page,
3. Log out of UI,
4. See this:

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/130280022-0aea1a2d-b5d7-49cf-a470-3702d38b38ed.png)

</details> 

5. Press Continue button 4 times,
6. Enter your valid password, press Continue and get rate limited status.
![image](https://user-images.githubusercontent.com/28785698/130277748-603b04fd-252b-42db-ac80-aeff6ccb5f9b.png)

**Comment by MrBurrBurr** [comment]
I do not think this is a bug.

ASF decided that your 5th attempt should be blocked since you failed to authenticate for 4 consecutive attempts.

Try to only press the Continue button 2 times and everything works.

**Comment by Botan626** [comment]
>ASF-ui says 'Please enter your IPC password'
>User enters valid IPCPassword
>User gets rate limited status
>Not a bug

This is your self-made schizophrenia confession, skurr, it's time for you to order a ride to loony bin.

> Try to only press the Continue button 2 times and everything works.

Try to reinstall your PC OS, set up ASF and send a valid IPCPassword with the first try, everything will work.
