### ISSUE TITLE
UI Config page is corrupted after some actions

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1518]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest pre-release

### ASF-ui version

817f0bd

### Bug description

UI Config page doesn't display content correctly.

### Expected behavior

<details>
  <summary>Screenshot</summary>
  
![image](https://user-images.githubusercontent.com/28785698/134237721-88d58b05-0b17-45e9-8c60-2f059b29d0c4.png)

</details> 

### Actual behavior

<details>
  <summary>Screenshot</summary>
  
![chrome_iuxuneIqk0](https://user-images.githubusercontent.com/28785698/134236046-1ef2ea70-d8e2-460f-b340-24aba8cbf1da.png)

</details> 

### Steps to reproduce

Often there is no need to repeat clauses 2-6, if UI Config is left opened for 1 minute, before performing clause 2.

1. Open UI Config page,
2. Press Save,
3. Open Log page immediately,
4. Wait for page reload,
5. Open UI Config page immediately,
6. Press Save immediately.
7. Repeat 2-6 until you see screenshot, provided above.

<details>
  <summary>Gif</summary>
  
![WuPVs8J2hd](https://user-images.githubusercontent.com/28785698/134236309-d7671efa-bceb-4708-baba-0c952e3d0360.gif)

</details> 

### Possible reason/solution

Have no idea, UI developers should know better, than me.

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code.

**Comment by Botan626** [comment]
Nice issue form, but:

1. How it can be quickly determined in e.g. a month, what was latest pre-release ASF version?
2. How bug reporter can be always sure, that it's not ASF problem?
3. Fields with no response could be auto deleted.

**Comment by MrBurrBurr** [comment]
Can't reproduce.
