### ISSUE TITLE
Add support for ASF 2FA management endpoints

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#1526]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

ASF recently got new endpoints to support management of ASF 2FA. These should be supported in the official GUI.

### Solution

Add a "Remove Authenticator from ASF" button to a bots 2FA modal.
If the 2FA modal on a bot without authenticator is opened, there should be a button with a text like "Import authenticator" opening a file-selection menu and using the selected file for import.

### Why currently available solutions are not sufficient?

Currently we have to either use swagger, `curl` or copy the file to our ASF instances config folder manually.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

### Additional info

[related merge request](https://github.com/JustArchiNET/ArchiSteamFarm/pull/2426)

**Comment by MrBurrBurr** [comment]
I like that idea! Thank you very much for suggesting it. I will propably implement it as a seperate PR tho.
