### ISSUE TITLE
Cleanup code after ASF commands got "de-steamified"

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#1546]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

After https://github.com/JustArchiNET/ArchiSteamFarm/issues/2500 has been implemented we should also cleanup ASF-ui and remove unused code.

### Can you help us with this enhancement idea?

Yes, I can code the solution myself and send a pull request

**Comment by JustArchi** [comment]
IIRC the only thing that ASF-ui should do is not requiring in any form `SteamOwnerID` from the user now in order to execute commands and/or set up ASF-ui.
