### ISSUE TITLE
infinite loading loop

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#1556]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest pre-release

### ASF-ui version

e35e350

### Bug description

Loading ASF-ui without any items present in the local storage results in the page loading infinitely (probably some sort of infinite recursion/loop).

### Expected behavior

The page loads and displays properly

### Actual behavior

The browser tab keeps loading without actually displaying stuff. Notice the loading animation in the top left corner

![image](https://user-images.githubusercontent.com/6608231/156555855-6260fe92-fe89-4d17-b3a5-0e6cd1d03f1c.png)

### Steps to reproduce

1. open current ASF-ui in an incognito tab
2. observe described behaviour

### Possible reason/solution

Maybe some infinite loop/recursion. I dont know exactly what could cause this. This is only an assumption.

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

### Additional info

Thank you in advance for looking into this and fixing it!

Originally this was reported by @JustBuddy on our ASF discord server.

**Comment by JustArchi** [comment]
@MrBurrBurr I've confirmed this myself, seems like a regression that happened between previous release cycle and this one, which means bug is at most 1 month old. I suspect `SteamOwnerID` changes or some dependency upgrade, there wasn't much happening between those two.

https://github.com/JustArchiNET/ASF-ui/compare/156992e..e35e350

**Comment by JustBuddy** [comment]
Using the 5.2.2.5 "www" folder with the latest ASF bot version lets ASF-ui operate like expected again.
Hope this information helps?

**Comment by Aareksio** [comment]
![image](https://user-images.githubusercontent.com/11166786/156577569-8016c56b-4351-48c8-9b68-e8698ce7f110.png)

1. First time user is redirected from `/` to `/welcome`

![image](https://user-images.githubusercontent.com/11166786/156577743-758c663c-8a28-4da0-a9ad-f457edf6b3ad.png)

2. `/welcome` has no `noPasswordRequired` defined
3. `beforeEach` is triggered, no `if` matches, thus last clause is executed - `next({ name: 'setup' })`
4. `beforeEach` is triggered, navigation is aborted and redirected from `/setup` to `/welcome`
5. Back to 3. in infinite loop

**Comment by JustArchi** [comment]
FYI this is currently blocking updates of ASF-ui bundled with ASF.

**Comment by MrBurrBurr** [comment]
I will create a PR for it later today after work, sorry for the long waiting time.
