### ISSUE TITLE
Make it clearer that user filtered visible bots

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#1564]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

![obraz](https://user-images.githubusercontent.com/1069029/164186597-90d571e4-2861-46b0-b782-54dc95ebf8c4.png)

### Solution

I imagine we should grey-out the unselected options instead, maybe leaving the current green highlight for additional visibility, but that alone is not sufficient.

### Why currently available solutions are not sufficient?

It's not the first time somebody is confused what happened.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by JustArchi** [comment]
![obraz](https://user-images.githubusercontent.com/1069029/164191764-6cee7d83-9c17-453e-a1b2-98384d8e6ce0.png)

This should also be addressed, we can't just set other squares to 0 just because bots are not visible.

**Comment by MrBurrBurr** [comment]
Thank you for creating this issue. I also thought about a solution when I saw DetectiveFingerling's post but you were faster :p

I would suggest the following solution:
Once at least one filter is active we will show a little info:

```
You have a filter active, not all of your bots are currently being shown.
Click here to disable all filters.
```

I think this is a nice solution, let me know what you think.

And regarding:
> This should also be addressed, we can't set other squares to 0 just because bots are not visible.

We are not doing this in the first place. You can try it for yourself and verify.

**Comment by JustArchi** [comment]
I'm not an expert in frontend, whatever you believe is right I support you in that :slightly_smiling_face:
