### ISSUE TITLE
Add support for changing default theme

### ISSUE THREAD

**Issue by SuperSandro2000** [JustArchiNET/ASF-ui#1572]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

I am tired of always changing my default theme and other setting for asf-ui when browser cache gets cleared.

### Solution

A way to change to change the defaults of theme, dark mode, etc. I would also be fine with a patch that changes the defaults.

### Why currently available solutions are not sufficient?

You need to manually change the settings everytime cache is cleared.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by Aareksio** [comment]
Theme preferences is exactly the sort of information that is stored in browser cache. The complaint is the site does not store preferences after you clear the preferences - notice the irony. 

Even if we decided to implement such mechanism, we'd need to store the theme (or any other settings) somewhere. If we went with storing them inside ASF, you'd see a flash of different style for a while before the preferences can be downloaded from ASF. And they'd get lose once you decide to clear the ASF storage too - endless loop.

**Comment by JustArchi** [comment]
> Theme preferences is exactly the sort of information that is stored in browser cache. The complaint is the site does not store preferences after you explicitly clear them - notice the irony.
> 
> Even if we decided to implement such mechanism, we'd need to store the theme (or any other settings) somewhere. If we went with storing them inside ASF, you'd see a flash of different style for a while before the preferences can be downloaded from ASF. And they'd get lose once you decide to clear the ASF storage too - endless loop.

I think middle ground that still would be viable would go like this:
- Load theme from local cache (if available)
- Ask ASF about settings
- If ASF settings are different than local, set local to ASF settings, and change to it
- When user changes settings, save to both local and ASF

This way:
- Initial flash of different style will happen only once after browser cache clearing
- User can still persist his settings in ASF and load them after the above

I already wrote mechanism for that btw, ASF-ui just needs to use it:

![obraz](https://user-images.githubusercontent.com/1069029/171901022-71ff3916-5103-4bab-b9ab-4b448a4cf95c.png)

**Comment by SuperSandro2000** [comment]
JustArchi suggestion sounds wonderful.

I would also happy with a way to change the defaults for the WebUI for every (me) user.

**Comment by MrBurrBurr** [comment]
Related: #1431
