### ISSUE TITLE
Allow only parameters to be passed to the Swagger post request that need to be changed, while not resetting the ones not passed.

### ISSUE THREAD

**Issue by lzrdblzzrd** [JustArchiNET/ASF-ui#1578]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

Allow you to pass the config parameter for the bot to Swagger, while not changing the parameters that were not passed.

### Solution

Allow some parameters to be passed to the post request, but do not reset those that were not passed so that the bot config does not fly off.

Request example:
```
{
  "BotConfig": {
    "GamesPlayedWhileIdle": [
      4294967295
    ]
  }
}
```

### Why currently available solutions are not sufficient?

For example: I want to pass a list of games to GamesPlayedWhileIdle, but if I don't pass in the post request all the other parameters that I don't want to change, then the bot will lose all its settings.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

### Additional info

I do not know if this question was asked or if this idea was suggested, but this is a very necessary functionality for me, since my script accesses Swagger literally every hour, automatically changing the configuration of the bot. And if there is no such functionality, I have two solutions:
1. Write the bot config directly into my script code, having lost the ability to change the config via IPC, since it will be constantly replaced with a hardcoded config.
2. Get the entire bot config completely using a get request, then change the value of the GamesPlayedWhileIdle key and then send the received config with the changed key.

It seems to me that it would be much easier to pass only certain values to the post request without changing the ones that were not passed.

**Comment by MrBurrBurr** [comment]
This is not ASF-ui issue.
