### ISSUE TITLE
Disable `Capture snapshot` button until `Logging` state is saved

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#158]
If you set `Logging` to true (before you click on save) `Capture snapshot` button becomes visible and clickable. If you click the `Capture snapshot` button it will show the notification that a snapshot has been captured. This is in this case wrong because it will first capture a snapshot once we click on save button. We should improve this. Either by disabling the button (similar to "No events logged" button) or by showing a different notification. I would prefer the option where we disable the button.

**Comment by Aareksio** [comment]
To achieve that, we need to make `$sentry` reactive. I'll try to figure it out.
