### ISSUE TITLE
Changing bots display order

### ISSUE THREAD

**Issue by dd410** [JustArchiNET/ASF-ui#1587]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

Would be cool if you could change order in which bots are displayed. Currently looks like they are displayed by alphabetical order.
There is no way to change that in UI. If bots have numbers in name they are displayed in weird way for example instead of Bot1, Bot2, Bot3.... Bot10, Bot11, they will be displayed Bot1, Bot10, Bot11, Bot2, Bot3... Bot9. Would be cool to edit that. At least ascending descending order and from alphabetical to numerical order.

Example:
https://imgur.com/a/jtImzrS

### Solution

 Would be cool to freely edit order of displayed bots. Or at least ascending descending order and from alphabetical to numerical order.

### Why currently available solutions are not sufficient?

Beside changing code manually just for myself i don't know any way to do it.

### Can you help us with this enhancement idea?

Yes, I can code the solution myself and send a pull request

### Additional info

I could help to code it but I am not advanced coder so someone would have to check after me.

**Comment by MrBurrBurr** [comment]
Ordering bots freely by drag'n'dropping will be too much IMHO.

I will add a config option for you to change order to numeric.

**Comment by dd410** [comment]
Yes i agree drag and drop is a lot of work i put it only as suggestion.
Changing order to numeric is everything i wanted.
