### ISSUE TITLE
PathBase not respected and bounces to root

### ISSUE THREAD

**Issue by jaredkotoff** [JustArchiNET/ASF-ui#1589]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

~~0000000~~ c694963

### Bug description

When I try to open the UI using the `PathBase` set in IPC.config I'm redirected back to root

### Expected behavior

I'm able to use ASF-ui with the pathbase route
I open: `http:<ip>:1242/asf`
I end up: `http://<ip>:1242/asf/bots`
Then, I'm able to setup my reverse proxy to use `https://<domain>/asf`

### Actual behavior

I'm always redirected to root path making it unable for me to use a reverse proxy
I open: `http:<ip>:1242/asf`
I end up: `http://<ip>:1242/bots`

### Steps to reproduce

Fresh installation of ASF using Docker
IPC.config: 
```json
{
  "Kestrel": {
    "Endpoints": {
      "Endpoint1": {
        "Url": "http://*:1242/"
      }
    },
    "PathBase": "/asf"
  }
}
```
Go to `http://<ip>:1242/asf`

### Possible reason/solution

Possible regression of https://github.com/JustArchiNET/ASF-ui/issues/1467 ?

### Can you help us with this bug report?

Yes, I can code the solution myself and send a pull request

### Global ASF.json config file

```json                                                                              
{
  "Headless": true,
  "IPCPassword": [redacted],
  "SteamOwnerID": [redacted],
  "Statistics": 1,
  "SteamTokenDumperPluginEnabled": true,
}
```

### Additional info

- Not an issue with ASF: https://github.com/JustArchiNET/ArchiSteamFarm/discussions/2646
- Im using docker-compose:
  ```yaml
  asf:
    container_name: archisteamfarm
    image: justarchi/archisteamfarm:latest
    ports:
      - 1242:1242/tcp
    volumes:
      - /opt/docker/asf/config:/app/config
  ```
  - Still doesn't work in `release` or `main` images
- ~~Version in the corner shows `0000000` which is concerning~~

**Comment by Aareksio** [comment]
You mention the use of a reverse proxy. Are you using any on top of what ASF provides? If so, may we see the config?

The issue you point to was fixed with https://github.com/JustArchiNET/ASF-ui/pull/1468 which explicitly targets your use case (`/ASF`). It was working fine at the time and no change have been made to the relevant code since. If possible, please provide a screenshots from "DevTools > Network" tab with "Preserve log" enabled:

![image](https://user-images.githubusercontent.com/11166786/179296267-6dd04271-d983-48a0-a38b-48e2ef05fcba.png)

**Comment by JustArchi** [comment]
> Version in the corner shows 0000000 which is concerning 

Yes, that's on me, Docker doesn't include `.git` as part of its build process, and this causes ASF-ui to be unable to calculate its own commit hash, I should be able to make exception for ASF-ui in our ASF build process - but this has nothing to do with this issue, just to be clear.

**Comment by JustArchi** [comment]
In any case the ASF-ui version is the same as the one bundled in ASF in non-docker releases, there isn't anything specific there.

**Comment by jaredkotoff** [comment]
@Aareksio Not using a reverse proxy yet, since it doesn't seem to work cause of this. Just trying get it to work with raw IP right now.

<img width="727" alt="Screenshot 2022-07-15 at 12 24 50 PM" src="https://user-images.githubusercontent.com/3268576/179297220-afee67ae-4f14-4e84-ab67-2465e396824e.png">

Seeing bundle load from root: 
<img width="476" alt="Screenshot 2022-07-15 at 12 25 08 PM" src="https://user-images.githubusercontent.com/3268576/179297246-741d9fd9-ffea-4d15-8bab-318d9bc30b51.png">

**Comment by Aareksio** [comment]
@JustArchi is ASF serving the content on both `/` and `BasePath`? Here it clearly loads from `/scripts`, not `/asf/scripts`. I vividly remember stumbling upon this before. 

@jaredkotoff I am positive as soon as you put ASF behind a reverse proxy which disables the access to `/scripts` and only allows `/asf/scripts` it's gonna work. I'll dig a bit to find the old mention of this case.

**Comment by Abrynos** [comment]
I know I'm not Archi, but I know the answer to both questions/statements.

> is ASF serving the content on both `/` and `BasePath`?

Yes. ASF should is serving on both `/` and `BasePath`.

> I am positive as soon as you put ASF behind a reverse proxy which disables the access to `/scripts` and only allows `/asf/scripts` it's gonna work

I concur.

In short: Use `PathBase` only if you need it. If you CAN use `/`, you SHOULD do so.

**Comment by JustArchi** [comment]
> is ASF serving the content on both / and BasePath?

As Abry said above, yes. And this is why I originally recommended to start from the top, so upper dir, and not `/`. I don't remember what original solution did.

**Comment by Aareksio** [comment]
To this day, I believe sacrificing convenience of one user every year to work around ASF's quirk of serving assets on `/` despite setting `BasePath` is not worth for every single user to make redundant requests starting from top of the path. Run behind reverse proxy, this is the intended combination with `BasePath` anyway.

**Comment by MrBurrBurr** [comment]
As @Aareksio said.
