### ISSUE TITLE
Add option to show current steam name

### ISSUE THREAD

**Issue by MalvoTheReal** [JustArchiNET/ASF-ui#159]
Would be cool for UI ASF, if on 'Bots' page you can also see the current nickname that are on steam account.

**Comment by Aareksio** [comment]
I don't think we have access to steam username in ASF API

**Comment by MrBurrBurr** [comment]
Which option do we choose:

1. Close issue
2. Implement function to fetch steam name
3. Ask Archi to implement in API (Maybe Out-Of-Scope)

I think it would be a nice feature to have an option to switch between botNames and steamNames.

**Comment by JustArchi** [comment]
> Ask Archi to implement steamName in API

**Comment by MalvoTheReal** [comment]
That really would be a cool thing. Archi hope you can do that :)

**Comment by MrBurrBurr** [comment]
Your feature request was already implemented in PR #170
