### ISSUE TITLE
Cannot execute commands on mobile device browsers

### ISSUE THREAD

**Issue by zynowhere** [JustArchiNET/ASF-ui#1590]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

9927878

### Bug description

In the command screen, execute the command

### Expected behavior

Press Enter after typing the command, execute the command

### Actual behavior

The cursor moves to the top, like a new line

### Possible reason/solution

In fact, it can be executed in some browsers or with some input methods
For example

|  | Android-Gboard |  ios-default |
| :-----| ----: | :----: |
| chrome | × | √ |
| safari | / | √ |
| via | √ | / |

But，use the ENTER NOT NEXT with Unexpected Keyboard or hack keyboard，it always works

It may be a problem with the IPC page, it was made into a form

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

**Comment by Aareksio** [comment]
https://www.youtube.com/watch?v=jLqTXkFtEH0

I guess we could work around it...

**Comment by JLCareglio** [comment]
Something new?

**Comment by oubeichen** [comment]
This issue has been bothering me for years ever since a certain ASF-ui update. Now I can only use [ASFBot](https://github.com/dmcallejo/ASFBot) to execute commands on the Telegram bot.

**Comment by JustArchi** [comment]
> This issue has been bothering me for years ever since a certain ASF-ui update. Now I can only use [ASFBot](https://github.com/dmcallejo/ASFBot) to execute commands on the Telegram bot.

You can always navigate to `/swagger` and execute the endpoint yourself, you just authorize in top right if you use `IPCPassword`, then you find the `POST /Api/Command` endpoint and put the command in the POST body.

ASF-ui is a frontend to ASF API, not a requirement to use it, which is why other solutions work properly with it.

**Comment by Abrynos** [comment]
While the enter button might be a nice feature, in the meantime you can tap on the `>` character to the left of the input. This works in chromium based mobile browsers as well.

**Comment by oubeichen** [comment]
> While the enter button might be a nice feature, in the meantime you can tap on the `>` character to the left of the input. This works in chromium based mobile browsers as well.

Thank you for your reply. I hadn't noticed that character before. However, I think I've identified the cause of the issue and have submitted a Pull Request.

**Comment by Abrynos** [comment]
> However, I think I've identified the cause of the issue and have submitted a Pull Request.

I've seen it. This is why I noticed the issue in the first place. Thank you for that. I'm looking forward to the enter button working as well.
