### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by DAYAR4ik** [JustArchiNET/ASF-ui#1591]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not **[ASF question](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### The question

can I create ASF on one machine and run ASF-ui on another machine in order to connect to ASF via a domain, through a website?

**Comment by Abrynos** [comment]
Yes. This is possible. I recommend you read the IPC section of [ASF wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki). More specifically the part about [custom configuration](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#custom-configuration).
