### ISSUE TITLE
Alignment and Spacing in WebUI Commands responses

### ISSUE THREAD

**Issue by Knightmore** [JustArchiNET/ASF-ui#1593]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not **[ASF question](https://github.com/JustArchiNET/ArchiSteamFarm/discussions/new?category=Support)**

### The question

As alignment and spacing is possible in the interactive console with String.Format, would it be possible to add a proper parsing for that to the WebUI console?

(ex.: String.Format("{0,-30} {1,-5} {2,-5}\n", badge.Game, badge.Owned, badge.Total);)

**Comment by Aareksio** [comment]
What do you plan to achieve exactly?

**Comment by Aareksio** [comment]
I see, so you want the UI terminal to preserve the extra spaces. This should be achieved with `white-space: pre;` CSS property applied to the terminal container or text line. @MrBurrBurr do you see any obvious issues that may arise from such white space treatment? If not, I suggest we add this as feature request / improvement.

**Comment by MrBurrBurr** [comment]
@Knightmore feel free to check if my [PR](https://github.com/JustArchiNET/ASF-ui/pull/1594) fixes your issue
