### ISSUE TITLE
Account balance is no longer displayed on the robot details page

### ISSUE THREAD

**Issue by zynowhere** [JustArchiNET/ASF-ui#1597]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

f486cd1

### Bug description

The position where the account balance was previously displayed is now blank

### Expected behavior

Robot details page showing account balance

### Actual behavior

New version does not show

### Possible reason/solution

[https://github.com/JustArchiNET/ASF-ui/commit/bce8f8993e649aac4bd82ed3a49e3eac8fe86b98#diff-6decd23fb3c52d71ba50001f38f1820eac149999c2a2584b1b02790d9fd483d2R4](https://github.com/JustArchiNET/ASF-ui/commit/bce8f8993e649aac4bd82ed3a49e3eac8fe86b98#diff-6decd23fb3c52d71ba50001f38f1820eac149999c2a2584b1b02790d9fd483d2R4)

This commit replaces the previously normal getCountryCode with getCurrencyCode, and after deleting the previous getCountryCode.js that stored the currency units, it instead takes the currency units from swagger.json, but the new method assumes that the json is at http://localhost :8080/swagger/ASF/swagger.json

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

**Comment by MrBurrBurr** [comment]
This was already fixed with https://github.com/JustArchiNET/ASF-ui/pull/1595
