### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#16]
This should include the following points:
- Option to change language
- English fallback if target translation isn't available in chosen language
- Auto-detect language based on browser language (or ASF config value `CurrentCulture` if possible)
- Add information about translation percentage and ways to contribute (Maybe on home page and/or as notification)

**Comment by JustArchi** [comment]
Localization should be in form of a single file, e.g. `strings.json` that will be pushed and handled by crowdin. Crowdin will automatically generate files for other languages, e.g. `strings.pt-BR.json` or `string-pt-BR.json` (format up to you) which can be then bundled and used in form of interactive dropdown for language selection.

If you don't want to use `json` for this, you can use any other **[supported format](https://support.crowdin.com/supported-formats/)**. Let me know once you decine upon something, so I can add it to general ASF localization pipeline.

**Comment by Aareksio** [comment]
- language switch: 81f03af375b89a545a0e8e489a1461f964c83024
- auto detect user's language: 472e631e3c095acbaca0680b8ed496fd9d7ce595
- english fallback, other goodies: cfd438cdf368934187d469858160e3fa5f51de1c
