### ISSUE TITLE
Display current Status better

### ISSUE THREAD

**Issue by Joey291** [JustArchiNET/ASF-ui#1616]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

If all card drops are complete and you selected to idle hours there is no visibility that its actually idling. just displaying "online".
i have added 2 Accounts one i configured idling hours and the other one not. both just say online.

### Solution

for better overview in the UI it would be great so see anything else then "online" while idling game hours

### Why currently available solutions are not sufficient?

the current solution just display Online for both. "doing nothing" and "idleling hours".

you have to go to the console to see if your account startet idle hours after you played

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by MrBurrBurr** [comment]
AFAIK this is not possible to achive since ASF will not set a specific status for "idling hours".

Also, its not possible for ASF-ui to get this information in a reliable way. We could try to read it from "GamesPlayedWhileIdle" bot setting but thats a hassle and not 100% reliable.
