### ISSUE TITLE
Disable `copy-log` dropdown item if no event was logged

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#162]
Currently its possible to copy empty event log. Instead user should be informed that there is no event log to copy and that he should either wait for an error to be logged or that he has to capture a snapshot. We could do it as it was before. Disable it and show "No events logged".

**Comment by Aareksio** [comment]
Empty log is still a log

**Comment by MrBurrBurr** [comment]
Sure but why would a user want to copy "nothing" to his clipboard? Wouldn't it be user-friendlier to disable it and show him we he cant click it?

**Comment by Aareksio** [comment]
A lot of things would be more user-friendly. If you figure out how to display it _nicely_, then sure, make it disabled.
