### ISSUE TITLE
Inability to connect to ASF-ui in a day

### ISSUE THREAD

**Issue by CrazyGhostRider** [JustArchiNET/ASF-ui#1625]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

a4617d1

### Bug description

I ran into the problem that after about 20 hours IPC freezes and it is impossible to log in from the browser. At the same time, the ASF console is fully operational. When restarting ASF, everything is restored, but the next day ui hangs again.

I also tried to run ASF in debug mode with one bot. ASF is frozen, but there are logs.
Then I started ASF in debug mode without bots — it also froze. But there are no logs. Since there are no bots.
I also tried to open ASF-ui in different browsers.

### Expected behavior

Opening the ASF-ui

### Actual behavior

This page is unavailable/does not exist

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

### Global ASF.json config file

```json
{
  "Blacklist": [
    570
  ],
  "IPCPassword": "********",
  "LoginLimiterDelay": 30,
  "SteamOwnerID": **********,
  "WebLimiterDelay": 400
}
```

**Comment by CrazyGhostRider** [comment]
ASF 5.4.2.13 Everything also freezes.
But I found that if you make changes to "IPC.config", the ASF restarts the IPC Server.
And unfortunately, the ASF has no function to restart the IPC Server on the command.

**Comment by MrBurrBurr** [comment]
Can't reproduce - Also, so far nobody else has reported this kind of issue. So I believe the issue you are describing is caused by something else, something else on your end.
