### ISSUE TITLE
Add functionality to manage ASF IPC IP bans

### ISSUE THREAD

**Issue by fazelukario** [JustArchiNET/ASF-ui#1627]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

The title speaks for itself.
For convenience and full functionality.

### Solution

Add functionality to manage ASF IPC IP bans.

### Why currently available solutions are not sufficient?

Half a year ago, the functionality of IP bans and their management was introduced in ASF, and it is difficult to imagine a more adequate and human solution for using this functionality than ASF-ui. At the moment, the use of this functionality by the built-in ASF tools is possible only through swagger.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by MrBurrBurr** [comment]
@fazelukario Feel free to check out my PR #1630 and let me know what you think about it.

**Comment by fazelukario** [comment]
> @fazelukario Feel free to check out my PR #1630 and let me know what you think about it.

LGTM, thanks a lot!
