### ISSUE TITLE
J ai un souci pour finir  mon bot il me demande le mot de passe ipc pour steam mais j en ai pas j utilise steam guard c est possible de m aider svp?

### ISSUE THREAD

**Issue by Lagueule** [JustArchiNET/ASF-ui#1628]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

5.4.4.3

### Bug description

J ai un souci pour finir  mon bot il me demande le mot de passe ipc pour steam mais j en ai pas j utilise steam guard c est possible de m aider svp?

### Expected behavior

Je n comprends pas pourquoi il me de passe vue qu je l ai pas

### Actual behavior

Ducoup ca me mets en attente vu que j ai fais trop d essai comme tu peux voir je n ai pas de mot de passe ipc
[Lagueule .txt](https://github.com/JustArchiNET/ASF-ui/files/11186530/Lagueule.txt)

J ai mis le contenue en bas.

### Can you help us with this bug report?

Yes, I can code the solution myself and send a pull request

### Global ASF.json config file

```json
{
  "SteamLogin": "lagueule786",
  "SteamPassword": "****`********",
  "Enabled": true,
  "SteamParentalCode": "***`",
  "RemoteCommunication": 1,
  "AcceptGifts": true,
  "CompleteTypesToSend": [
    3,
    5
  ],
  "LootableTypes": [
    1,
    2,
    4,
    3,
    7
  ],
  "MatchableTypes": [
    14,
    13,
    10,
    8,
    6
  ],
  "SendOnFarmingFinished": true,
  "TradingPreferences": 23,
  "TransferableTypes": [
    14,
    10,
    7,
    8,
    2,
    1
  ],
  "AutoSteamSaleEvent": true,
  "FarmingOrders": [
    9,
    5,
    7,
    6,
    2,
    1,
    10
  ],
  "FarmPriorityQueueOnly": true,
  "HoursUntilCardDrops": 10,
  "Paused": true,
  "SkipRefundableGames": true,
  "BotBehaviour": 22,
  "CustomGamePlayedWhileFarming": "6",
  "CustomGamePlayedWhileIdle": "6",
  "OnlineFlags": 768,
  "OnlineStatus": 1,
  "RedeemingPreferences": 15,
  "ShutdownOnFarmingFinished": true
}
```

### BotName.json config of all affected bot instances

```json
{
  "SteamLogin": "lagueule786",
  "SteamPassword": "*********`",
  "Enabled": true,
  "SteamParentalCode": "****",
  "RemoteCommunication": 1,
  "AcceptGifts": true,
  "CompleteTypesToSend": [
    3,
    5
  ],
  "LootableTypes": [
    1,
    2,
    4,
    3,
    7
  ],
  "MatchableTypes": [
    14,
    13,
    10,
    8,
    6
  ],
  "SendOnFarmingFinished": true,
  "TradingPreferences": 23,
  "TransferableTypes": [
    14,
    10,
    7,
    8,
    2,
    1
  ],
  "AutoSteamSaleEvent": true,
  "FarmingOrders": [
    9,
    5,
    7,
    6,
    2,
    1,
    10
  ],
  "FarmPriorityQueueOnly": true,
  "HoursUntilCardDrops": 10,
  "Paused": true,
  "SkipRefundableGames": true,
  "BotBehaviour": 22,
  "CustomGamePlayedWhileFarming": "6",
  "CustomGamePlayedWhileIdle": "6",
  "OnlineFlags": 768,
  "OnlineStatus": 1,
  "RedeemingPreferences": 15,
  "ShutdownOnFarmingFinished": true
}
```

### Additional info

Mon tel pour que ca soit plus simple. Pour échanger 
 0619962912  
Merci d avance.
A très vite

**Comment by Aareksio** [comment]
The only language supported for issues is English. Please redo the issue.
