### ISSUE TITLE
Indicator to separate online from farming accounts

### ISSUE THREAD

**Issue by SENPAY98K** [JustArchiNET/ASF-ui#1633]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

More control for accounts.
Separating the online accounts that have nothing to farm, from currently farming, will make it easy to execute commands on those specific state accounts, thus less steam requests..

### Solution

Since asf has already know the state of all accounts, adding an optional argument at the end of the command to indicate which accounts to execute the command on.

### Why currently available solutions are not sufficient?

It is sufficient, as this is only an enhancement idea for improving ASF-ui.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

### Additional info

I am not familiar with C#, unfortunately i can't code it.

**Comment by Aareksio** [comment]
I think this belongs to https://github.com/JustArchiNET/ArchiSteamFarm
