### ISSUE TITLE
Funny bug in translate

### ISSUE THREAD

**Issue by An0nX** [JustArchiNET/ASF-ui#1636]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest pre-release

### ASF-ui version

94befd8

### Bug description

I want to take result of `help mabrm` command

### Expected behavior

Удаляет заданные appID из черного списка автоматической торговли в MatchActively.

### Actual behavior

Elfkztn заданные appID из черного списка автоматической торговли в MatchActively.

### Steps to reproduce

`help mabrm` in Russian language

### Can you help us with this bug report?

Yes, I can code the solution myself and send a pull request

**Comment by Aareksio** [comment]
This is actually an issue from ASF wiki:
https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands-ru-RU#%D0%BA%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D1%8B-1

Please scroll down to `mabrm` command. 
You can contribute to the translation here: https://crowdin.com/project/archisteamfarm/ru
