### ISSUE TITLE
Show game that bots are playing ( play bot 730 )

### ISSUE THREAD

**Issue by Kitki30** [JustArchiNET/ASF-ui#1638]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

If you farm the game by manually setting it ( play 730 ) you see online status on the bot (on asf-ui) but you dont see if it's playing why not change it to playing it's good cause you know if it's playing if the bot has invisible/offline status 

a tak wogóle to ty z polski jesteś

### Solution

-

### Why currently available solutions are not sufficient?

-

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

### Additional info

change default ip to phone local IP (I can't access asf on Termux on my computer )

**Comment by Aareksio** [comment]
Playing a selected game is a vanity setting, it does not affect ASF's functionality therefore is not reflected on the ui. For the card farming purpose, which is primary goal of ASF, the account should be treated as "online".
