### ISSUE TITLE
Improve ASF-ui for a better Overview

### ISSUE THREAD

**Issue by xXSUICIDECOMMANDOXx** [JustArchiNET/ASF-ui#1639]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

it would be a great idea to improve the ASF-ui, I suggest the following:

1. add a searchbar in "GamesPlayedWhileIdle" that you can search games by the Name.
2. add gamepictures for the picked games in "GamesPlayedWhileIdle" to make it more clear and to get a better overview.

### Solution

i cant upload a picture but there are many idle sites that have this feature.

### Why currently available solutions are not sufficient?

There are no existing solutions or plug-ins-there

### Can you help us with this enhancement idea?

No, I don't have time, skills or willings for any of that

### Additional info

I think it wouldn't be too difficult to add it.

**Comment by Aareksio** [comment]
`GamesPlayedWhileIdle` is a miscellaneous feature of ASF; The primary purpose of ASF, defining the scope of the project is farming cards. Handling `GamesPlayedWhileIdle` is out of scope for ASF-ui, but you are more than welcomed to create a UI plugin to display these!
