### ISSUE TITLE
Add `2fa` to bot action buttons

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#165]
![image](https://user-images.githubusercontent.com/28785698/48418796-47613200-e767-11e8-829d-d77f805fd212.png)

2FA button for quick sending **2faok** command for a given bot.

**Comment by MrBurrBurr** [comment]
This will be part of a bigger feature update coming in the future.

**Comment by Botan626** [comment]
Great.

**Comment by MrBurrBurr** [comment]
Related: #184
