### ISSUE TITLE
ASF-ui can't show currency

### ISSUE THREAD

**Issue by WiLuX-Source** [JustArchiNET/ASF-ui#1653]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

f84a296

### Bug description

Currency don't show

### Expected behavior

Currency would show

### Actual behavior

![image](https://github.com/JustArchiNET/ASF-ui/assets/61833703/c4fe5d0f-0676-4fd7-ae5f-d28538b36ef2)

### Steps to reproduce

Simply open one of the bots preview.

### Possible reason/solution

Probably a few lines of code fix.

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

### Global ASF.json config file

```json
not needed.
```

### BotName.json config of all affected bot instances

```json
not needed.
```

**Comment by WiLuX-Source** [comment]
![image](https://github.com/JustArchiNET/ASF-ui/assets/61833703/d27f424c-aa19-4323-9b44-c7c622849b12)

**Comment by MrBurrBurr** [comment]
Thank you for reporting the bug.
