### ISSUE TITLE
Add dark mode support for `bot-action color`

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#166]
![19 10 29](https://user-images.githubusercontent.com/31552675/48433661-f4dc4180-e777-11e8-8f61-6d611db33600.png) ![19 10 42](https://user-images.githubusercontent.com/31552675/48433655-f148ba80-e777-11e8-81ec-f5e70b6b8a80.png)

**Comment by Aareksio** [comment]
![Cascades](https://yko.im/ZsS-.png)

Cascades 🙂

**Comment by Aareksio** [comment]
The exact issue is fixed, but we need a proper refactor of these actions
