### ISSUE TITLE
Autocompletes not working (like before)

### ISSUE THREAD

**Issue by clumba** [JustArchiNET/ASF-ui#1660]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not **[ASF question](https://github.com/JustArchiNET/ArchiSteamFarm/discussions/new?category=Support)**

### The question

Previously, autocomplete worked correctly - if I enter `pl`, then `play` is offered. I enter the first letters of the bot's name - the full name is suggested. Now it doesn't work. However, something else works - if you enter the letter `s`, then `sa` (?) is suggested. And if you press TAB... `status ASF` will appear! What's happening? Was there some kind of update that changed the logic of autocomplete?

**Comment by Wolterhon** [comment]
Same. When I type transfer^ nothing shows up, when I send the command as-is without the needed params I get 'unknown command' for some reason, idk if it was like that before. But for sure the auto-complete and param tips is disabled/broken.

**Comment by evgewakan** [comment]
The situation is the same, and not only does it not prompt you to complete the commands, but also the names of the bots must be entered in full manually. At the same time, in ASF Config, when you click on the question mark to expand the list with a description of the parameters, it is also empty

**Comment by zhangminghao1989** [comment]
same

**Comment by MrBurrBurr** [comment]
Works for me. Maybe your ASF can't connect to GitHub to fetch wiki commands page.

**Comment by Wolterhon** [comment]
> Works for me. Maybe your ASF can't connect to GitHub to fetch wiki commands page.

A bunch of random people have this problem, and you just close the issue cause it 'works for you' instead of investigating. Bruh.

**Comment by Botan626** [comment]
d

**Comment by Abrynos** [comment]
Works for me. Try updating to latest version

**Comment by Wolterhon** [comment]
Upading what? ASF updates itself automatically.

**Comment by evgewakan** [comment]
> Works for me. Try updating to latest version

![Снимок экрана 2024-03-18 120236](https://github.com/JustArchiNET/ASF-ui/assets/74374112/41e9b2f1-3430-4454-8f53-f33d738ae5bf)
![1](https://github.com/JustArchiNET/ASF-ui/assets/74374112/a204c6e7-8e9e-43fc-bdbe-e6c849cc422c)
![Снимок экрана 2024-03-18 120033](https://github.com/JustArchiNET/ASF-ui/assets/74374112/24192be3-bf33-4a4f-bf8d-a077a43d7563)

use last stable version ASF

**Comment by ezhevita** [comment]
I can indeed confirm that it doesn't work on the latest stable ASF version but works using the latest pre-release.

**Comment by ezhevita** [comment]
As for global config property descriptions, it was fixed as per https://github.com/JustArchiNET/ASF-ui/issues/1661 and is not included yet in any ASF release.

**Comment by MrBurrBurr** [comment]
> A bunch of random people have this problem, and you just close the issue cause it 'works for you' instead of investigating. Bruh.
I answered his question, what more do you expect? This is not a bug report issue as you can see from the assigned label.

> There's also an issue with the global config page as stated in [this comment](https://github.com/JustArchiNET/ASF-ui/issues/1660#issuecomment-1997980415), does it also require to connect to GitHub?
This issue has already been fixed thanks to the bug report in #1661. And yes it also reads from GitHub and needs to be able to connect to it. But that bug was related to GitHub changing html structure of their wiki page so ASF-ui wasnt able to parse it correctly.
