### ISSUE TITLE
Github parsing (the wiki entry appearing under a setting when clicking the questiomark icon) is broken again

### ISSUE THREAD

**Issue by VasilisThePikachu** [JustArchiNET/ASF-ui#1661]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

7406f71

### Bug description

#1648 again.

The config question mark brings up a link icon that blends with the UI in the background. And clicking it just brings you back to the same entry. Not into a wiki page. Or does not show you the contents of the wiki page at that point
![image](https://github.com/JustArchiNET/ASF-ui/assets/34938708/99d82214-aa9c-4d47-aa7c-b4507002289f)

### Expected behavior

I get the wiki entry. And a link to the wiki

### Actual behavior

You only get a "link" that blends in the background. And clicking that just brings you into the same page at the same setting.

### Steps to reproduce

1. Open settings on a bot
2. Press the question mark on any of the configs

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

**Comment by MrBurrBurr** [comment]
Thank you for reporting this bug! Fix should be available in next ASF pre-release.
