### ISSUE TITLE
Bot’s balance is not displayed when using base path

### ISSUE THREAD

**Issue by ezhevita** [JustArchiNET/ASF-ui#1663]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest pre-release

### ASF-ui version

b112518

### Bug description

Balance is not displayed on the bot’s card when using base path.

### Expected behavior

Balance of the bot is displayed properly.

### Actual behavior

Balance is not displayed at all.

### Steps to reproduce

1. Start ASF with `PathBase` property in IPC.config (and make sure that requests without `PathBase` fail, e.g. by using reverse-proxy)
2. Open bot’s card
3. Balance is not displayed

### Possible reason/solution

To get all possible currency codes ASF-ui relies on swagger schema however it is requested without being prefixed by base path:
https://github.com/JustArchiNET/ASF-ui/blob/b1125188620864f3289f35e2146b93554b941f95/src/utils/swagger/parse.js#L4

Solution would be to prefix that path with `window.__BASE_PATH__` or create axios client with that path as the `baseURL`.

### Can you help us with this bug report?

Yes, I can code the solution myself and send a pull request

**Comment by MrBurrBurr** [comment]
Thank you for your report! Feel free to send a PR if you have the time 💪
