### ISSUE TITLE
Make eye button state coincide with current password visibility state

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1666]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

Currently they mismatch each other, which can be misleading and confusing.
![image](https://github.com/JustArchiNET/ASF-ui/assets/28785698/a15b7d7e-16d6-4b55-9e5a-9104a3d934ca)
If eye is crossed, password should be hidden, and vice versa, shouldn't it?

**Comment by Abrynos** [comment]
You can look at it the other way and interpret the icon as the "action to do" or "target state after the click"... so the crossed out eye means "hide" while the normal eye mans "show".

**Comment by Botan626** [comment]
> You can look at it the other way and interpret the icon as the "action to do" or "target state after the click"... so the crossed out eye means "hide" while the normal eye mans "show".

Or
I can continue to look at it the other way and treat this eye as a switch, which should correctly indicate its current state.

**Comment by MrBurrBurr** [comment]
There is no "correct" here. Both scenarios are valid as long as they are implemented consistently. Look at the encrypt/hash function where the eye icon is normal when the password is masked (not visible) and switches to a crossed-out eye icon when the password is visible.

This approach indicates the action that’s performed when you press the icon.
