### ISSUE TITLE
Improve notification layout

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#167]
Maybe something like [this](https://yko.im/lLn3.png)

Also it would be nice to have a setting in UI Configuration where user can decide where he wants notification to be displayed (e.g. bottom right, top right, top center).

**Comment by Aareksio** [comment]
And that's a good issue!

**Comment by MrBurrBurr** [comment]
This issue will be closed for now because I was the only one requesting it and it's not really needed. It's definitely a nice2have and maybe something for the future. We can always reopen this issue if needed.
