### ISSUE TITLE
Hide the LicenseID

### ISSUE THREAD

**Issue by VasilisThePikachu** [JustArchiNET/ASF-ui#1674]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

I don't see a reason you would need the licenseid to be visible via ui after you entered it. And should kind of help with not accidently exposing the licenseid

### Solution

Just make it hidden!

### Why currently available solutions are not sufficient?

Considering, the LicenseID is meant to be kept hidden except of the person who owns the key. It should be hidden. Similar to the bots password and login field

### Can you help us with this enhancement idea?

Yes, I can code the solution myself and send a pull request

### Additional info

I can try coding this but no promises.

**Comment by MrBurrBurr** [comment]
Ref. https://github.com/JustArchiNET/ArchiSteamFarm/commit/81789c717f137efe94d0111482c75c55954d1e66
