### ISSUE TITLE
Select a specific status to execute a command on it.

### ISSUE THREAD

**Issue by SENPAY98K** [JustArchiNET/ASF-ui#1682]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

This purely for enhancing user experience, which to let user select a status such as `Farming / Online` to execute a command on the bots running with that state.
- For example: `Farm ASF` executed on all bots. In the example `ASF` reflect all bots whether farming or just online.

### Solution

Adding similar selectors as `ASF`.
Could be `FARM` and `ONLINE`

### Why currently available solutions are not sufficient?

Not available.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by Aareksio** [comment]
Sounds reasonable, but this is outside of the scope of ASF-ui, you could try raising a feature request to https://github.com/JustArchiNET/ArchiSteamFarm

**Comment by JustArchi** [comment]
https://github.com/JustArchiNET/ArchiSteamFarm/commit/9f1a3a0304fc93e44a5d8f14b9eac7bf46bba024
