### ISSUE TITLE
Wrong display of ImmutableHashSet<uint> during bot config

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#169]
`GamesPlayedWhileIdle` is being displayed as a single `uint` field, while it should be displayed as a collection of elements (similar to `FarmingOrders` and other sets).

**Comment by Aareksio** [comment]
Too much RimWorld?
![I guess so...](https://yko.im/aesP.png)

**Comment by Aareksio** [comment]
I'll consider adding `,`, `;` and ` ` as possible delimiters.

**Comment by JustArchi** [comment]
![image](https://user-images.githubusercontent.com/1069029/48510910-7950c200-e855-11e8-8a59-d1fa194c32f9.png)

It's not obvious for the user that this field allows multiple values. I had to try out several combinations of keys (including `,` and space) before finally I found out that `enter` does the trick.

It's very inconsistent with other arrays to make it work like that. If other sets include `Add` button, this one should too, even if both input methods would be supported at the same time.

Also, if your set type accepts only numbers, space should also work as enter.

**Comment by JustArchi** [comment]
Therefore, my suggestions:

- If set is numbers-based, make `space` work like enter and add the current value to the array.
- Even with implementing above, there should still be `Add` button for consistency reasons with other sets, arrays and enum flags that all allow multiple values.
