### ISSUE TITLE
Auto execute 'commands' command after double Tab press

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1690]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

Why not?

And description for double Tab could be: `Double Tab press lists all possible commands.`

**Comment by Abrynos** [comment]
> So why not?

Because the maintainer said so. If you want it, feel free to send a PR and hope it gets accepted.

**Comment by Botan626** [comment]
> Because the maintainer said so.

Maintainer said nothing. Stop hallucinating.

**Comment by Aareksio** [comment]
No

**Comment by Botan626** [comment]
> No

So why not?

**Comment by Aareksio** [comment]
Asking 'why not?' shifts the burden of proof from the proposer to the skeptic, bypassing the responsibility to provide reasoning for new ideas or changes. It presumes an obligation to accept every possibility, which can lead to an unsustainable path of endless justifications. Essential to constructive discourse is a balanced evaluation of innovation against the guiding principles and goals of the project.

The requested feature, while intriguing, diverges from the core objectives and streamlined focus that define our project's value and usability. Implementing such a niche functionality would demand disproportionate time and resources, potentially introducing unforeseen complications and ongoing maintenance challenges. Prioritizing features that align with our core vision ensures that we build a cohesive and sustainable tool that serves the broader user community effectively.

We sincerely appreciate your enthusiasm and the thoughtfulness behind your suggestions, as they reflect a deep engagement with our project. However, we kindly ask you to consider aligning future requests with the project's primary goals to help us maintain our focus and efficiency.

**Comment by Botan626** [comment]
> Asking 'why not?' shifts the burden of proof from the proposer to the skeptic, bypassing the responsibility to provide reasoning for new ideas or changes. It presumes an obligation to accept every possibility, which can lead to an unsustainable path of endless justifications. Essential to constructive discourse is a balanced evaluation of innovation against the guiding principles and goals of the project.
> 
> The requested feature, while intriguing, diverges from the core objectives and streamlined focus that define our project's value and usability. Implementing such a niche functionality would demand disproportionate time and resources, potentially introducing unforeseen complications and ongoing maintenance challenges. Prioritizing features that align with our core vision ensures that we build a cohesive and sustainable tool that serves the broader user community effectively.
> 
> We sincerely appreciate your enthusiasm and the thoughtfulness behind your suggestions, as they reflect a deep engagement with our project. However, we kindly ask you to consider aligning future requests with the project's primary goals to help us maintain our focus and efficiency.

That`s what she said.

--


So despite this enhancement idea automates an obvious user action, the reason why it won't be implemented is not given here, leaving me in void and dark.
I can't see how we can continue to efficiently and productively develop this project together as a team.

**Comment by Rudokhvist** [comment]
> I can't see how we can continue to efficiently and productively develop this project together as a team.

Lucky for us, you never was part of the team: https://github.com/orgs/JustArchiNET/people
Stop hallucinating.
