### ISSUE TITLE
a bug with card dropping

### ISSUE THREAD

**Issue by Neoexe01** [JustArchiNET/ASF-ui#1693]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

I don't know what to write in the text that appears when submitting this feedback, this is my first feedback on Github, I apologize if I did something wrong, I have to say that before restarting ASF there was 1 game left to downgrade, after restarting it didn't find any game to downgrade in my account again I'm trying again, it didn't find it again, my advice is to add Whitelist like Blacklist, if Whitelist is added, let it run the games with IDs we enter there and drop cards I use ASF with love, I used it in my 2 accounts, I understand that it does not try to drop cards in risky games, this is a good thing, if Whitelist logic comes in future versions, it will be very good, thanks to the whole team

### Solution

Running games whose ID is entered with whitelist logic in a special way 

### Why currently available solutions are not sufficient?

I don't know about the available solutions so I will leave it blank 

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by MrBurrBurr** [comment]
This has nothing to do with ASF-ui.


Feel free to head over to [ASF](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose) and open an issue

**Comment by Neoexe01** [comment]
> This has nothing to do with ASF-ui.
> 
> Feel free to head over to [ASF](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose) and open an issue

I know that it is not related to ASF-UI, but it is not exactly a bug, I wrote it in the suggestion section because it is like both a bug and a suggestion.
