### ISSUE TITLE
IPC log tab not showing real time logs.

### ISSUE THREAD

**Issue by SENPAY98K** [JustArchiNET/ASF-ui#1697]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest stable release

### ASF-ui version

9f5672d

### Bug description

After setting up asf behind reverse proxy, logs are not showing in ipc.
I have added a basepath `/farm` to result in  `asf.domain/farm/log` 
![image](https://github.com/user-attachments/assets/2a0319f1-df2d-472d-8106-e802ce7bbfe9)

### Expected behavior

Displaying logs in ipc > log tab in real time.

### Actual behavior

Empty ipc log tab, even after loading previous n lines.

### Possible reason/solution

Adding custom path in ipc config.

### Can you help us with this bug report?

Yes, I can code the solution myself and send a pull request

**Comment by Aareksio** [comment]
> After setting up asf behind reverse proxy

Probably reverse proxy not proxying websocket correctly

**Comment by SENPAY98K** [comment]
I used the config provided in faq.

**Comment by Abrynos** [comment]
> I used the config provided in faq.

Works for me.
![image](https://github.com/user-attachments/assets/862ba0cf-b6f4-42b3-bada-744e46a7199b)

**Comment by SENPAY98K** [comment]
> > I used the config provided in faq.
> 
> Works for me. ![image](https://private-user-images.githubusercontent.com/6608231/376111721-862ba0cf-b6f4-42b3-bada-744e46a7199b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTE5MTgsIm5iZiI6MTcyOTIxMTYxOCwicGF0aCI6Ii82NjA4MjMxLzM3NjExMTcyMS04NjJiYTBjZi1iNmY0LTQyYjMtYmFkYS03NDRlNDZhNzE5OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDAzMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjg0ZTExMjdjMjQzZmRlNTk3Yjg0NTlhYWEwZjVmOTY1ZTEzOTQ4ZDEyMTBiYTFlNTliMTBjNGQ1NzA1N2VhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dvg2OeV5SVeCamFQkShyfKT_DLm3O62Exu6qqtsaQoE)

could you share you nginx config?

**Comment by SENPAY98K** [comment]
My config
```php
server {
    server_name asf.domain.com;

    location /stm/ {
	proxy_pass http://localhost:8888;
        include proxy_params;
    }

    location /farm/ {
	proxy_pass http://localhost:9999;
        include proxy_params;
    }

    location ~* /Api/NLog {
	proxy_pass http://localhost:$server_port;
	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Host $host:$server_port;
	proxy_set_header X-Forwarded-Proto $scheme;
	proxy_set_header X-Forwarded-Server $host;
	proxy_http_version 1.1;
	proxy_set_header Connection "Upgrade";
	proxy_set_header Upgrade $http_upgrade;
    }

    listen 443 ssl; 
    ssl_certificate /etc/letsencrypt/live/asf.domain.com/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/asf.domain.com/privkey.pem; 
    include /etc/letsencrypt/options-ssl-nginx.conf; 
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; 

}
server {
    if ($host = asf.domain.com) {
        return 301 https://$host$request_uri;
    }

    server_name asf.domain.com;
    listen 80;
    return 404;
}
```

**Comment by Abrynos** [comment]
> > > I used the config provided in faq.
> > 
> > 
> > Works for me. ![image](https://private-user-images.githubusercontent.com/6608231/376111721-862ba0cf-b6f4-42b3-bada-744e46a7199b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTE5MTgsIm5iZiI6MTcyOTIxMTYxOCwicGF0aCI6Ii82NjA4MjMxLzM3NjExMTcyMS04NjJiYTBjZi1iNmY0LTQyYjMtYmFkYS03NDRlNDZhNzE5OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDAzMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjg0ZTExMjdjMjQzZmRlNTk3Yjg0NTlhYWEwZjVmOTY1ZTEzOTQ4ZDEyMTBiYTFlNTliMTBjNGQ1NzA1N2VhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dvg2OeV5SVeCamFQkShyfKT_DLm3O62Exu6qqtsaQoE)
> 
> could you share you nginx config?

Sure. Here you go:
```
upstream asf {
        server 127.0.0.1:1242;
}

server {
        server_name redacted;
        listen 443 ssl;
        listen [::]:443 ssl;

        ssl_certificate /redacted.crt;
        ssl_certificate_key /redacted.key;
        ssl_protocols TLSv1.3;
        ssl_prefer_server_ciphers on;

        add_header Strict-Transport-Security "max-age=63072000" always;

        server_tokens off;
        more_set_headers 'Server: None Of Your Bussiness';

        location ~* /Api/NLog {
                proxy_http_version 1.1;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Upgrade $http_upgrade;

                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_pass http://asf;
        }

        location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Host $host:$server_port;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Server $host;
                proxy_set_header X-Real-IP $remote_addr;

                proxy_pass http://asf;
        }
}


```

**Comment by SENPAY98K** [comment]
> > > > I used the config provided in faq.
> > > 
> > > 
> > > Works for me. ![image](https://private-user-images.githubusercontent.com/6608231/376111721-862ba0cf-b6f4-42b3-bada-744e46a7199b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTE5MTgsIm5iZiI6MTcyOTIxMTYxOCwicGF0aCI6Ii82NjA4MjMxLzM3NjExMTcyMS04NjJiYTBjZi1iNmY0LTQyYjMtYmFkYS03NDRlNDZhNzE5OWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMThUMDAzMzM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjg0ZTExMjdjMjQzZmRlNTk3Yjg0NTlhYWEwZjVmOTY1ZTEzOTQ4ZDEyMTBiYTFlNTliMTBjNGQ1NzA1N2VhMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dvg2OeV5SVeCamFQkShyfKT_DLm3O62Exu6qqtsaQoE)
> > 
> > could you share you nginx config?
> 
> Sure. Here you go:
> ```
> upstream asf {
>         server 127.0.0.1:1242;
> }
> 
> server {
>         server_name redacted;
>         listen 443 ssl;
>         listen [::]:443 ssl;
> 
>         ssl_certificate /redacted.crt;
>         ssl_certificate_key /redacted.key;
>         ssl_protocols TLSv1.3;
>         ssl_prefer_server_ciphers on;
> 
>         add_header Strict-Transport-Security "max-age=63072000" always;
> 
>         server_tokens off;
>         more_set_headers 'Server: None Of Your Bussiness';
> 
>         location ~* /Api/NLog {
>                 proxy_http_version 1.1;
>                 proxy_set_header Connection "Upgrade";
>                 proxy_set_header Upgrade $http_upgrade;
> 
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header X-Forwarded-Host $host:$server_port;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header X-Forwarded-Server $host;
>                 proxy_set_header X-Real-IP $remote_addr;
> 
>                 proxy_pass http://asf;
>         }
> 
>         location / {
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>                 proxy_set_header X-Forwarded-Host $host:$server_port;
>                 proxy_set_header X-Forwarded-Proto $scheme;
>                 proxy_set_header X-Forwarded-Server $host;
>                 proxy_set_header X-Real-IP $remote_addr;
> 
>                 proxy_pass http://asf;
>         }
> }
> 
> 
> ```

Im using custom config for ipc, to run different types of asf with different ports, that's why im not sure how configure it correctly

**Comment by Aareksio** [comment]
Running on configuration other than the default is not officially supported. You can get it to work, however we will not be able to guide you on how to configure your machine to do so. 

This is the first and last tip I will give, especially since you did not bother to format the config correctly making it unnecessarily harder to read. Your `server` block is configured to `listen 443 ssl` which means it explicitly listens on port 443. Then your `location ~* /Api/NLog` is configured to `proxy_pass http://localhost:$server_port/`, which should always resolve to `http://localhost:433/`. Unless you run ASF on `localhost:443`, it will explicitly not work.

**Comment by SENPAY98K** [comment]
> Running on configuration other than the default is not officially supported. You can get it to work, however we will not be able to guide you on how to configure your machine to do so.
> 
> This is the first and last tip I will give, especially since you did not bother to format the config correctly making it unnecessarily harder to read. Your `server` block is configured to `listen 443 ssl` which means it explicitly listens on port 443. Then your `location ~* /Api/NLog` is configured to `proxy_pass http://localhost:$server_port/`, which should always resolve to `http://localhost:433/`. Unless you run ASF on `localhost:443`, it will explicitly not work.

Ok i understand.
Well, i have 2 instance of ASF running under my domain in linux, i tried many configuration to get logs to work for both, but no help! the default config does not support it either. I am talking about listening to 443 ssl, and using different port and paths for it.

```
location ~* /Api/NLog {
  proxy_http_version 1.1;
  proxy_set_header Connection "Upgrade";
  proxy_set_header Upgrade $http_upgrade;
  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_set_header X-Forwarded-Host $host:$server_port;
  proxy_set_header X-Forwarded-Proto $scheme;
  proxy_set_header X-Forwarded-Server $host;
  proxy_set_header X-Real-IP $remote_addr;

  proxy_pass http://asf.domain:IP1;
}
```
