### ISSUE TITLE
Addition of a 'Status' page?

### ISSUE THREAD

**Issue by JRDK92** [JustArchiNET/ASF-ui#1699]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

Simple enhancement idea: addition of a 'Status' page to the UI. Example below. It would be neat to have a status page that shows current status like a splash screen. Only way currently I've found is to open the command prompt window:

![image](https://github.com/user-attachments/assets/8b7ac3e0-62ee-4ea1-96e7-b72d02d617df)

### Solution

This isn't as elegant, of course. Wondering if there's a way to do a simple splash/status screen that has some basics? Example below. Run time, games we're farming, estimated time until 

![image](https://github.com/user-attachments/assets/83f6ad14-6ee9-4502-a554-10214fbb41bd)

### Why currently available solutions are not sufficient?

No status page I've found thus far. 

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by Aareksio** [comment]
Hey! Isn't the `bots` page serving similar purpose right now? I understand you would want some sort of home screen with pretty stats. This seems fairly easy to implement, mostly visual task. With majority of the work to be done in UI design, not logic. I think the team would be happy to go forward with such idea, but at the same time I do not recall anyone having strong UI skills or will to do visual UI work.

If you want to push the idea forward, a sketch mapping the information we could provide on such screen will do wonders. Below I attach some (pretty random) examples of what may actually be useful and requires virtually no skills, only good will to create. https://tldraw.com was used to create these in particular.

![image](https://github.com/user-attachments/assets/dcb037bc-f80f-4bdd-bc7f-ca783e3f8a7b)

We need general page layout + detailed take on each component. Once project is sketched, assuming it meets the expected quality, picking up the task will be much easier for maintainers or anyone interested really.

**Comment by MrBurrBurr** [comment]
The `bots` page does include everything you mentioned: "Run time, games we're farming, estimated time until".
