### ISSUE TITLE
Keep log at fixed height

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#1700]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

When opening Log page it shows last 20 lines.
![image](https://github.com/user-attachments/assets/12fa5c4c-2211-484e-ad6b-9acf6270bfdb)

But if leaving Log page opened, lines go to the bottom of the page and it becomes inconvenient to read log.
![image](https://github.com/user-attachments/assets/8e3bdc41-ced1-4b86-b1ce-ee7dc18d13b8)

### Solution

New ui setting which I don't know how to name (give your suggestions in comments) to optionally keep log at 20 lines always.

**Comment by Aareksio** [comment]
I'll do it for $1,250
