### ISSUE TITLE
Accept login from UI

### ISSUE THREAD

**Issue by Switchbot-Nova** [JustArchiNET/ASF-ui#1701]
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

After creating a new bot you have to go in the commandline and press Y after accepting in steam authenticator. However, when running in headless or through docker or a systemd service, its not as easy to just go into the shell and press Y.

### Solution

An option after creating the bot or when needing to be logged in to confirm in the UI

### Why currently available solutions are not sufficient?

The functionality doesnt exist yet afaik

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

**Comment by MrBurrBurr** [comment]
I do not understand what your issue is. After creating a new bot you can just start it from within the UI. If you need to provide auth for that bot it will stop and you can start it again, then there should be a window where you can provide said auth-info.

Let me know if that fixes your issue or if I misunderstood what you are trying to achieve.

**Comment by Switchbot-Nova** [comment]
I forgot to enable headless mode so the window wasnt showing, my bad
