### ISSUE TITLE
Hide farming info if no bot is currently farming

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#174]
![20 02 06](https://user-images.githubusercontent.com/31552675/48575227-a9f63180-e911-11e8-8da6-0a125b883e28.png)

**Comment by Aareksio** [comment]
Let's make the interface shake more... 🤔

**Comment by MrBurrBurr** [comment]
Yes you are right, maybe we should add transitions?

I just think its not good to display farming info if we are not farming. This would be false information.

**Comment by Aareksio** [comment]
How is it false when it says `value: 0`?
I don't like the idea of hiding info components from the user, the navigation is not a place for personally tailored informations.

**Comment by MrBurrBurr** [comment]
In my case it says `value: 8` and thats false/outdated/deprecated information since all bots are disabled.
If it would show `value: 0` instead I think its not necessary to show at all since this should be obvious (if no bots are farming there cant be cards).

Or did I miss something?

**Comment by Aareksio** [comment]
Then we should fix it instead of removing from display, rito?

**Comment by MrBurrBurr** [comment]
I still think its not necessary to display at all if no bots are farming. If you want to we can make it optional and add it to UI Configuration.
