### ISSUE TITLE
Add secondary "SteamTradeToken" 

### ISSUE THREAD

**Issue by MalvoTheReal** [JustArchiNET/ASF-ui#177]
I think that will be really useful to have in our .json config files 1 more line for secondary steam trade token, which will not depend from Master. For example I've got in situation when I needed to put 1 unique steam trade token to each of my bot, that means each bot has his own "storage" bot or his own trade destination.
And i find it not possible to do because it requires that "SteamUserPermissions" has been seted on 3 for steam id which trade token i am using.

**Comment by MalvoTheReal** [comment]
So like we have 2 lines:
"SteamTradeToken": "here is trade token of my Master account"
"SteamTradeUrl": "here is trade URL of the storage bot"

**Comment by MrBurrBurr** [comment]
This has nothing to do with ASF-ui.
