### ISSUE TITLE
Fix autocomplete for every OS

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#18]
Find a consistent solution for properly displaying autocomplete on every OS

**Comment by Aareksio** [comment]
Is it still broken? How?

**Comment by MrBurrBurr** [comment]
I will have to check again and will report back.

**Comment by MrBurrBurr** [comment]
![bildschirmfoto 2018-10-16 um 17 01 16](https://user-images.githubusercontent.com/31552675/47026177-25bf5b80-d165-11e8-9b12-7621e6c19054.png)

This screenshot was taken on macOS. Autocomplete is not aligned properly.

**Comment by Aareksio** [comment]
Buy me a macbook and I'll fix 🤔

**Comment by MrBurrBurr** [comment]
No problem! Just send me $2000 on my PayPal and I will buy you a MacBook.

**Comment by MrBurrBurr** [comment]
Could [this](https://www.browserstack.com/) help you?
