### ISSUE TITLE
Improve `bot-games` layout for single game

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#182]
The game banner should be centered if bot is only farming one game. Looks better IMHO.

![ugly](https://user-images.githubusercontent.com/31552675/48667863-79182700-eae0-11e8-96ef-c3d43de2f8b0.png)
![better](https://user-images.githubusercontent.com/31552675/48667865-7ddcdb00-eae0-11e8-9626-24734ee87cd6.png)

**Comment by Aareksio** [comment]
`grid-column: 1 / -1;` to keep aspect ratio

I find it quite ugly though:
![ugly...](https://yko.im/jsz3.png)

**Comment by MrBurrBurr** [comment]
If we keep the aspect ratio it looks terrible. I will do some research if we have any other game banners available.

**Comment by MrBurrBurr** [comment]
This issue will be closed for now because I was the only one requesting it and it's not really needed. It's definitely a nice2have and maybe something for the future. We can always reopen this issue if needed.
