### ISSUE TITLE
Implement selectable "Quick Action Buttons"

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#184]
# Current situation
Each bot has the following quick action buttons:

**Bot card**:
- Resume/Pause
- Start/Stop

![04 27 02](https://user-images.githubusercontent.com/31552675/48668304-4541ff00-eaea-11e8-8652-a2237705523f.png)

**Bot modal**:
- Configuration
- BGR
- Resume/Pause
- Start/Stop
- Delete

![04 27 09](https://user-images.githubusercontent.com/31552675/48668306-4d01a380-eaea-11e8-8a21-e8ef8eea3c0c.png)

# How it should be
With more bot actions being implemented in the future it will be a hassle to display all those icons nicely and in a user friendly way. Instead, user should be able to select his favorite quick action buttons for each bot.

**Bot card**:
On bot card it should be possible to select up to 3 (maybe 4?) favorite quick action buttons. Default selected action buttons should be current ones.

Example:
![48418796-47613200-e767-11e8-829d-d77f805fd212](https://user-images.githubusercontent.com/31552675/48668301-1c216e80-eaea-11e8-9e06-af28888c7fc1.png)

**Bot modal**:
Here it should be possible to select up 10 (maybe only 6-8 if we make those buttons bigger) favorite quick action buttons. Also here should be a drop down containing all bot action buttons.

Example:
![sxrm](https://user-images.githubusercontent.com/31552675/48668338-327bfa00-eaeb-11e8-8aae-ff879c88789e.png)

### How to select favorite quick action buttons:
It should be possible to select favorite quick action buttons for bot card and bot modal from within the dropdown in bot modal. How exactly we want to achieve this is yet to be solved.

**Comment by Aareksio** [comment]
> How exactly we want to achieve this is yet to be solved.

> [5:12 PM] Mole: Install firefox if you want customization :doubt:

**Comment by MrBurrBurr** [comment]
This issue will be closed for now because I was the only one requesting it and it's not really needed. It's definitely a nice2have and maybe something for the future. We can always reopen this issue if needed.
