### ISSUE TITLE
Implement NLog layout

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#19]

**Comment by Aareksio** [comment]
🤔 
Done

**Comment by MrBurrBurr** [comment]
Good, now that you thought about how to implement NLog layout we can rename this issue and keep it.

**Comment by Aareksio** [comment]
https://yko.im/C0zw.png Done. The output is up to the user from what I know, no way we're gonna parse it any further.

**Comment by MrBurrBurr** [comment]
Layout can be changed within ASF code. Archi mentioned that we can add HTML to api output. We have to think about how we want the output to look.

**Comment by MrBurrBurr** [comment]
My suggestion would be to add colors similar to ASF console.

**Comment by Aareksio** [comment]
How can you decide what color should a message be?

**Comment by MrBurrBurr** [comment]
To be honest I cant remember, it was to long ago.

But it should be possible, otherwise I wouldnt had added it to the list back in the days.

We should ask Archi for an explanation again.

**Comment by MrBurrBurr** [comment]
We really need @JustArchi here to elaborate our options.
