### ISSUE TITLE
Force refresh/reload of the ASF-ui after successful update

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#195]
It's entirely possible that old code will try to request chunks or other assets that no longer exist in the ASF code. This will lead to broken functionality such as `404` errors that given chunks do not exist, rendering lazy-loaded features unavailable. The solution is to force refresh of the ASF-ui in this case.

**This should be implemented as passive check in background against `Version` of `/Api/ASF`** - ASF could decide to update itself in the background without user's action as well, with user's tab still being opened. IIRC there is already a code that periodically checks that, so it should be trivially easy to cache `Version` and compare it with the response.

Right now the only solution that works is clear of cache + force refresh.

**Comment by JustArchi** [comment]
![image](https://user-images.githubusercontent.com/1069029/50045840-61f63600-009a-11e9-962f-b1ef825ef784.png)

Would be cool if we could handle it rather sooner than later 🤔

**Comment by JustArchi** [comment]
Before I forget:

@Aareksio suggested doing it with `?ver=A.B.C.D` sent to all chunks that we can't change name-wise. I don't know for sure how ASF-ui is initialized right now, but I think of something like that:

- On the front there should be some barebones `init.js` that **will never change** code-wise. It'll have a very simple job of bootstrapping proper `main.bundle.js`.
- If there is (local) cached `version`, it'll use it and add `?version=A.B.C.D` to `main.bundle.js`.
- If there is no local cached version, it'll just call `main.bundle.js` without argument.
- `main.bundle.js` will ask for `Version` returned by `/Api/ASF` at some point during later execution
- Once that happens, it'll compare locally cached `version` to that `Version` and update it.
- If the `Version` does not match `version` that was cached before, force reload, either by starting again from `init.js`, or by somehow re-executing `main.bundle.js` with that `?version` added, this will force browser cache reload and fetch up-to-date content.

Once above is implemented (in this or similar way), decide whether it makes sense to use the same approach for other chunks instead of current (and already working) hashing of them. In this case both approaches will work, so it doesn't matter what we stick with.

**Comment by Aareksio** [comment]
Currently solved by forcing cache refresh:
a) when the app fails to load page chunk
b) after update executed from UI

Note this will not refresh cache when the update is executed via ASF and the user doesn't navigate to changed page, which may lead to errors loading other (logic, utility) chunks that are not directly bound to any page.

One additional drawback of current strategy is that we cannot **both** force refresh the cache and navigate to other page, so after clicking navigation link, the user will stay on the same page.

I'm looking into webpack code to figure out whether hooking to "chunk failed to load" event is possible as well as automatic navigation after force refresh.
