### ISSUE TITLE
Request Failed After 5 attempts!

### ISSUE THREAD

**Issue by tiagofabrica** [JustArchiNET/ASF-ui#197]
After the last update my ASF can't get the information from the badges page.

https://i.imgur.com/Ni6xkbJ.png

**Comment by Abrynos** [comment]
Hey there! Thank you for contacting our development team at GitHub.

First and foremost we believe that you did post this issue in the wrong repository as this one here is only for our graphical user interface called ASF-ui and not ASF itself.

Aside from that we also believe that your issue does not meet our [contributing guidelines](https://github.com/JustArchiNET/ArchiSteamFarm/blob/master/.github/CONTRIBUTING.md) referenced during issue creation  (in the correct repository).
> Before you open an issue please review the contributing guidelines for this repository. (...)
I understand that if my issue is not meeting contributing guidelines specified above, especially if it's a question or technical issue that is not related to ASF development in any way, then it will be closed and left unanswered.

The "problem" you encountered is not a bug, which you would know if you read our [FAQ](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/FAQ#what-is-the-difference-between-a-warning-and-an-error-in-the-log)

> General ASF rule is that warnings are not errors, therefore they should not be reported

Please check [our wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki) if you need further help.

Have a nice day!
~Abrynos

**Comment by MrBurrBurr** [comment]
This has nothing to do with ASF-ui.
