### ISSUE TITLE
Enhance help command

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#20]
Add available types/modes/settings to help text for help command

Example:
lets say you cant remember what a certain command is called but you  know it exists. so you write commands. you get a nice list of all available commands. you found the command you were looking for. now you want to know what it does because you forgot. so you call help <Command>. you get wiki description of what that command does. now you see in auto complete that this command accepts <Settings> but you cant remember which settings are available. my idea was to add those settings in some way.
![bildschirmfoto 2018-10-16 um 17 05 21](https://user-images.githubusercontent.com/31552675/47026944-cf531c80-d166-11e8-9496-9ad06a0df0c7.png)

**Comment by Aareksio** [comment]
We need better wiki schema for this

**Comment by MrBurrBurr** [comment]
Then we should ask Archi if he can improve it. Or did we already do that? If so what was his answer?
