### ISSUE TITLE
http status code only checked on initial load

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#200]
like the title says: error codes like 502 - Gateway Time-out are only checked during initial load. if they happen after that the "console" will only tell us `Error: undefined`

you can reproduce this by putting ASF behind a reverse proxy (I'm using nginx), setting InventoryLimiterDelay to 1000 and then sending the command `loot asf` to your instance with at least 2 or 3 bots viable for the command. nginx will then at some point send you a 502 and ASF-ui will not handle it correctly.

![image](https://user-images.githubusercontent.com/6608231/49887844-adf86f00-fe3d-11e8-9f69-e9006ef60f9d.png)

**Comment by Aareksio** [comment]
<img width="186" alt="screen shot 2019-01-04 at 12 49 20" src="https://user-images.githubusercontent.com/11166786/50686848-3625fa80-101f-11e9-9d24-7b527228dab2.png">

Cannot reporduce with latest release - possibly already fixed.
