### ISSUE TITLE
Improve layout for config-editor

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#22]
We dont want [this](https://yko.im/ycLK.png)

**Comment by Aareksio** [comment]
Use boxed layout

**Comment by MrBurrBurr** [comment]
This will work but is not very satisfiying.

**Comment by Aareksio** [comment]
It looks fairly decent on screens up to 1440p, bigger screens users are already used to seeing such abominations, as most sites layouts are not planned for such (or even bigger) resolutions.

We could force boxed layout (perhaps wider than 1250px) on 1440p+, or alternatively make it default if user opens page on such screen for the first time (first ever load).

![Github on 4k](https://yko.im/ig4E.png)

**Comment by MrBurrBurr** [comment]
I like your idea about making boxed layout default on big screens. We shouldnt force it.
