### ISSUE TITLE
Cache `SteamID` for bots

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#23]
Cache `steamId` (similar to `avatarHash`) so we can link profile when bot is offline

**Comment by Aareksio** [comment]
That's up to Archi

**Comment by MrBurrBurr** [comment]
How is that?

Once the bot goes online we have the bots steamID and then we can cache it.

Or did I miss something?

**Comment by Aareksio** [comment]
Actually, it should be already implemented
![Archi explains](https://yko.im/32g-.png)

**Comment by MrBurrBurr** [comment]
I just checked it and you are right.
