### ISSUE TITLE
Make statistics clickable

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#248]
# Feature request

I'd like to request, that when clicking on one of the 4 buttons (Farming, Online, Offline, Disabled) one should be redirected to bots page filtering it by the button one clicked on. So if i click on Farming i only want to see bots that are currently farming

![image](https://user-images.githubusercontent.com/6608231/50382722-3c72b900-06a6-11e9-817c-bef561909520.png)

**Comment by MrBurrBurr** [comment]
[Related](https://github.com/JustArchiNET/ASF-ui/issues/206#issuecomment-447656907)
