### ISSUE TITLE
Add config-generator

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#29]

**Comment by Aareksio** [comment]
Explain?

**Comment by MrBurrBurr** [comment]
Explain what?

In old UI we had the option to generate a config file and download it. This feature is missing.

**Comment by Aareksio** [comment]
Why do you need such option, as the config is directly fed to ASF - there's no need to play with files

**Comment by MrBurrBurr** [comment]
Why should we remove a feature that users are used to have?

I sometimes generate a config file for testing purposes if I dont remember config property names etc.

**Comment by Aareksio** [comment]
Fine
