### ISSUE TITLE
Accessible ready to use version of ASF-ui.

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#290]
Hello, dear ASF-ui developers!

Some issues, like this one https://github.com/JustArchiNET/ASF-ui/issues/165, when they are closed, make some users want to give it a try right away, so friendly version of ASF-ui for end users will be much appreciated for download from this Repo.

Please consider this.

Thanks!

**Comment by JustArchi** [comment]
I can take care of that and add proper routines to CI if @Aareksio decides he wants them.

**Comment by Botan626** [comment]
Archi,

I have no idea what CI is, but applying routines to them is the only solution to make this happen and Aareksio may not want them?

**Comment by Aareksio** [comment]
I was thinking about this for some time now. @JustArchi, if that's not a problem, could you configure CI? 

While on it, could you check whether adding CodeClimate here is possible for free? [It's said to be free for open-source](https://codeclimate.com/quality/pricing/) but I saw only paid option on GH Marketplace.
