### ISSUE TITLE
Game banners rendered too big on mobile

### ISSUE THREAD

**Issue by guixxx** [JustArchiNET/ASF-ui#297]
I think two banners per row would look good

![screenshot_20190123-230707](https://user-images.githubusercontent.com/27077338/51725600-4e030400-204a-11e9-93df-356fd5e8cfb4.png)

**Comment by Aareksio** [comment]
We could do a round of mobile optimization all over the interface

**Comment by MrBurrBurr** [comment]
> We could do a round of mobile optimization all over the interface

Let's do it.

**Comment by Aareksio** [comment]
Go ahead 😉
