### ISSUE TITLE
Show 2FA button in a bot card

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#330]
![image](https://user-images.githubusercontent.com/28785698/52057921-5d68dc80-2577-11e9-9cbf-9ad5792931da.png)

Among all these buttons under status 2FA lock button is used much more often than other ones, so moving it to the main bot card will make ASF-ui even more convenient.

![image](https://user-images.githubusercontent.com/28785698/52057895-4de99380-2577-11e9-964c-5739c3c8e1b3.png)

**Comment by Aareksio** [comment]
Is it?

**Comment by Botan626** [comment]
yep

**Comment by Botan626** [comment]
Less mouse clicks to confirm trades.

**Comment by Botan626** [comment]
Or copying tokens for bots when logging in onto account in browser etc.

**Comment by Botan626** [comment]
@JustArchi 
https://github.com/JustArchiNET/ASF-ui/issues/165

This issue destroyed the project for e.g.?

**Comment by Botan626** [comment]
or this one: https://github.com/JustArchiNET/ASF-ui/issues/290

maybe this one https://github.com/JustArchiNET/ASF-ui/issues/106

?
