### ISSUE TITLE
Context menu with copy option in Commands window

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#336]
Currently we need to right click with mouse exactly on the cursor in Commands window to paste the text.

Would be very convenient if that would be possible by right clicking with mouse in any place in Commands window.

**Comment by MrBurrBurr** [comment]
I don't know any way to make this possible that is not hacky. Maybe @Aareksio knows more but I think this issue is to irrelevant to implement hacky solution.

**Comment by Aareksio** [comment]
`@contextmenu` -> `input.select()` -> `executeCommand('paste')`

No opinion on whether we need this or not otherwise.
