### ISSUE TITLE
Remove 2FA modal for bots not having it enabled in ASF

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#342]
If a bot does not have his 2FA imported in ASF, the Modal (and the button to open it up) are still shown. The token from the response however is null and thus nothing is displayed. When trying to accept or cancel trades via those buttons the appropriate error message is shown but when clicking "Refresh token" it says "Success" and "Token refreshed". I suggest removing the modal for bots that do not have ASF 2FA set up completely

**Comment by MrBurrBurr** [comment]
> I suggest removing the modal for bots that do not have ASF 2FA set up completely

AFAIK the only way of checking if a bot has ASF 2FA set up or not is by sending 2FA related command and watch the error message.

I will take a look at why the message shows success even if the token is `null`

**Comment by Abrynos** [comment]
I don't know of any flag either, so it's either sending a request to the API or (even better) ask @JustArchi to add JsonPropertyAttribute to `HasMobileAuthenticator` (the Bot class in ASF has that property already).

**Comment by MrBurrBurr** [comment]
I don't see a reason why the 2FA modal/button should be removed if the bot doesn't have ASF 2FA enabled. If user wants to accept trades or fetch token on a bot that hasn't set up ASF 2FA he won't be able to and get proper error message.
