### ISSUE TITLE
Inconsistency when closing modals

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#343]
If one uses a quick-access-button (e.g. 2FA) and then closes the modal neither by clicking on the little "x" or pressing escape but by clicking on the background that's darkened out when having the modal open, the bot overview opens in a modal instead of closing it completely like it does when closing it the other way.

**Comment by MrBurrBurr** [comment]
Already fixed in 850c6111d3c7333300573a6ef77be8307edf4c5d
