### ISSUE TITLE
[FeatureRequest] Add Service Worker and Manifest

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#344]
I'd like to request a [service worker](https://www.w3.org/TR/service-workers-1/) and a [manifest](https://www.w3.org/TR/appmanifest/) to improve the app on mobile devices. Especially the Manifest would be nice as it allows for a "Add to homescreen" action on mobile devices and allows the app to go fullscreen by hiding the address bar on those devices.

**Comment by MrBurrBurr** [comment]
What do you expect the service worker to do?

**Comment by MrBurrBurr** [comment]
I think we should close this issue since its to generic and (if you want to you can) open more specific issue like "Send push notification over service worker if update is available". Also the manifest part got already taken care of.
