### ISSUE TITLE
Make URLs to popups work again

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#348]
Previously I had a very nice URL of `/page/bot/archi/bgr` that worked properly, it no longer does with the latest commit, and this is a regression compared to previous version in which it worked properly.

**Comment by MrBurrBurr** [comment]
#333

**Comment by Botan626** [comment]
I build master branch with the latest a7b6589 commit, single URLs, if bookmarked for e.g., work.
