### ISSUE TITLE
Make ASF-ui to work properly with small width

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#352]
For the first two cases ASF-ui could show only 1 bot card in a row:

https://i.imgur.com/MQtqAqg.png

https://i.imgur.com/5TZ9AKb.png

The cursor is not visible in Commands window:

https://i.imgur.com/SVTdrxb.png

Same for other windows.

**Comment by Aareksio** [comment]
Click the hamburger menu (so called trzy pierdolniki) 🤔
