### ISSUE TITLE
Config values missing when downloading config file

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#36]
Steps to reproduce:
- Click on `New bot`-Button
- Add a `Name`
- Change `BotBehaviour` to `All`
- Download config file

Open downloaded file and search for `BotBehaviour`.

**Comment by Aareksio** [comment]
Cannot reproduce. You need to "add" intended behaviour to the list.
![Proof](https://yko.im/-HGz.png)

**Comment by MrBurrBurr** [comment]
You are right, my fault. Sorry!
