### ISSUE TITLE
Replace `s_*` properties with original name when downloading config file

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#37]
Steps to reproduce:
- Go to `Global Config`
- Enter steamID into `SteamOwnerID`
- Download config file

In the config file it will now show `"s_SteamOwnerID":"12312313123123123"`
It should show `"SteamOwnerID":12312313123123123`

**Comment by Aareksio** [comment]
I think the complexity overweights the benefits. It is not possible to treat ulongs as numbers in JS without external support.

It might be possible to do but it may be prone to bugs...
```JS
const sPropertyRegex = /"s_(\w+)":\s*"(\d+)"/g;
const fixedConfig = config.replace(sPropertyRegex, '"$1":$2');
```

**Comment by JustArchi** [comment]
I have no clue why you added yourself work and in such hacky way removed original property if ASF is able to read and handle both, even at the same time.
