### ISSUE TITLE
[help wanted] production environment && compressed static file

### ISSUE THREAD

**Issue by hldh214** [JustArchiNET/ASF-ui#398]
Hello everyone, first apologize my poor english

im beginner in node/npm and i have a question about deploy on production env

first i know we can use `npm start` which refers to `webpack-dev-server --hot --open --env development`
however in development env the js/css file wasnt compressed and maybe a very huge file
then i tried to use `webpack-dev-server --env production` command but it doesnt work
it got stuck in `Compiling...` promot and stuck until out-of-memory
so i am asking if there is any way to build in production env with compressed static file?

please let me know if i have any misunderstand or mistake, Thanks <3

**Comment by MrBurrBurr** [comment]
This has nothing to do with development of ASF-ui.

**Comment by Aareksio** [comment]
You can use `npm run build` to build production-ready files.

**Comment by hldh214** [comment]
thanks for help
with npm run build indeed generate files i want
but how can i make this serve just like npm start do
i mean, create a server, listening on 8080 port etc...

在 2019年2月13日星期三，Arkadiusz Sygulski <notifications@github.com> 写道：

**Comment by JustArchi** [comment]
@MrBurrBurr Mole explicitly said to handle **all** questions/issues related to ASF-ui on GitHub, so do not use ASF's "only for development" attitude without providing another support channel.

**Comment by Aareksio** [comment]
@hldh214 
What you need is a web server software to serve the static files. We do not provide one as a part of ASF-ui.

The default method of serving the application si through ASF's `www` directory, you can read more on the [ASF wiki article](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#usage). You can also use any other software like nginx or apache. For node, there's a package [serve](https://www.npmjs.com/package/serve), which, as name suggests, serves static files from selected directory, though I wouldn't recommend using it for production environment.

@MrBurrBurr @JustArchi 
As Archi noted, I indeed chosen GH issues as the only formal communication channel. These issues happen so rarely, the overhead of maintaining separate place for such inquiries isn't justified. 

That said, I don't like how the last part suggests we're obligated to answer questions, especially these only loosely related to the application, like this one.

With the addition of issue templates not long ago, I suggest adding one for questions to make the syntax strict, precisely to extract the objective, prior efforts / observations and possibly environment.

**Comment by JustArchi** [comment]
It's fine to consider the question out of the scope of the project, it's not appropriate to consider the question as "nothing to do with ASF-ui development",  which I referred to.

**Comment by MrBurrBurr** [comment]
@JustArchi What's wrong about labeling this issue as invalid? What does a question about npm/node has to do with development of ASF-ui?

**Comment by JustArchi** [comment]
You still don't understand that issues that have **nothing to do with development of ASF-ui** can be valid. Did you read what @Aareksio said above?

**Comment by hldh214** [comment]
@Aareksio
solved, lessons learned
thanks again <3
