### ISSUE TITLE
Add scale support

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#40]
With 125% page zoom browser setting the ASF UI tab becomes cropped.

https://i.imgur.com/6qiB3xL.png

**Comment by Aareksio** [comment]
Stop using zoom, np

**Comment by Aareksio** [comment]
Fixed for up to 175% zoom on fhd screens, I recommend getting glasses instead of zooming, though.

**Comment by Botan626** [comment]
It was a 15.6" notebook's Full HD screen, 125% scale in Windows 10 settings + 125% page zoom in Chrome.

The screen was almost 1.5 meters from my eyes already using glasses.
