### ISSUE TITLE
Improve bot card's layout

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#402]
![image](https://user-images.githubusercontent.com/28785698/52780468-41773780-305b-11e9-9916-1bb9aa9377ca.png)

When 3 favorite buttons are selected, it's really hard to read Bots page.

The buttons have too big size comparing with other objects, too big distance between themselves, they are placed on the foreground all at a time, it's hard to find and focus on a specific icon.

![image](https://user-images.githubusercontent.com/28785698/52781046-a8e1b700-305c-11e9-8e02-a7b0405f3f00.png)

In my case, for e.g., I have enough place to place 4 overall buttons on the right side of the bot's card.

It would be nice, if it was possible to manually resize bot's card by holding and dragging card's border to the desired size, after this is done, ASF-ui could memory the last change.
In case, if we don't want to see a special tool while moving mouse cursor over card's border every time, some kind of toggle which will enable such action could be invented.

**Comment by Botan626** [comment]
This is ugly:
![image](https://user-images.githubusercontent.com/28785698/52846122-d6406a80-3119-11e9-9035-ff116145290f.png)

**Comment by MrBurrBurr** [comment]
I am closing this issue for now due to inactivity.

**Comment by SENPAY98K** [comment]
I fully agree with him, that even looks bad/ugly..

**Comment by MrBurrBurr** [comment]
Feel free to suggest a good, maintainable and mobile-friendly solution. Just saying "it's ugly" won't fix anything 🤣

**Comment by SENPAY98K** [comment]
> Feel free to suggest a good, maintainable and mobile-friendly solution. Just saying "it's ugly" won't fix anything 🤣

If i were a developer i would fix it, sadly i am not :/

**Comment by Abrynos** [comment]
Suggesting a solution has nothing to do with being a developer. I am sure even you are able to draw a sketch on a piece of paper, take a picture of it and upload it here.

**Comment by Botan626** [comment]
> Suggesting a solution has nothing to do with being a developer. I am sure even you are able to draw a sketch on a piece of paper, take a picture of it and upload it here.

What good would any sketch do? While there's lots of space on bot's card, the buttons are placed there in an odd way when 3 or more buttons are selected in settings. See screenshots and look at the bot 07 card, there is only 3 buttons on it.

Could ASF-ui just put all buttons on the right end of a bot's card, like it does on the 1st screenshot?

<details>
  <summary>Screenshots</summary>
  
![image](https://user-images.githubusercontent.com/28785698/120894451-1399d080-c621-11eb-9333-720bd280cab9.png)
![image](https://user-images.githubusercontent.com/28785698/120894577-d3871d80-c621-11eb-922f-3a94770170b3.png)

</details>

**Comment by Abrynos** [comment]
> What good would any sketch do?

If you provide a sketch that looks like the layout on it make sense, any developer with time and motivation can implement what is shown and decide, whether it really improves user experience during testing. Besides: Sketching is a standard practice in GUI and UX development. For reference I'll link you a post about the importance of sketches. [CLICK ME!](https://www.secretstache.com/blog/importance-sketching-web-design/) If you want to read more, I am sure I can ask one of my professors to recommend some books on the matter.

**Comment by Botan626** [comment]
You really need a sketch **in this case** to visualize this:
![001](https://user-images.githubusercontent.com/28785698/120896026-48f5ec80-c628-11eb-8810-d04d379cabc1.png)
?
