### ISSUE TITLE
Footer is not visible on Changelog and Global Config pages initially

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#410]
https://i.imgur.com/1TltwOK.gif

**Comment by Aareksio** [comment]
You don't say.

**Comment by Botan626** [comment]
> You don't say.
Already said.

> Also, use the other layout mode (boxed thingy) and it'll be visible...
I don't want to.

**Comment by Aareksio** [comment]
> > You don't say.
>
> Already said.

[:thinking:](https://en.wiktionary.org/wiki/you_don%27t_say)

> > Also, use the other layout mode (boxed thingy) and it'll be visible...
>
> I don't want to.

Then do not expect the footer to stick to the bottom of your window. This is one of the differences of layout modes. I can compare your _issue_ to having a problem with salt not being sweet.
