### ISSUE TITLE
Improve BGR

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#44]
1. It should be possible to see content of `<Bot>.keys.unused` file and `<Bot>.keys.used` file.
2. It should be possible to copy keys from `<Bot>.keys.unused` file (that way you can add them to a different bot).
3. ~~It should be possible to delete `<Bot>.keys.unused` file and `<Bot>.keys.used` file independently from each other.~~ Edit: ["Not going to happen"](https://github.com/JustArchiNET/ArchiSteamFarm/issues/922)
4. After you clicked [confirm](https://yko.im/FPWY.PNG) you should get a feedback about how many keys were successfully added.

**Comment by Abrynos** [comment]
> It should be possible to delete `<Bot>.keys.unused` file and `<Bot>.keys.used` file independently from each other.

i wanted to implement it that way back when i did my PR for this feature but Archi explicitly requested me to change this as he felt that nobody would want to keep one while removing the other one. This is not possible with ASF-ui due to Api-restrictions as of now

> After you clicked confirm you should get a feedback about how many keys were successfully added.

This would have to be implemented by ASF-ui only as the Api endpoint does not return that information either.

other two should be quite easy :) if you convince archi that number 3 is a good idea i'm happy to send a PR for the backend. number 4 is out of scope for backend imho.

**Comment by JustArchi** [comment]
> This would have to be implemented by ASF-ui only as the Api endpoint does not return that information either.

That's false, POST api explicitly returns you those keys that were added successfully.

**Comment by Abrynos** [comment]
oh i just overlooked that the same object was used instead of a copy 😓 sry

**Comment by MrBurrBurr** [comment]
> i wanted to implement it that way back when i did my PR for this feature but Archi explicitly requested me to change this as he felt that nobody would want to keep one while removing the other one.

I did not know this. I thought that Mole just kept them together since it would be more convenient. Thank you for the clarification.

**Comment by Abrynos** [comment]
yeah. i keep them both nowadays because i normally just want to delete the unused ones which i then added to the next account xD but this means that i always  just have to copy a part of the file over and can't just do ctrl + a, ctrl + c to copy those i need 😜

**Comment by MrBurrBurr** [comment]
Whelp, I tried but "not going to happen".

**Comment by Abrynos** [comment]
no PR-ok either :(

**Comment by Aareksio** [comment]
1. Add a popup that'll open when you click on number of used / unused keys
2. You can see = you can copy
3. Blame Archi
4. Will do
