### ISSUE TITLE
Used/Unused keys not showing in BGR

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#45]
I added some keys to BGR. ASF [processed](https://yko.im/s8k1.PNG) the keys and [created](https://yko.im/fIti.PNG) `*.keys.used` file.

When I reopen BGR it [doesnt show](https://yko.im/B36c.PNG) the count for used/unused. I tried to restart Bot/ASF/Browser but that didnt help.

**Comment by MrBurrBurr** [comment]
I will do some research whats causing this and report back.

**Comment by Aareksio** [comment]
Probably loading (un)used keys is hooked to wrong lifecycle event. Gonna check.

**Comment by Aareksio** [comment]
It seem that `/api/bot/:bot/SuperLongName` takes a while to populate with newly added keys - nothing we can do.

**Comment by JustArchi** [comment]
Fixed in https://github.com/JustArchiNET/ArchiSteamFarm/commit/ecf69973e9e7c6169728d5b62a75e8a8324c4e0f
