### ISSUE TITLE
Even more visibility adjustment under darkmode

### ISSUE THREAD

**Issue by deluxghost** [JustArchiNET/ASF-ui#460]
//Well, sorry for send so many separate issues, just want a better version before next asf stable release

Here I found 2 more elements can increase visibility under darkmode:

1. any popup window
2. bool property switcher (the disabled button) and any selected flag
3. maybe also textboxes, but it's ok

These elements' border are hard to recognize.

![](https://i.imgur.com/Mh32Leq.png)

the window itself

![](https://i.imgur.com/lBhJUgK.png)

the "TradingCard" and the bool switcher

**Comment by MrBurrBurr** [comment]
![image](https://user-images.githubusercontent.com/31552675/53142997-6a855400-3596-11e9-8372-d4acf35cfa3c.png)

I think it looks okay. What would you suggest to improve?

**Comment by deluxghost** [comment]
if i have a bad screen and first time to asf-ui, maybe i wont think that flag is a clickable button

**Comment by MrBurrBurr** [comment]
How would you improve that?
![2](https://user-images.githubusercontent.com/31552675/53143652-3d867080-3599-11e9-8265-f0f2698ea451.png)

**Comment by deluxghost** [comment]
at least let these buttons a bit brighter, to clearly indicates "this is a button", the major problem is "cant recognize as button because cant see border clearly" rather than "i dont know this button is for deleting flag", so i think we dont need a small X

**Comment by MrBurrBurr** [comment]
So like this?

![3](https://user-images.githubusercontent.com/31552675/53144518-db2f6f00-359c-11e9-8c0c-aa0cbacc9b39.png)

**Comment by deluxghost** [comment]
I still like brighter (but still dark) background button solution, but if you don't like this, I prefer keep them unchanged

**Comment by MrBurrBurr** [comment]
I don't understand what you want.

You say:
> - these buttons a bit brighter (ofc still a dark color)
> - cant see border clearly

I do:
- Brighter
- Border

Now you say: 
> if you don't like this, I prefer keep them unchanged

I am a bit confused on what you actually want.

**Comment by deluxghost** [comment]
ok, i should say background...

so i took a photo:

![](https://i.imgur.com/h5FVI6V.jpg)

just like nothing has a background in my shit screen

**Comment by MrBurrBurr** [comment]
Okay now I understand. Could you provide some colors (hex or rgb) that are visible on your screen?

**Comment by deluxghost** [comment]
`#4f5454` looks good for me, under both light/dark mode

**Comment by MrBurrBurr** [comment]
Yeah looks good for me too, lets see what @Aareksio says.

![6 28 41](https://user-images.githubusercontent.com/31552675/53145822-0799ba00-35a2-11e9-9ca5-8f3663bebcfb.png)

**Comment by MrBurrBurr** [comment]
@deluxghost What about color for modal background?

**Comment by deluxghost** [comment]
any gray between `#333` and `#444` is ok for me

**Comment by MrBurrBurr** [comment]
Hm, thats too bright IMHO. Let's wait for @Aareksio's opinion on this.

**Comment by deluxghost** [comment]
then at least `#1c1c1c`

**Comment by MrBurrBurr** [comment]
Thats better, but still I want to wait for @Aareksio response.
