### ISSUE TITLE
Better visibility of the underscore character in terminal

### ISSUE THREAD

**Issue by guixxx** [JustArchiNET/ASF-ui#462]
## Description
Not sure if I'd call this a bug, maybe it's just a discrepancy between monospaced fonts among operating systems. Anyway, on my Ubuntu machine, when I type the underscore character <kbd>_</kbd> in the Commands page, they are not displayed until I hit enter to send the command.

## Steps to reproduce
1. Have some Linux distro
2. Go to the Commands page
3. Type the underscore character (<kbd>_</kbd>) and it won't be properly displayed

## Expected behavior
Better visibility of the <kbd>_</kbd> character on Linux.

## Current behavior
I can't see the <kbd>_</kbd> character on Linux unless I hit Enter.

## Screenshots
<details>
 <summary>Before sending a command with <kbd>_</kbd></summary>

![screenshot from 2019-02-20 22-02-34](https://user-images.githubusercontent.com/27077338/53147445-5afe0f00-3586-11e9-8090-3b2d90665f38.png)

</details>

<details>
 <summary>After sending a command with <kbd>_</kbd></summary>

![screenshot from 2019-02-20 22-02-52](https://user-images.githubusercontent.com/27077338/53147459-5fc2c300-3586-11e9-9ffc-7d73d5cd84a3.png)

</details>

<details>
 <summary>My (default) fonts settings</summary>

![screenshot from 2019-02-20 22-15-29](https://user-images.githubusercontent.com/27077338/53147678-0ad37c80-3587-11e9-8dac-808d57bcf14b.png)

</details>

**Comment by Abrynos** [comment]
![image](https://user-images.githubusercontent.com/6608231/53167924-a42b7e80-35d9-11e9-82c2-d65dbe1f7f7e.png)
not a linux specific issue. i tested it both on Linux and Windows 10.

![image](https://user-images.githubusercontent.com/6608231/53167954-b6a5b800-35d9-11e9-97cd-143dadd313a7.png)

using UI version 1.0.5

**Comment by Aareksio** [comment]
Probably related to line height and overflow. The underscore character may be _below_ letter baseline.

**Comment by deluxghost** [comment]
this issue happened to Safari on macOS Mojave

but Chrome on the same machine is ok

**Comment by Abrynos** [comment]
screenshots were taken from chrome.
