### ISSUE TITLE
Start setup if no bots or SteamOwnerID is detected

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#489]
We need to inform the user about missing SteamOwnerID.

**Comment by JustArchi** [comment]
There should also be an option to re-do the tour at any given point of time, probably somewhere in the settings.

Once the tour is complete, it should be saved in the cookies, while new tour automatically pops up if (and only if) the user has no tour finished in the cookies **and** no bots are defined.

**Comment by Abrynos** [comment]
cookies should not be used for this but local storage. cookies are sent to the server and ASF does neither use nor understand them.

**Comment by JustArchi** [comment]
Yes I meant local storage, my bad.
