### ISSUE TITLE
Add detailed farming info

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#49]
I don't know what you had in mind for [detailed view](https://github.com/JustArchiNET/ASF-ui/commit/270cc53b009621544620ae5bb7311a183d84be46#commitcomment-30605113) but maybe the modal bot view could be a good place for it.

We should search for a solution on how to place more farming related information inside bot modal.

**Comment by MrBurrBurr** [comment]
Maybe we could use marquee to fit all info inside the modal.

Or we could take the game banners from steam store and insert into a carousel.

What do you think about that?

**Comment by Aareksio** [comment]
If you have an idea on design, feel free to share / implement.

I don't think marquee is a good idea. Banners may be good, but need to fit.
