### ISSUE TITLE
Review "Automatic apply ESLint rules via CI"

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#498]
![1](https://user-images.githubusercontent.com/31552675/53523128-45d03580-3adc-11e9-90f8-50e53e6db409.PNG)

**Comment by JustArchi** [comment]
You could also decide upon which code violations should result in an error (`exit 1`) and which would just output a warning, so a person reviewing code/PR could look into CI and have a glimpse on whether the code is OK or not, and if not then why exactly.

If it's not intended to have code violations being reported as CI failures, it still makes sense to output them as CI warnings.

**Comment by MrBurrBurr** [comment]
@Aareksio Can this be done easily or should I just close this issue?

**Comment by MrBurrBurr** [comment]
I am closing this issue for now due to inactivity.
