### ISSUE TITLE
Quick action buttons

### ISSUE THREAD

**Issue by brecho** [JustArchiNET/ASF-ui#504]
When BGR button is selected as the only quick action button, one that is actually visible is 2FA button. Only after actually selecting 2FA button as the second one, both of them start being visible.

**Comment by Botan626** [comment]
Is ok for me:
![image](https://user-images.githubusercontent.com/28785698/53684020-296d0c80-3d19-11e9-8f97-28f8d5ba11b8.png)

Try clearing cache.

**Comment by MrBurrBurr** [comment]
Already fixed in https://github.com/JustArchiNET/ASF-ui/issues/415
