### ISSUE TITLE
Add newline delimiter for BGR

### ISSUE THREAD

**Issue by timmyfromspace** [JustArchiNET/ASF-ui#51]
If you copy keys from sites like Indiegala, Humble etc, it often looks like this:

Game1
ABCDE-EFGH-XYZ
Game2
ABCDE-EFGH-XYZ

As far as i know / tested the format has to be with a delimiter ("," for e.g.):

Game1,ABCDE-EFGH-XYZ
Game2,ABCDE-EFGH-XYZ

It would be handy, if this was possible:

Game1(\n)
ABCDE-EFGH-XYZ
Game2(\n)
ABCDE-EFGH-XYZ

Thank you.

**Comment by Abrynos** [comment]
you forget that it's not 
```
Game1\n
ABCDE-EFGHI-JKLMN
Game2\n
ABCDE-EFGHI-JKLMN
```
but rather 
```
Game1\n
ABCDE-EFGHI-JKLMN\n
Game2\n
ABCDE-EFGHI-JKLMN\n
```
as the lines with keys in them also end with `\n` and empty lines in between them also have a newline-delimiter. in addition to that on windows there will most likele by a return-carriage character as well.
