### ISSUE TITLE
Add Terminal shortcuts

### ISSUE THREAD

**Issue by Abrynos** [JustArchiNET/ASF-ui#517]
## Purpose
add shortcuts to commands page. I'm used to have certain shortcuts on a terminal. ctrl + a to jump to the beginning of the current line i'm typing... ctrl + k to remove everything at the current line that is after the cursor... ctrl + l to clear the whole terminal

## Solution
Add proposed keyboard shortcuts

## Alternatives
a userscript i have to install in all the browsers on all of my machines

## Additional information
no additional information needed

Thanks in advance for consideration
~Abrynos

**Comment by deluxghost** [comment]
readline with emacs binding, noice!

**Comment by MrBurrBurr** [comment]
I don't see a problem with adding such a feature, but I also don't want to be the one implementing it.
