### ISSUE TITLE
Unable to read logs when using reverse proxy.

### ISSUE THREAD

**Issue by Blake-Bill** [JustArchiNET/ASF-ui#534]
## Description
Unable to read logs when using reverse proxy.

## Expected behavior
Can read the log.

## Current behavior
Unable to read logs when using reverse proxy.

## Screenshots

![SharedScreenshot](https://user-images.githubusercontent.com/16754839/55273113-87cde080-5301-11e9-969a-6fde45c8ab89.jpg)

**Comment by Abrynos** [comment]
this is because the log is distributed over websocket. please add a reverse proxy for `/Api/NLog`. i'm not sure wheter the UI accesses it with lowercase letters or like this (which is what is defined on the backend). if you are using nginx this would probably look something like this:
```
location ~* /ASF/Api/NLog(?<stuff>.*)$ {
                rewrite ^ /Api/NLog$stuff break;
                proxy_pass http://127.0.0.1:1242;
                proxy_http_version 1.1;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Upgrade $http_upgrade;
        }``

**Comment by Blake-Bill** [comment]
Duplicate of #

> this is because the log is distributed over websocket. please add a reverse proxy for `/Api/NLog`. i'm not sure wheter the UI accesses it with lowercase letters or like this (which is what is defined on the backend). if you are using nginx this would probably look something like this:
> 
> ```
> location ~* /ASF/Api/NLog(?<stuff>.*)$ {
>                 rewrite ^ /Api/NLog$stuff break;
>                 proxy_pass http://127.0.0.1:1242;
>                 proxy_http_version 1.1;
>                 proxy_set_header Connection "Upgrade";
>                 proxy_set_header Upgrade $http_upgrade;
>         }``
> ```

Thanks! I rewrite the nginx's conf and the problem was solved!

**Comment by Aareksio** [comment]
I don't think nginx locations are case sensitive either

**Comment by Abrynos** [comment]
from the [documentation](http://nginx.org/en/docs/http/ngx_http_core_module.html): 

> A location can either be defined by a prefix string, or by a regular expression. Regular expressions are specified with the preceding “~*” modifier (for case-insensitive matching), or the “~” modifier (for case-sensitive matching).

so `~*` has to be used for case-insensitive matching

**Comment by Blake-Bill** [comment]
That's my website's config, I hope that can help others.
server
    {
        listen 80;
        listen [::]:80;
        server_name _yourhost_;
                return 301 https://$server_name$request_uri; 
        }
server
    {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;
        server_name _yourhost_;
        ssl on;
        ssl_certificate //_yourhost.cer_;   
        ssl_certificate_key //_yourhost.key_;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
        ssl_session_cache builtin:1000 shared:SSL:10m;
        ssl_dhparam /etc/ssl/certs/dhparam.pem;

    location ~* /Api/NLog {
        proxy_pass http://127.0.0.1:1242;
#       proxy_set_header Host 127.0.0.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_http_version 1.1;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Upgrade $http_upgrade;
    }

    location / {
        proxy_pass http://127.0.0.1:1242;
#       proxy_set_header Host 127.0.0.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

**Comment by Aareksio** [comment]
Adding an example config to README or at least linking to the wiki wouldn't hurt I guess.
