### ISSUE TITLE
ToDo-List and Ideas

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#6]
# High priority
- [BGR] Auto detect order of keys ([Suggestion](https://github.com/JustArchi/ArchiSteamFarm/issues/773#issuecomment-381519702))
  - Implement `GET /Api/GamesToRedeemInBackground/{BotName}`
  - Implement `DELETE /Api/GamesToRedeemInBackground/{Bot}`
- [Config] Add config generator/editor
  - Add drag&drop to config generator/editor to import existing json file for edit/bot creating
  - Add option to directly create new bot config via `POST /Api/Bot/{BotName}`
  - Add wiki parser for help text for config properties
  - Add link to wiki for descriptions of config properties
- [Global] Add localization
  - Add option to change language
- [Commands] Add available types/modes/settings to help text for help command
- [Commands] Add option to show timestamps in terminal
- [Bots] Add `bot-action` to delete bot
- [Home] Add confirmation prompt to `bot-action` buttons
- [Bots / Home / Statistics] Add farming infos ([example](https://yko.im/bse_.PNG) / [example2](https://i.imgur.com/BwRhL8k.jpg))

# Low priority
- [Config] Improve layout for config-editor ([Maybe use this?](https://github.com/yuanfux/vue-metro-tile))
- [Commands] Find a consistent solution for properly displaying autocomplete on every OS
- [Bots] Cache `steamId` (similar to `avatarHash`) so we can link profile when bot is offline
- [Global] Add loading symbol to indicate state of `bot-action` buttons
- [Bots] Add option to hide bots (hide idling, disabled and farming bots)
- [Side menu] Think about different toggle buttons
- [Log] Think about NLog layout
- [Setup] Add message for user when entering wrong IPC password
- [Side menu] Don't show/use `Boxed layout` when screen size < 1250px
- [Side menu] Add dark mode support for theme-switcher

## Ideas for Home
- Some kind of tour (driver.js as example) for first visit
- Some kind of 'Whats new?' feature
- Information about translation percentage and ways to contribute

## Check before releasing
1. Dark mode
2. Localization
3. Responsivity

**Comment by Yur0K** [comment]
Hi. I can't copy text from Command input field.

**Comment by Botan626** [comment]
Please add the information on total cards remaining to farm in the STATISTICS.

Something like this: https://i.imgur.com/BwRhL8k.jpg

**Comment by Aareksio** [comment]
@Yur0K Not from the input, butrather the terminal. It tries to imitate text terminal, which let's you type the command as long as the window is active. To do so, it'll focus HTML input on mouse click, removing your selection as side effect.

I'll try to _fix_ it.

**Comment by DeadSam** [comment]
_-  [Side menu] Think about different toggle buttons_

This could be simple < > icons instead of that three dashes

**Comment by DeadSam** [comment]
You could usa a little (?) icon here and put these info in a box that show when mouse hover over the icon.
http://prntscr.com/l5ay5s

**Comment by MrBurrBurr** [comment]
> Please add the information on total cards remaining to farm in the STATISTICS.
> 
> Something like this: https://i.imgur.com/BwRhL8k.jpg

Added to the list. Thank you.



> _- [Side menu] Think about different toggle buttons_
> 
> This could be simple < > icons instead of that three dashes

I dont know what you mean by this.



> You could usa a little (?) icon here and put these info in a box that show when mouse hover over the icon.
> http://prntscr.com/l5ay5s

This was the [initial idea](https://github.com/JustArchiNET/ASF-ui/commit/274a20c70323a5ef0b2dec50ecb40712b1c51c15#commitcomment-30606176) but @Aareksio had some problems implementing it.
