### ISSUE TITLE
Improve visible separation of config categories

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#601]
Just an idea.. maybe the border color is too much, let me know what you think.

<details>
<summary>Before</summary>

![2](https://user-images.githubusercontent.com/31552675/57986243-c0bd4280-7a72-11e9-8ad2-b59dceb7f297.png)
</details>
<details>
<summary>After</summary>

![1](https://user-images.githubusercontent.com/31552675/57986231-8c498680-7a72-11e9-9d41-1931f9c4cf86.png)
</details>

**Comment by JustArchi** [comment]
I like it.

**Comment by Aareksio** [comment]
I like it too ;)

**Comment by Abrynos** [comment]
I like it as well :)
