### ISSUE TITLE
Further improve getLocaleForHD.js

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#608]
![1](https://user-images.githubusercontent.com/31552675/58120598-dca51d80-7c05-11e9-8a75-b87b3dc4af2d.png)

**Comment by deluxghost** [comment]
new i18n string looks not good for me, i.e. translate `and` separately
my opinion is something like `Released {time} and {time} ago`, to support 2 units time (i don't think we need 3 units)
then also consider `Released just now` for very short time
and no matter how it shows, display ISO format time in hover tooltip

**Comment by MrBurrBurr** [comment]
I added the delimiter for the timeString because I thought it would look better this way, example:
```js
Released 1 day and 2 hours ago // with " and " as delimiter
Released 1 day, 2 hours ago // default delimiter
```

Now that I think about it I am not sure if it creates more problems for translators than it solves. I could imagine that in some languages the " and " makes no sense etc. I am not sure what the best approach would be here.. maybe split up the timeString at the comma and then use a translation string like this:
`Released {1} and {2} ago`, or would that be too much hassle for such a "not-important" feature? Should we just use the default delimiter and call it a day?
Maybe @Aareksio or @JustArchi could share their thoughts on this.

**Comment by Aareksio** [comment]
Internationalization is hard. Not only languages have different preferred format of relative time, but also the list formatting (`[A, B, C] => "A, B and C"`). I wouldn't bother with setting custom delimiter, as while in english it may sound better (I don't think it does), other languages may have, for example, different grammar cases for these depending on context - making it sound weird. A comma or blank space should be good enough.

If you want to improve it somehow, you can try experimenting with the new Intl apis available in recent versions of Firefox and Chrome - these should take care of all nuances related to different languages - just make sure to keep humianize-duration as fallback.

**Comment by deluxghost** [comment]
in chinese, i prefer a whitespace rather than comma 🤣 
~~yes hard i18n~~

**Comment by JustArchi** [comment]
The best idea that comes to my mind right now is to make use of ASF's humanizer and add API that would convert timespan into string.

Let me know what you think about that @MrBurrBurr.

Otherwise ask Mole and the rest of the translators. @deluxghost is a good person for that since chinese isn't west language (english and german are not good enough for comparison).

**Comment by deluxghost** [comment]
> The best idea that comes to my mind right now is to make use of ASF's humanizer and add API that would convert timespan into string.
> 
> Let me know what you think about that @MrBurrBurr.
> 
> Otherwise ask Mole and the rest of the translators. @deluxghost is a good person for that since chinese isn't west language (english and german are not good enough for comparison).

LGTM, just need new asf-ui to test

**Comment by MrBurrBurr** [comment]
Closed due to inactiviy, if we really need it again we will just open it again.
