### ISSUE TITLE
Add tooltip to clarify what each button does

### ISSUE THREAD

**Issue by woctezuma** [JustArchiNET/ASF-ui#631]
## Purpose
Clarify what each button does. Right now, one has to experiment and some icons are scary.

![buttons](https://i.imgur.com/GPRsvHM.png)

## Solution
Add a tooltip when the mouse hovers each button.

**Comment by woctezuma** [comment]
The first button is to edit the settings.
The second button is to redeem a key.
The fourth button is to pause/resume idling, I guess.

However, the third (lock?) and fifth button (shutdown?) are not clear.

**Comment by Aareksio** [comment]
Having the icons alone is definitely bad UX, labels, despite making it only a bit better, are great idea.
