### ISSUE TITLE
How to configure .....

### ISSUE THREAD

**Issue by hawkonyt** [JustArchiNET/ASF-ui#640]
## Question
Is it possible to let it run on my server? In tutorial it says localhost but i dont want to let it run on localhost

**Comment by Aareksio** [comment]
You can find an answer to your question on [ASF wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#can-i-use-asfs-ipc-behind-a-reverse-proxy-such-as-apache-or-nginx).
