### ISSUE TITLE
Add localization info

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#71]
When switching between languages a notification should pop up if the selected language is not fully translated. That way user can help translate his selected language.

Notification message could look something like this:

1. "Your selected language is missing some translations! You can learn [here](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Localization) about how to contribute."
2. "Only 40% of your selected language is translated! Learn [here](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Localization) how to help."
3. "12% of your selected language is missing a translation! Learn [here](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Localization) how to help."

**Comment by Aareksio** [comment]
How do we detect translation percent? `Translated strings / total strings`?

**Comment by MrBurrBurr** [comment]
Exactly
