### ISSUE TITLE
Link aliases to commands for auto-complete

### ISSUE THREAD

**Issue by guixxx** [JustArchiNET/ASF-ui#712]
## Purpose
Ease of use, I guess. I often use the `!redeem` command in its short form: `!r`. However, after I type `r<space>` and hit <kbd>Tab</kbd> in the Commands page, the command itself gets completely removed. It's reproducible when you type basically anything that is not a recognized ASF command.

## Solution
Make auto-completion work for command aliases, as well. Or, at least, don't remove everything I typed after I hit <kbd>Tab</kbd>.

## Alternatives
None, AFAIK.

## Additional information
These are the current command aliases, from the [Wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/Commands#notes):

![image](https://user-images.githubusercontent.com/27077338/63191268-77af6700-c03e-11e9-86d6-dcc141e7c41c.png)

**Comment by JustArchi** [comment]
Probably better and more user-friendly approach is to link aliases to commands internally, then make `oa<tab>` replace into `owns ASF` instead of sending `oa`.

**Comment by Aareksio** [comment]
It shouldn't delete the already typed characters, it's a bug if it does. I agree with Archi on _extending_ the aliases on tab.
