### ISSUE TITLE
Use flag as icon

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#72]
I think it would look better like this:
![10 15 51](https://user-images.githubusercontent.com/31552675/47485745-1021f400-d83f-11e8-8b7e-fc3160a36dee.png)

What do you think?

**Comment by Aareksio** [comment]
http://www.flagsarenotlanguages.com/blog/
Using flags alone is already a bad practice I'd like to change

**Comment by MrBurrBurr** [comment]
You learn something new every day I guess.

I think it would be a good idea to move `language-switcher` into side menu and instead of the dropdown with flags use a select box with flags and names.

What do you think about that?

**Comment by Aareksio** [comment]
Adding language names would introduce more complexity than it's worth. Moving language switch to hidden menu doesn't sound like the best idea either.

**Comment by MrBurrBurr** [comment]
Okay you are right about moving language switch.

What do you want to add instead of language names so you are not only using flags? Right now we have language code as title but that doesn't seem very user friendly. Any ideas?

**Comment by Aareksio** [comment]
We could replace the flags with a list with language names, but we do not have the names available as for now.

**Comment by MrBurrBurr** [comment]
Couldn't we just map language names to the matching language code? Or is there a better approach for doing that? I guess ideally we don't want to map anything manually.

**Comment by MrBurrBurr** [comment]
I could try to create one based on ISO 639.1 but I don't know if thats what we want.

**Comment by JustArchi** [comment]
**[DRY](https://www.npmjs.com/package/iso-639-1)**.
