### ISSUE TITLE
UI is broken

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#757]
After update to ASF v4.1.0.0 UI is broken.

1. Refreshing (including hard refreshing) of any opened UI page (e.g. http://127.0.0.1:1242/page/commands) leads to "This 127.0.0.1 page can’t be found" error.

http://127.0.0.1:1242 still opens UI
![image](https://user-images.githubusercontent.com/28785698/65754577-02918000-e11a-11e9-8d6e-a7e8ee50cf9b.png)

2. 
![image](https://user-images.githubusercontent.com/28785698/65754429-bd6d4e00-e119-11e9-98b8-3b26ce535cbb.png)

3.
![image](https://user-images.githubusercontent.com/28785698/65754453-c6f6b600-e119-11e9-900c-925c11b3b3c6.png)

4. Any of Configuration pages won't open at all.

**Comment by Aareksio** [comment]
Thanks for reporting, 
I'll check what can be done on UI part, some of these are caused by ASF upgrade to .net core 3.0. We should get it all sorted before stable release ;)

**Comment by Botan626** [comment]
This is ASF v4.1.0.1, look at the bottom right corner.
![image](https://user-images.githubusercontent.com/28785698/65795054-0bae3b80-e172-11e9-86d3-40cd1632bf1a.png)
