### ISSUE TITLE
Remove versioning

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#760]
![asf-ui](https://user-images.githubusercontent.com/31552675/65839962-d3922e80-e312-11e9-9993-69bd3ebaffbe.PNG)

Click on UI and get 404'ed - Also I don't see any point keeping versioning

**Comment by Botan626** [comment]
Because UI v1.0.9 is a bump version which was never released?

**Comment by guixxx** [comment]
I believe that's because they prefer to tag a new release at the beginning of the development, and not at the end (which is more common, I guess). I'd say there's nothing wrong with either approach, it's just a matter of preference.

**Comment by MrBurrBurr** [comment]
@Aareksio what do you think about removing versioning from asf-ui? Is there really a need for it?

**Comment by JustArchi** [comment]
Version in form of git commit from which the release was built is always good (you can pinpoint the bugs this way), strict versioning in form of X.Y.Z numbers is not necessary if the project doesn't need it. If I didn't have to release ASF, it wouldn't have a versioning either, but I need to release something - you don't need to, as ASF release does for you (for the most part).

**Comment by MrBurrBurr** [comment]
Good to hear, I'll take care of it.
