### ISSUE TITLE
Close Flags panel if Settings panel is opened too

### ISSUE THREAD

**Issue by Botan626** [JustArchiNET/ASF-ui#771]
And if they are opened in different order as well.

Look at this mess:

![image](https://user-images.githubusercontent.com/28785698/66257892-4bdf7080-e7a7-11e9-84be-ba922f0cf315.png)

**Comment by Aareksio** [comment]
I wouldn't consider it a bug. The fix is relatively easy, mount an event handler when the drawer is opened - PR welcomed!

**Comment by Botan626** [comment]
Well yeah not a bug, but a slight omission to be more precise.

Btw, while having both panels opened, I can still press on the button which changes ui color to yellow (the right one), and it will do it!
