### ISSUE TITLE
Add farming info to statistics

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#79]
[Example](https://i.imgur.com/BwRhL8k.jpg)
This was requested by @Botan626

**Comment by Abrynos** [comment]
i'd rather include it in the bots page instead of clustering it all over the already full sidebar

**Comment by Botan626** [comment]
How come Memory Usage and Uptime are more useful for a common ASF user than an overall farming statistics?

IMO total cards remaining to farm should be right in the Statistics section.

**Comment by MrBurrBurr** [comment]
Sounds good to me! 

The only thing I think we could improve in the future would be to add a switch to our yet-to-code ui configuration. Then user could decide for himself if he wants it hidden or not.

**Comment by Botan626** [comment]
@Aareksio 

In my [example](https://i.imgur.com/BwRhL8k.jpg) I cropped CONFIGURATION box and there was quite a lot of space left, no?

**Comment by Aareksio** [comment]
No.
