### ISSUE TITLE
Implement friendly 404 information

### ISSUE THREAD

**Issue by JustArchi** [JustArchiNET/ASF-ui#81]
Accessing any unknown URL renders `/index.html`, but ASF-ui currently displays just empty page instead of proper 404 message.

Not sure if we can change the response code, but there should at least be some output for the user.

**Comment by Aareksio** [comment]
Psst, friendly 404 page will still render `/index.html`, just with different content 🙂

**Comment by Aareksio** [comment]
Honestly I don't think we need one - in such small application it should be better to redirect the user to home instead, as we do currently.

**Comment by MrBurrBurr** [comment]
What about a notification like "404 - Page not found! Redirecting to home"

**Comment by Aareksio** [comment]
Maybe if we had better looking notifications :D

**Comment by MrBurrBurr** [comment]
What do you not like about the current ones?

**Comment by Aareksio** [comment]
This:
![this](https://yko.im/yzzn.png)

**Comment by MrBurrBurr** [comment]
Could you please explain what exactly you think is wrong with it?

**Comment by Aareksio** [comment]
It's ugly and doesn't match the rest of the UI

**Comment by MrBurrBurr** [comment]
We should still provide user with a response in some way.

**Comment by JustArchi** [comment]
> redirect the user to home instead, as we do currently.

@Aareksio you don't.

![image](https://user-images.githubusercontent.com/1069029/47742645-5fbc5180-dc7d-11e8-9450-4dac085ce97c.png)
