### ISSUE TITLE
Create bot based on existing one

### ISSUE THREAD

**Issue by MrBurrBurr** [JustArchiNET/ASF-ui#84]
It would be nice to have an option where you can create a bot based on an existing one.

**Comment by JustArchi** [comment]
I think it'd be better to define user-provided "config scheme" for a bot that ASF-ui could use. A good way to do it is adding a nice "save model" option, and another button "load model" during editing/creating the bot. User could have multiple models saved under different names at the same time.

**Comment by MrBurrBurr** [comment]
This issue will be closed for now because I was the only one requesting it and it's not really needed. It's   definitely a nice2have and maybe something for the future. We can always reopen this issue if needed.

**Comment by MrBurrBurr** [comment]
![06 52 35](https://user-images.githubusercontent.com/31552675/52930712-d6bf4800-3349-11e9-8d81-ae3c0d2974a7.png)
