### ISSUE TITLE
GitHub report 404 of latest version check

### ISSUE THREAD

**Issue by levelKro** [JustArchiNET/ASF-ui#859]
## Description
Problem with update url on the GitHub API.

## Steps to reproduce
Go to : https://api.github.com/repos/JustArchiNET/ASF-ui/releases/latest

## Expected behavior
ASF check for the latest version of ASF-ui.

## Current behavior
ASF return error about the url; https://api.github.com/repos/JustArchiNET/ASF-ui/releases/latest and ignore update config (disable or time)

## Screenshots
```
[15:05:13] WARN ASF > UrlGetToString() Request failed after 5 attempts!
[15:05:13] DEBUG ASF > UrlGetToString() Request failing: https://api.github.com/repos/JustArchiNET/ASF-ui/releases/latest
```

## Additional information
The url have correct syntax, but GitHub return a 404 error about this url. Is a API bug ? Latest release of ASF-ui is not available ? I just report this issue, is not really a bug, but need improvement.

**Comment by JustArchi** [comment]
I like how @MrBurrBurr decided to kill all ASF-ui releases without a second thought that current users might still be using it 😁

**Comment by MrBurrBurr** [comment]
My bad. Should be fixed with next ASF pre-release I guess. Thanks for reporting it.

**Comment by JustArchi** [comment]
A simple solution would be to bring back the latest release from back then until new stable ASF with the versioning changes is released.

**Comment by MrBurrBurr** [comment]
Thanks! Should be fixed for now.
