### ISSUE TITLE
asd-iu dont open command, journal and more

### ISSUE THREAD

**Issue by redl5** [JustArchiNET/ASF-ui#868]
IPC does not open the "command"(and other pages) the page is updated and that's it,
pls help!

**Comment by Potatossauro** [comment]
same here but only commands don't open and I receive (WARN ASF > UrlGetToString() Falha na solicitação após 5 tentativas!
[2:45:12 PM] DEBUG ASF > UrlGetToString() Falha na solicitação: https://api.github.com/repos/JustArchiNET/ASF-ui/releases/latest) every time that i click in commands

**Comment by MrBurrBurr** [comment]
Which Version of ASF are you using? Seems to me like you are not using latest stable release.
Update to latest stable release and clear the cache of your browser. Problem should be solved.

**Comment by Potatossauro** [comment]
it's browser problem if you are using Brave disable Brave Shield if didn't work try another browser

**Comment by redl5** [comment]
thank you for feedback, but now it worked, maybe  these are the problems  Steam.
