### ISSUE TITLE
Statistics can't show 99+ bots

### ISSUE THREAD

**Issue by Vital7** [JustArchiNET/ASF-ui#89]

**Comment by Aareksio** [comment]
This is [intended](https://github.com/JustArchiNET/ASF-ui/blob/master/src/components/NavigationBots.vue#L19-L22) as otherwise the number would not fit in available space

**Comment by JustArchi** [comment]
Not intended considering ASF can run 100+ bots easily, you should make `999` the upper limit if anything.
