### ISSUE TITLE
ASF webinterface on Debian 18.04 doesnt work as planned?

### ISSUE THREAD

**Issue by SafeKane** [JustArchiNET/ASF-ui#922]
If I try to set up a bot via the ASF web interface, it will only be shown if I completely restart ASF.
The restart does not work via the web interface either, but only via the console.
Furthermore ASF freezes when I try to enter the 2FA code for a bot.
pls help.

**Comment by JustArchi** [comment]
Hey there! Thank you for contacting our development team at GitHub.

We believe that your issue does not meet our **[contributing guidelines](https://github.com/JustArchiNET/ArchiSteamFarm/blob/master/.github/CONTRIBUTING.md)** referenced during issue creation.

> Before you open an issue please review the contributing guidelines for this repository.
> (...)
> I understand that if my issue is not meeting contributing guidelines specified above, especially if it's a question or technical issue that is not related to ASF development in any way, then it will be closed and left unanswered.

Reason for closing: **technical difficulties using the program are not related to ASF development**. Use appropriate **[support](https://github.com/JustArchiNET/ArchiSteamFarm/blob/master/SUPPORT.md)** channel instead.

Please check out **[our wiki](https://github.com/JustArchiNET/ArchiSteamFarm/wiki)** if you need further help.

Have a nice day!
~Archi
