### ISSUE TITLE
 ui domain host

### ISSUE THREAD

**Issue by MattiasMoenster2019** [JustArchiNET/ASF-ui#934]
Add a way to host the Ui to a website (Dunno if this is already supported could not find anything about it) so the ui can be accessed across the web

**Comment by Abrynos** [comment]
read the wiki. it's there. trust me. Screenshot as proof because people seem to be unable to read: 
![image](https://user-images.githubusercontent.com/6608231/77475461-2871b600-6e19-11ea-9020-0f568af13e0b.png)

**Comment by Aareksio** [comment]
Yes, it is possible, simply setup [reversed proxy](https://github.com/JustArchiNET/ArchiSteamFarm/wiki/IPC#can-i-use-asfs-ipc-behind-a-reverse-proxy-such-as-apache-or-nginx)
