### ISSUE TITLE
Bot name auto-completion in the Commands shell no longer works

### ISSUE THREAD

**Issue by stray-pengo** [JustArchiNET/ASF-ui#937]
## Description
The auto-completion feature for bot names in the Commands shell has stopped working.

## Steps to reproduce
1. Enter the Commands shell.
2. Type an appropriate command e.g. "iq" then the first letter of a running bot, then hit tab

## Expected behavior
Matching bot names will be cycled

## Current behavior
Does nothing.

**Comment by MrBurrBurr** [comment]
Thank you for reporting it. I will look into it when I have time.
