### ISSUE TITLE
Bot's profile link

### ISSUE THREAD

**Issue by Saacy** [JustArchiNET/ASF-ui#95]
It used to take 1 click to open bot's Steam profile. Now you need to open modal and then click avatar pic. We really need some link to open bot`s profile without opening modal.

Also screen is scrolling to the top on each modal opening.

**Comment by MrBurrBurr** [comment]
I opened a separate issue for the scrolling bug.

**Comment by Aareksio** [comment]
@MrBurrBurr Could you please make avatar a link again?

**Comment by MrBurrBurr** [comment]
Sure will do that.
