### ISSUE TITLE
Don't clone trade token

### ISSUE THREAD

**Issue by SuperSandro2000** [JustArchiNET/ASF-ui#957]
## Purpose

When a bot gets cloned the trade token is not cleared which is not useful cause it is always wrong.

## Solution

Empty the trade token when a bot gets cloned.

**Comment by JustArchi** [comment]
> When a bot gets cloned the trade token is not cleared which is not useful cause it is always wrong.

Why? This is trade token of the master, not the bot, if the master stays the same, so will the token.

**Comment by SuperSandro2000** [comment]
🤦 I never noticed that this was totally wrong cause I have all my bots on my friends list. Thanks for clearing up that derp.
