### ISSUE TITLE
Failed due to error: You can't send trade to yourself!

### ISSUE THREAD

**Issue by 17mafo** [JustArchiNET/ASF-ui#959]
When I try to get the bots to send me all there inventory items 11 of the bots says this
![image](https://user-images.githubusercontent.com/42637131/81710659-38019880-9473-11ea-9487-37f74bff9024.png)

and the rest just says they there inventory is empty!
Could not find anything or anyone talking about this problem
They all have the same correct SteamtradeToken. And I'm friends with all of them.

Could also just be that I fucked something up.

I have 14 bots instead of 10 that's recommended.

Thanks in advance! :)

**Comment by Abrynos** [comment]
That is neither an issue for this repository nor for the main repository. Since you are out of support as you are running 14 bots you probably would not get an answer anyways. Small hint: This is due to a misconfiguration on your side and you should look at what wiki says.
