### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by idunnoooooo** [JustArchiNET/ASF-ui#960]
is there a way to make multiple accounts for dashboard? For example i want to create account for friend so when he logins with his password he got access to only his bot

**Comment by Abrynos** [comment]
No. This is not in the base project and therefore not in the UI project. Your friend can run ASF himself. If he somehow is not able to run ASF (which he could also use on the PC he wants to access the UI from) you can just run another instance of ASF, which uses another port.

**Comment by idunnoooooo** [comment]
> No. This is not in the base project and therefore not in the UI project. Your friend can run ASF himself. If he somehow is not able to run ASF (which he could also use on the PC he wants to access the UI from) you can just run another instance of ASF, which uses another port.

but how i can run another instance with another port?

**Comment by Abrynos** [comment]
by reading wiki. you may want to read about command line arguments and IPC(-configuration)

**Comment by idunnoooooo** [comment]
> by reading wiki. you may want to read about command line arguments and IPC(-configuration)

i readed all about command line arguments and IPC and theres nothing about changing ports or im just blind

**Comment by Abrynos** [comment]
in that case you are just blind

**Comment by idunnoooooo** [comment]
> in that case you are just blind

nvm found it thanks! and do u know where is site  .html located?

**Comment by Ryzhehvost** [comment]
Multiple accounts for ASF-ui is impossible by design. All IPC requests to ASF are executed with SteamOwnerID permissions, so you either have access to everything or no access at all. So, to implement this it would be necessary to make changes in ASF itself, and only then add appropriate changes to ASF-ui.
