### ISSUE TITLE
Not able to get onto ASF UI even with correct password

### ISSUE THREAD

**Issue by matcho13579** [JustArchiNET/ASF-ui#976]
## Description
Not able to get to ASF UI

## Steps to reproduce
1. Start ASF
2. Open http://127.0.0.1:1242/
3. Nothing happens - I just get black screen with "there is no webpage found"

## Expected behavior
ASF UI opens normally

## Current behavior
ASF UI webpage not showing

## Additional information
Using Docker version of ASF with Docker for Windows, Linux containers mode

ASF version 4.2.1.8

I can see from the logs that ASF IPC is started, also I'm able to see it's running on API endpoint ( http://127.0.0.1:1242/Api/ASF?password=xxxx ), response is
{"Result":{"BuildVariant":"linux-x64","GlobalConfig":{"Blacklist":[267420,303700,335590,368020,425280,480730],"Headless":true,"IPC":true,"IPCPassword":"xxxx","MaxTradeHoldDuration":0,"SteamOwnerID":xxxxxx,"s_SteamOwnerID":"xxxxx"},"MemoryUsage":32901,"ProcessStartTime":"2020-05-30T16:04:17.89+00:00","Version":"4.2.1.8"},"Message":"OK","Success":true}

ASF itself works without any issues, as I'm able to issue commands using Steam chat

Container itself looks like this: 
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS                   PORTS                    NAMES
bb5f133a2420        justarchi/archisteamfarm   "./ArchiSteamFarm-Se…"   9 minutes ago       Up 9 minutes (healthy)   0.0.0.0:1242->1242/tcp   asf

Run command for the container: docker run -it -p 1242:1242 -v C:\Users\match\Desktop\ASF\ASFDocker:/app/config --restart unless-stopped --name asf justarchi/archisteamfarm -d

**Comment by MrBurrBurr** [comment]
This looks more like a docker problem to me. Sadly I am not very familiar with docker but I guess its an issue with redirecting traffic from the container to the host?! Maybe @JustArchi can help out here.

**Comment by JustArchi** [comment]
This is much deeper issue: https://github.com/dotnet/runtime/issues/37208

**Comment by JustArchi** [comment]
ASF core is tracking this issue in https://github.com/JustArchiNET/ArchiSteamFarm/issues/1812

Nothing to do in ASF-ui in regards to this.
