### ISSUE TITLE
ASF-ui still save "Name" property into botName.json while creating bots

### ISSUE THREAD

**Issue by deluxghost** [JustArchiNET/ASF-ui#985]
## Description
As mentioned in #468 and #536, there was a bug that asf-ui tried to save a property `Name` into json file of the bot while renaming the existing bot, but ASF doesn't have a `Name` property.

That issue was fixed by removing rename bot feature, but I found ASF-ui still try to save the `Name` while **creating** a bot.

A minimal request:
![image](https://user-images.githubusercontent.com/5835759/83528779-19476c80-a51c-11ea-945e-a1ca9031214b.png)

## Steps to reproduce
1. Download latest ASF.
2. Enable IPC (`{"IPC": true}`)
3. Open http://127.0.0.1:1242/
4. Create a new bot with its name, steamlogin and password
5. Check the new json file in the config folder.

## Expected behavior
```json
{
  "SteamLogin": "xxx",
  "SteamPassword": "xxx"
}
```

## Current behavior
```json
{
  "SteamLogin": "xxx",
  "SteamPassword": "xxx",
  "Name": "xxx"
}
```

## Additional information
I suggest redesign the struct of a bot, spilt bot config out, for example:

```json
{
    "name": "xxx",
    "config": {
        "SteamLogin": "xxx",
        ......
    }
}
```

**Comment by JustArchi** [comment]
> That issue was fixed by removing rename bot feature, but I found ASF-ui still try to save the Name while creating a bot.

... Probably because removing a feature is never a "fix" for anything 😕

**Comment by deluxghost** [comment]
yes, TBH I was surprised when I found this issue (again)

**Comment by MrBurrBurr** [comment]
Thank you, nice issue description :)
