### ISSUE TITLE
'Game Names Only' works incorrectly

### ISSUE THREAD

**Issue by AndrewRAN** [JustArchiNET/ASF-ui#986]
## Description
When I tweaked the setting 'Game Names Only' and set it to true, it behaved differently from my expectations and I think that's a bug.

## Steps to reproduce
Have an account that has at least several games to be farmed.
Set 'Game Names Only' to true and click on any bot's nickname on IPC->Bots page.

## Expected behavior
I expected the game names to display properly so all of them can be read with ease.

## Current behavior
Game names look messy and overlap each other, so some names cannot be read at all. Also if the light theme is used then nothing can't be read at all because the background color is almost the same as the text color itself.

## Screenshots
https://imgur.com/a/xN4AyYf

**Comment by MrBurrBurr** [comment]
Thank you for reporting it. I will fix it as soon as I got some time! :)
