### ISSUE TITLE
Make the bot filtering a bit clearer

### ISSUE THREAD

**Issue by AndrewRAN** [JustArchiNET/ASF-ui#987]
## Purpose
The current 'glowy' highlight of selected categories is only noticeable if you knew about the feature before or by accident, there's no way you can call that clear (at least for the 'Farming' filter because it's green too). For example I clicked on some filter categories several times while I only had one account and the account was in both of them so I saw no effect and thought that's just categories and the buttons don't surve any interactive purpose. After I added another bot (while I only had 'Farming' category enabled, it's like adding 1 or 1.5 pixel outline of the same color to an element, barely noticeable), it didn't appear on the page because it had no cards to farm. At first I thought that's a bug and went here to submit a bug report issue. But then I noticed that it's all right if opened in incognito mode. By accident I tweaked those filters two or three more times and only after that it became clear that it actually has a purpose and can filter bots. Of course it's my fault but if there was a clear checkbox or it changed its background or something I'm sure that I would get the feature after the first click.

## Solution
Make the filters change a bit more noticeably, like add an outline or at least make the green glowing more noticeable on the green 'Farming' filter, because that was the thing that I stumbled upon myself. Other categories have a clear green outline and I personally had no problems with those. I would change the border color to something pretty close to white (#dcdcdc) and it became much clearer.

## Additional information
I do understand that's a very minor change but a reasonable one (IMHO of course).

**Comment by MrBurrBurr** [comment]
I agree that this filtering feature is a bit hidden and not intuitive to use but I think the green glow adds a proper visible difference. Maybe a notification would help out? Something like this:

![info](https://user-images.githubusercontent.com/31552675/83689596-9abbff00-a5ef-11ea-865e-79ae99ec0039.gif)

**Comment by AndrewRAN** [comment]
Green glow is really good but not with the Farming category. Notification is kind of too much for this I think.

**Comment by MrBurrBurr** [comment]
![image](https://user-images.githubusercontent.com/31552675/84038404-322ea280-a9a0-11ea-84d8-86af66d88183.png)
Would this be more visible to you? Or any other idea on how to make it more visible?

**Comment by AndrewRAN** [comment]
Pretty much what I suggested. Looks very bright and can be seen even if you are unaware.
